// Package authlog provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package authlog

import (
	apierrors "gitlab.com/digilab.overheid.nl/ecosystem/ftv/open-ftv/oas/errors"
)

// Defines values for AuthlogEntryStatus.
const (
	Error AuthlogEntryStatus = "Error"
	Ok    AuthlogEntryStatus = "Ok"
	Unset AuthlogEntryStatus = "Unset"
)

// Valid indicates whether the value is a known member of the AuthlogEntryStatus enum.
func (e AuthlogEntryStatus) Valid() bool {
	switch e {
	case Error:
		return true
	case Ok:
		return true
	case Unset:
		return true
	default:
		return false
	}
}

// AuthlogEntries A set of Authorization Decision Log entries.
type AuthlogEntries = []AuthlogEntry

// AuthlogEntry An Authorization Decision Log entry.
type AuthlogEntry struct {
	// Created Timestamp the entry was created.
	Created string `json:"created,omitempty"`

	// Engine Details of the PDP engine.
	Engine map[string]interface{} `json:"engine,omitempty"`

	// EventName Logius ADL event_name.
	EventName string `json:"eventName,omitempty"`

	// Id Unique identifier.
	Id int64 `json:"id,omitempty"`

	// Information Information (attributes) used during the authorization process.
	Information map[string]interface{} `json:"information,omitempty"`

	// ParentSpanId Logius ADL parent span identifier (W3C Trace Context format), when this record is a child span.
	ParentSpanId string `json:"parentSpanId,omitempty"`

	// Policies Unique identifier of the policy bundle used during the authorization process.
	Policies string `json:"policies,omitempty"`

	// Request Logius ADL body (adl.core.request); AuthZEN request.
	Request map[string]interface{} `json:"request,omitempty"`

	// RequestType Type of AuthZEN request.
	RequestType string `json:"requestType,omitempty"`

	// Resource Logius ADL resource; identifies the producer of the log record.
	Resource map[string]interface{} `json:"resource,omitempty"`

	// Response Logius ADL body (adl.core.response); AuthZEN response.
	Response map[string]interface{} `json:"response,omitempty"`

	// SpanId Logius ADL span identifier (W3C Trace Context format).
	SpanId string `json:"spanId,omitempty"`

	// Status Logius ADL evaluation status.
	Status AuthlogEntryStatus `json:"status,omitempty"`

	// Timestamp Logius ADL timestamp; milliseconds since Unix epoch when the decision was made.
	Timestamp int64 `json:"timestamp,omitempty"`

	// TraceId Logius ADL trace identifier (W3C Trace Context format).
	TraceId string `json:"traceId,omitempty"`
}

// AuthlogEntryStatus Logius ADL evaluation status.
type AuthlogEntryStatus string

// ActionName defines model for ActionName.
type ActionName = string

// DecisionId defines model for DecisionId.
type DecisionId = int64

// EndTimestamp defines model for EndTimestamp.
type EndTimestamp = string

// Limit defines model for Limit.
type Limit = int

// Policies defines model for Policies.
type Policies = []string

// RecentPeriod defines model for RecentPeriod.
type RecentPeriod = string

// RequestTypes defines model for RequestTypes.
type RequestTypes = []string

// ResourceId defines model for ResourceId.
type ResourceId = string

// ResourceType defines model for ResourceType.
type ResourceType = string

// SpanId defines model for SpanId.
type SpanId = string

// StartTimestamp defines model for StartTimestamp.
type StartTimestamp = string

// SubjectId defines model for SubjectId.
type SubjectId = string

// SubjectType defines model for SubjectType.
type SubjectType = string

// TraceId defines model for TraceId.
type TraceId = string

// AccessDenied Error response model (as defined by RFC9457).
type AccessDenied = apierrors.ErrorResponse

// AuthlogResponse A set of Authorization Decision Log entries.
type AuthlogResponse = AuthlogEntries

// BadRequest Error response model (as defined by RFC9457).
type BadRequest = apierrors.ErrorResponse

// NotAuthorized Error response model (as defined by RFC9457).
type NotAuthorized = apierrors.ErrorResponse

// NotFound Error response model (as defined by RFC9457).
type NotFound = apierrors.ErrorResponse

// UnexpectedError Error response model (as defined by RFC9457).
type UnexpectedError = apierrors.ErrorResponse

// GetAdlEntriesParams defines parameters for GetAdlEntries.
type GetAdlEntriesParams struct {
	// Id Select exact decision log identifier.
	//
	// This is mutually exclusive with all other parameters.
	Id DecisionId `form:"id,omitempty" json:"id,omitempty"`

	// Start Filter entries with a created timestamp greater of equal this (RFC3339).
	//
	// This parameter is mutually exclusive with the recent period.
	Start StartTimestamp `form:"start,omitempty" json:"start,omitempty"`

	// End Filter entries with a created timestamp lesser of equal this (RFC3339).
	//
	// Default is the current timestamp.
	End EndTimestamp `form:"end,omitempty" json:"end,omitempty"`

	// Recent Select a period upto and including the current timestamp.
	//
	// This parameter is mutually exclusive with the start timestamp.
	//
	// The string should be formatted as a to Golang duration.
	// E.g.:
	// - "1m"       = 1 minute.
	// - "12s"      = 12 seconds.
	// - "3h"       = 3 hours.
	// - "1h10m15s" = 1 hour, 10 minutes and 15 seconds.
	Recent RecentPeriod `form:"recent,omitempty" json:"recent,omitempty"`

	// Types Filter entries matching one of the AuthZEN request types.
	//
	// Valid values are:
	// - evaluation
	// - evaluations
	// - search_subject
	// - search_action
	// - search_resource
	//
	// Duplicate values are not allowed.
	Types RequestTypes `form:"types,omitempty" json:"types,omitempty"`

	// Policies Filter entries matching one of the policy bundle identifiers.
	//
	// Maximum 10 bundle identifiers can be supplied.
	// Duplicate values are not allowed.
	Policies Policies `form:"policies,omitempty" json:"policies,omitempty"`

	// TraceId Filter entries with a matching Logius ADL trace identifier (W3C Trace Context format).
	//
	// Must be exactly 32 characters in hexadecimal.
	TraceId TraceId `form:"traceId,omitempty" json:"traceId,omitempty"`

	// SpanId Filter entries with a matching Logius ADL span identifier (W3C Trace Context format).
	//
	// Must be exactly 16 characters in hexadecimal.
	SpanId SpanId `form:"spanId,omitempty" json:"spanId,omitempty"`

	// SubjectType Filter entries with a matching subject type.
	SubjectType SubjectType `form:"subjectType,omitempty" json:"subjectType,omitempty"`

	// SubjectId Filter entries with a matching subject identifier.
	//
	// Use of this parameter may considerably impact performance.
	SubjectId SubjectId `form:"subjectId,omitempty" json:"subjectId,omitempty"`

	// ActionName Filter entries with a matching action name.
	//
	// Use of this parameter may considerably impact performance.
	ActionName ActionName `form:"actionName,omitempty" json:"actionName,omitempty"`

	// ResourceType Filter entries with a matching resource type.
	//
	// Use of this parameter may considerably impact performance.
	ResourceType ResourceType `form:"resourceType,omitempty" json:"resourceType,omitempty"`

	// ResourceId Filter entries with a matching resource identifier.
	//
	// Use of this parameter may considerably impact performance.
	ResourceId ResourceId `form:"resourceId,omitempty" json:"resourceId,omitempty"`

	// Limit Limit the result to this many entries.
	//
	// The default limit is 100 entries.
	// All entries are sorted in descending order of creation.
	Limit Limit `form:"limit,omitempty" json:"limit,omitempty"`
}
