// Package authlog provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package authlog

// AuthlogResourceResponse The response for retrieving an authorisation log resource summary.
type AuthlogResourceResponse struct {
	Rvva []struct {
		Count  int    `json:"count,omitempty"`
		RvvaId string `json:"rvvaId,omitempty"`
	} `json:"rvva,omitempty"`

	// Total Total count.
	Total int `json:"total,omitempty"`
}

// ErrorResponse The response for an error (as defined by RFC9457).
type ErrorResponse struct {
	// Detail Detailed description of the problem.
	Detail string `json:"detail,omitempty"`

	// Instance Identification of the problem instance.
	Instance string `json:"instance,omitempty"`

	// Status Status code of the problem.
	Status int `json:"status,omitempty"`

	// Title Summary of the problem.
	Title string `json:"title,omitempty"`

	// Type Identification of the problem.
	Type string `json:"type,omitempty"`
}

// ResourceKey defines model for ResourceKey.
type ResourceKey = string

// AccessDenied The response for an error (as defined by RFC9457).
type AccessDenied = ErrorResponse

// BadRequest The response for an error (as defined by RFC9457).
type BadRequest = ErrorResponse

// NotAuthorized The response for an error (as defined by RFC9457).
type NotAuthorized = ErrorResponse

// NotFound The response for an error (as defined by RFC9457).
type NotFound = ErrorResponse

// UnexpectedError The response for an error (as defined by RFC9457).
type UnexpectedError = ErrorResponse
