openapi: 3.0.0

info:
  title: Authorization Decision Log queries.
  version: 1.0.0
  description: |
    OpenAPI specification for searching and retrieving entries from the Authorization Decision Log.
  contact:
    name: G. Juijn
    url: https://gitlab.com/digilab.overheid.nl/ecosystem/ftv/open-ftv

servers:
  - url: https://localhost:8080/v1
    description: Local server.

tags:
  - name: adl
    description: Queries on the Authorization Decision Log.

paths:
  /adl/entries:
    get:
      operationId: "get-adl-entries"
      summary: Query Authorization Decision Log.
      description: |
        Endpoint to search for and retrieve Authorization Decision Log entries.

        Resulting entries are sorted in descending order of creation.

      tags:
        - adl
      parameters:
        - $ref: "#/components/parameters/DecisionId"
        - $ref: "#/components/parameters/StartTimestamp"
        - $ref: "#/components/parameters/EndTimestamp"
        - $ref: "#/components/parameters/RecentPeriod"
        - $ref: "#/components/parameters/RequestTypes"
        - $ref: "#/components/parameters/Policies"
        - $ref: "#/components/parameters/TraceId"
        - $ref: "#/components/parameters/SpanId"
        - $ref: "#/components/parameters/SubjectType"
        - $ref: "#/components/parameters/SubjectId"
        - $ref: "#/components/parameters/ActionName"
        - $ref: "#/components/parameters/ResourceType"
        - $ref: "#/components/parameters/ResourceId"
        - $ref: "#/components/parameters/Limit"
      responses:
        "200":
          $ref: "#/components/responses/AuthlogResponse"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/NotAuthorized"
        "403":
          $ref: "#/components/responses/AccessDenied"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/UnexpectedError"

components:
  parameters:
    DecisionId:
      in: query
      name: id
      schema:
        type: integer
        format: int64
      description: |
        Select exact decision log identifier.
        
        This is mutually exclusive with all other parameters.

    RecentPeriod:
      in: query
      name: recent
      schema:
        type: string
      description: |
        Select a period upto and including the current timestamp.
        
        This parameter is mutually exclusive with the start timestamp.
        
        The string should be formatted as a to Golang duration.
        E.g.:
        - "1m"       = 1 minute.
        - "12s"      = 12 seconds.
        - "3h"       = 3 hours.
        - "1h10m15s" = 1 hour, 10 minutes and 15 seconds.

    StartTimestamp:
      in: query
      name: start
      schema:
        type: string
        maxLength: 36
      description: |
        Filter entries with a created timestamp greater of equal this (RFC3339).
        
        This parameter is mutually exclusive with the recent period.

    EndTimestamp:
      in: query
      name: end
      schema:
        type: string
        maxLength: 36
      description: |
        Filter entries with a created timestamp lesser of equal this (RFC3339).
        
        Default is the current timestamp.

    RequestTypes:
      in: query
      name: types
      schema:
        type: array
        items:
          type: string
          maxLength: 20
      description: |
        Filter entries matching one of the AuthZEN request types.

        Valid values are:
        - evaluation
        - evaluations
        - search_subject
        - search_action
        - search_resource

        Duplicate values are not allowed.

    Policies:
      in: query
      name: policies
      schema:
        type: array
        items:
          type: string
          maxLength: 100
      description: |
        Filter entries matching one of the policy bundle identifiers.
        
        Maximum 10 bundle identifiers can be supplied.
        Duplicate values are not allowed.

    TraceId:
      in: query
      name: traceId
      schema:
        type: string
        minLength: 32
        maxLength: 32
      description: |
        Filter entries with a matching W3C trace identifier.

        Must be exactly 32 characters in hexadecimal.

    SpanId:
      in: query
      name: spanId
      schema:
        type: string
        minLength: 16
        maxLength: 16
      description: |
        Filter entries with a matching W3C span identifier.

        Must be exactly 16 characters in hexadecimal.

    SubjectType:
      in: query
      name: subjectType
      schema:
        type: string
        maxLength: 100
      description: Filter entries with a matching subject type.

    SubjectId:
      in: query
      name: subjectId
      schema:
        type: string
        maxLength: 100
      description: |
        Filter entries with a matching subject identifier.

        Use of this parameter may considerably impact performance.

    ActionName:
      in: query
      name: actionName
      schema:
        type: string
        maxLength: 100
      description: |
        Filter entries with a matching action name.

        Use of this parameter may considerably impact performance.

    ResourceType:
      in: query
      name: resourceType
      schema:
        type: string
        maxLength: 100
      description: |
        Filter entries with a matching resource type.

        Use of this parameter may considerably impact performance.

    ResourceId:
      in: query
      name: resourceId
      schema:
        type: string
        maxLength: 100
      description: |
        Filter entries with a matching resource identifier.

        Use of this parameter may considerably impact performance.

    Limit:
      in: query
      name: limit
      schema:
        type: integer
        maximum: 1000
      description: |
        Limit the result to this many entries.
        
        The default limit is 100 entries.
        All entries are sorted in descending order of creation.

  responses:
    AuthlogResponse:
      description: Log entries found.
      headers:
        API-Version:
          schema:
            type: string
          description: Full version number of the API.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/AuthlogEntries"

    BadRequest:
      description: Bad request.
      headers:
        API-Version:
          schema:
            type: string
          description: Full version number of the API.
      content:
        application/json:
          schema:
            $ref: '../errors/openapi.yaml#/components/schemas/ErrorResponse'

    NotAuthorized:
      description: Not authorized.
      headers:
        API-Version:
          schema:
            type: string
          description: Full version number of the API.
      content:
        application/json:
          schema:
            $ref: '../errors/openapi.yaml#/components/schemas/ErrorResponse'

    AccessDenied:
      description: Access denied.
      headers:
        API-Version:
          schema:
            type: string
          description: Full version number of the API.
      content:
        application/json:
          schema:
            $ref: '../errors/openapi.yaml#/components/schemas/ErrorResponse'

    NotFound:
      description: Resource not found.
      headers:
        API-Version:
          schema:
            type: string
          description: Full version number of the API.
      content:
        application/json:
          schema:
            $ref: '../errors/openapi.yaml#/components/schemas/ErrorResponse'
          examples:
            GET_ATTRIBUTE_404_NOTFOUND:
              summary: Unsuccessful retrieval of unknown attribute.
              value:
                title: Not found

    UnexpectedError:
      description: Unexpected error.
      headers:
        API-Version:
          schema:
            type: string
          description: Full version number of the API.
      content:
        application/json:
          schema:
            $ref: '../errors/openapi.yaml#/components/schemas/ErrorResponse'

  schemas:
    AuthlogEntries:
      type: array
      description: A set of Authorization Decision Log entries.
      items:
        $ref: "#/components/schemas/AuthlogEntry"

    AuthlogEntry:
      type: object
      description: An Authorization Decision Log entry.
      properties: 
        id:
          type: integer
          format: int64
          description: Unique identifier.
        created:
          type: string
          maxLength: 32
          description: Timestamp the entry was created.
        requestType:
          type: string
          maxLength: 20
          description: Type of AuthZEN request.
        policies:
          type: string
          maxLength: 100
          description: Unique identifier of the policy bundle used during the authorization process.
        request:
          type: object
          description: AuthZEN request.
          anyOf:
            - $ref: "#/components/schemas/EvaluationObject"
            - $ref: "#/components/schemas/EvaluationsObject"
            - $ref: "#/components/schemas/SearchObject"
            - $ref: "#/components/schemas/SearchActionObject"
        response:
          type: object
          description: AuthZEN response.
          anyOf:
            - $ref: "#/components/schemas/EvaluationDecision"
            - $ref: "#/components/schemas/EvaluationsDecision"
            - $ref: "#/components/schemas/SearchResults"
            - $ref: "#/components/schemas/SearchActionResults"
        information:
          type: object
          description: Information (attributes) used during the authorization process.
        engine:
          type: object
          description: Details of the PDP engine.
        traceId:
          type: string
          minLength: 32
          maxLength: 32
          description: W3C trace identifier from the authorization request.
        spanId:
          type: string
          minLength: 16
          maxLength: 16
          description: W3C span identifier from the authorization request.

    Entity:
      type: object
      description: |
        The entity associated with an authorization request.
        This can be the subject (e.g. principal) or the resource.
      properties:
        type:
          type: string
          description: The type of the entity.
          example: "user"
        id:
          type: string
          description: The unique ID of the entity.
          example: "alice"
        properties:
          type: object
          description: Optional attributes for the entity.
      required:
        - type
        - id

    Action:
      type: object
      description: The action associated with an authorization request.
      properties:
        name:
          type: string
          description: The name of the action.
          example: "can_read"
        properties:
          type: object
          description: Optional attributes for the action.
      required:
        - name

    ReasonField:
      type: object
      description: Map of one or more reasons, with a language-identifier as the key.

    ReasonObject:
      type: object
      description: Specifies a particular reason.
      properties:
        reason_admin:
          $ref: "#/components/schemas/ReasonField"
        reason_user:
          $ref: "#/components/schemas/ReasonField"

    EvaluationObject:
      type: object
      description: Evaluation object model.
      properties:
        subject:
          $ref: "#/components/schemas/Entity"
        action:
          $ref: "#/components/schemas/Action"
        resource:
          $ref: "#/components/schemas/Entity"
        context:
          description: Optional context of the request.
          type: object
      required:
        - subject
        - action
        - resource

    EvaluationDecision:
      type: object
      description: Evaluation decision model.
      properties:
        decision:
          type: boolean
          description: true if the request is authorized.
        context:
          $ref: "#/components/schemas/ReasonObject"
      required:
        - decision

    EvaluationsObject:
      type: object
      description: Evaluations object model.
      properties:
        evaluations:
          type: array
          description: list of evaluation requests to test.
          items:
            $ref: "#/components/schemas/EvaluationObject"
        subject:
          $ref: "#/components/schemas/Entity"
        action:
          $ref: "#/components/schemas/Action"
        resource:
          $ref: "#/components/schemas/Entity"
        context:
          description: Optional default context of the request.
          type: object
        options:
          type: object
          description: Options for the evaluations request.
          properties:
            evaluation_semantics:
              type: string
              description: |
                By default, every request in the evaluations array is executed and a response returned in the same array order.
                This is the most common use-case for boxcarring multiple evaluation requests in a single payload.
                
                To select the desired evaluations semantic, use exactly one of the following values:
                  - execute_all = default.
                  - deny_on_first_deny = halt processing after first deny.
                  - permit_on_first_permit = halt processing after first allow.
      required:
        - evaluations

    EvaluationsDecision:
      type: object
      description: Evaluations decision model.
      properties:
        evaluations:
          type: array
          description: List of evaluation decisions.
          items:
            $ref: "#/components/schemas/EvaluationDecision"
      required:
        - evaluations

    PageRequest:
      type: object
      description: Pagination options.
      properties:
        token:
          type: string
          description: Token used for pagination.
          example: "a3M9NDU2O3N6PTI="
        limit:
          type: integer
          description: Maximum number of results to return.
          example: 2
        properties:
          type: object
          description: Implementation-specific pagination request attributes.

    PageResponse:
      type: object
      description: Pagination options.
      properties:
        next_token:
          type: string
          description: Token used for pagination.
          example: "a3M9NDU2O3N6PTI="
        count:
          type: integer
          description: Number of results returned.
          example: 2
        total:
          type: integer
          description: Total number of results available.
          example: 3
        properties:
          type: object
          description: Implementation-specific pagination response attributes.

    SearchEntity:
      type: object
      description: |
        An entity (subject or resource) associated with a search request.
        This means the id can be empty.
      properties:
        type:
          type: string
          description: The type of the search entity.
          example: "user"
        id:
          type: string
          description: The unique ID of the search entity.
          example: "alice"
        properties:
          type: object
          description: Optional attributes for the search entity.
      required:
        - type

    SearchObject:
      type: object
      description: Search object model.
      properties:
        subject:
          $ref: "#/components/schemas/SearchEntity"
        action:
          $ref: "#/components/schemas/Action"
        resource:
          $ref: "#/components/schemas/SearchEntity"
        context:
          description: Optional context of the request.
          type: object
        page:
          $ref: "#/components/schemas/PageRequest"
      required:
        - subject
        - action
        - resource

    SearchResult:
      type: object
      description: Search result model.
      properties:
        type:
          type: string
          description: The type of the entity.
          example: "user"
        id:
          type: string
          description: The unique ID of the entity.
          example: "alice"

    SearchResults:
      type: object
      description: Search results model.
      properties:
        results:
          type: array
          description: List of search results.
          items:
            $ref: "#/components/schemas/SearchResult"
        page:
          $ref: "#/components/schemas/PageResponse"
      required:
        - results

    SearchActionObject:
      type: object
      description: Search action object model.
      properties:
        subject:
          $ref: "#/components/schemas/Entity"
        resource:
          $ref: "#/components/schemas/Entity"
        context:
          description: Optional context of the request.
          type: object
        page:
          $ref: "#/components/schemas/PageRequest"
      required:
        - subject
        - resource

    SearchActionResult:
      type: object
      description: Search action result model.
      properties:
        name:
          type: string
          description: The name of the action.
          example: "can_read"

    SearchActionResults:
      type: object
      description: Search action results model.
      properties:
        results:
          type: array
          description: List of action search results.
          items:
            $ref: "#/components/schemas/SearchActionResult"
        page:
          $ref: "#/components/schemas/PageResponse"
      required:
        - results
