// Package settings provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package settings

import (
	apierrors "gitlab.com/digilab.overheid.nl/ecosystem/ftv/open-ftv/oas/errors"
)

// Defines values for SettingsLogoMediaType.
const (
	Imagejpeg   SettingsLogoMediaType = "image/jpeg"
	Imagepng    SettingsLogoMediaType = "image/png"
	ImagesvgXml SettingsLogoMediaType = "image/svg+xml"
	Imagewebp   SettingsLogoMediaType = "image/webp"
)

// Valid indicates whether the value is a known member of the SettingsLogoMediaType enum.
func (e SettingsLogoMediaType) Valid() bool {
	switch e {
	case Imagejpeg:
		return true
	case Imagepng:
		return true
	case ImagesvgXml:
		return true
	case Imagewebp:
		return true
	default:
		return false
	}
}

// Error Error response model (as defined by RFC9457).
type Error = apierrors.ErrorResponse

// Settings The manager ui settings.
type Settings struct {
	// HeaderColor Background color of the header, as a hex color code.
	HeaderColor string `json:"headerColor"`

	// HeaderTitle Header title.
	HeaderTitle string `json:"headerTitle"`

	// Logo Logo shown on the left side of the header, base64-encoded. Omit or leave empty to remove the logo.
	Logo []byte `json:"logo,omitempty"`

	// LogoMediaType Media type of the logo, required if logo is set.
	LogoMediaType SettingsLogoMediaType `json:"logoMediaType,omitempty"`

	// TitleColor Text color of the header title, as a hex color code.
	TitleColor string `json:"titleColor"`

	// Updated Timestamp the settings were last updated (RFC3339 format).
	Updated string `json:"updated,omitempty"`

	// UpdatedBy User that last updated the settings.
	UpdatedBy string `json:"updatedBy,omitempty"`
}

// SettingsLogoMediaType Media type of the logo, required if logo is set.
type SettingsLogoMediaType string

// AccessDenied Error response model (as defined by RFC9457).
type AccessDenied = Error

// BadRequest Error response model (as defined by RFC9457).
type BadRequest = Error

// NotAuthorized Error response model (as defined by RFC9457).
type NotAuthorized = Error

// SettingsResponse The manager ui settings.
type SettingsResponse = Settings

// UnexpectedError Error response model (as defined by RFC9457).
type UnexpectedError = Error

// UpdateSettingsJSONRequestBody defines body for UpdateSettings for application/json ContentType.
type UpdateSettingsJSONRequestBody = Settings
