package models

// List of standard attribute keys.
const (
	AttrAPIKey          = "api_key"
	AttrAction          = "action"
	AttrBasicPswd       = "basic_pswd"
	AttrBasicUser       = "basic_user"
	AttrBody            = "body"
	AttrClaims          = "claims"
	AttrClientIP        = "ip_address"
	AttrClientPrincipal = "client_principal"
	AttrContentType     = "content_type"
	AttrCoreUser        = "core_user"
	AttrDeviceID        = "device_id"
	AttrDoelbinding     = "doelbinding"
	AttrFSC             = "fsc"
	AttrGrondslag       = "grondslag"
	AttrHTTP            = "http"
	AttrHeaders         = "headers"
	AttrHost            = "host"
	AttrJWT             = "jwt"
	AttrMethod          = "method"
	AttrPath            = "path"
	AttrPathParts       = "path_parts"
	AttrPrincipal       = "principal"
	AttrQuery           = "query"
	AttrRequestTime     = "request_time"
	AttrResource        = "resource"
	AttrRoles           = "roles"
	AttrRvvaID          = "rvva_id"
	AttrScheme          = "scheme"
	AttrSpanID          = "span_id"
	AttrTaak            = "taak"
	AttrTime            = "time"
	AttrTraceID         = "trace_id"
	AttrTraceParent     = "traceparent" // https://www.w3.org/TR/trace-context/
	AttrTraceState      = "tracestate"  // https://www.w3.org/TR/trace-context/
	AttrValid           = "valid"
	AttrZaakType        = "zaak_type"
)
