variables:
  RENOVATE_REPOSITORIES: $CI_PROJECT_PATH

stages:
  - Version
  - Linter
  - UnitTests
  - Build
  - Publish
  - deploy

include:
  - ".gitlab/ci/**.yml"
  # https://gitlab.com/gitlab-com/gl-infra/renovate/renovate-runner/-/blob/main/templates/renovate.gitlab-ci.yml?ref_type=heads
  - project: 'renovate-bot/renovate-runner'
    file: '/templates/renovate.gitlab-ci.yml'
