variables:
  pattern_prerelease_tag: '/^v\d*\.\d*\.\d*-rc\.\d*$/'
  pattern_release_tag: '/^v\d*\.\d*\.\d*$/'
  RENOVATE_REPOSITORIES: $CI_PROJECT_PATH

stages:
  - Version
  - Linter
  - UnitTests
  - Build
  - Release
  - Manifest
  - deploy
#  - Redeploy
#  - Security
#  - E2E tests
#  - Tools
#  - external
#  - On Failure

include:
  - ".gitlab/ci/**.yml"
  # https://gitlab.com/gitlab-com/gl-infra/renovate/renovate-runner/-/blob/main/templates/renovate.gitlab-ci.yml?ref_type=heads
  - project: 'renovate-bot/renovate-runner'
    file: '/templates/renovate.gitlab-ci.yml'
