# yaml-language-server: $schema=https://raw.githubusercontent.com/deepmap/oapi-codegen/HEAD/configuration-schema.json
package: errors
output: errors.go
generate:
  models: true
output-options:
  skip-prune: true
  prefer-skip-optional-pointer: true
