// Package errors provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package errors

// ErrorCode Stable, machine-readable error code (e.g. "E10010") that clients can use to look up
// their own localized (e.g. Dutch) message. Not part of RFC9457; an OpenFTV extension.
type ErrorCode = string

// ErrorResponse Error response model (as defined by RFC9457).
type ErrorResponse struct {
	// Code Stable, machine-readable error code (e.g. "E10010") that clients can use to look up
	// their own localized (e.g. Dutch) message. Not part of RFC9457; an OpenFTV extension.
	Code ErrorCode `json:"code,omitempty"`

	// Detail Detailed description of the problem.
	Detail string `json:"detail,omitempty"`

	// Instance Identification of the problem instance.
	Instance string `json:"instance,omitempty"`

	// Status Status code of the problem.
	Status int `json:"status,omitempty"`

	// Title Summary of the problem.
	Title string `json:"title,omitempty"`

	// Type Identification of the problem.
	Type string `json:"type,omitempty"`
}
