openapi: 3.0.0

info:
  description: |
    OpenAPI specification for maintaining policies.
  version: 1.2.0
  title: Policy management
  contact:
    name: G. Juijn
    url: https://gitlab.com/digilab.overheid.nl/ecosystem/ftv/ftv-implementatie

servers:
  - url: https://localhost:8080/v1
    description: Local server.

tags:
  - name: policy
    description: Operations on policies.

paths:
  /policies:
    get:
      operationId: "get-policies"
      summary: Retrieve policies.
      description: Endpoint to retrieve all policy keys.
      tags:
        - policy
      responses:
        "200":
          description: Policies found.
          headers:
            API-Version:
              schema:
                type: string
              description: Full version number of the API.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PoliciesResponse"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/NotAuthorized"
        "403":
          $ref: "#/components/responses/AccessDenied"
        "404":
          $ref: "#/components/responses/NotFound"
        "5XX":
          $ref: "#/components/responses/UnexpectedError"

  /policy/{language}/{id}:
    parameters:
      - $ref: "#/components/parameters/PolicyLanguage"
      - $ref: "#/components/parameters/PolicyID"

    get:
      operationId: "get-policy"
      summary: Retrieve policy.
      description: Retrieve a specified cached policy.
      tags:
        - policy
      responses:
        "200":
          description: Policy found.
          headers:
            API-Version:
              schema:
                type: string
              description: Full version number of the API.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PolicyResponse"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/NotAuthorized"
        "403":
          $ref: "#/components/responses/AccessDenied"
        "404":
          $ref: "#/components/responses/NotFound"
        "5XX":
          $ref: "#/components/responses/UnexpectedError"

    put:
      operationId: "add-policy"
      summary: Add policy.
      description: |
        If the unique identifier of the policy already exists, a 409 status code will be returned.        
        You can override this behavior by passing the 'force' parameter in the query.
      tags:
        - policy
      parameters:
        - $ref: "#/components/parameters/ForceUpsert"
      requestBody:
        description: Definition of the new policy.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Policy"
      responses:
        "201":
          description: Policy created.
          headers:
            API-Version:
              schema:
                type: string
              description: Full version number of the API.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PolicyResponse"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/NotAuthorized"
        "403":
          $ref: "#/components/responses/AccessDenied"
        "409":
          $ref: "#/components/responses/AlreadyExists"
        "5XX":
          $ref: "#/components/responses/UnexpectedError"

    post:
      operationId: "replace-policy"
      summary: Replace policy.
      description: |
        If the unique identifier of the policy does not exist, a 404 status code will be returned.
        You can override this behavior by passing the 'force' parameter in the query.
      tags:
        - policy
      parameters:
        - $ref: "#/components/parameters/ForceUpsert"
      requestBody:
        description: Definition of the new policy.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Policy"
      responses:
        "200":
          description: Policy replaced.
          headers:
            API-Version:
              schema:
                type: string
              description: Full version number of the API.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PolicyResponse"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/NotAuthorized"
        "403":
          $ref: "#/components/responses/AccessDenied"
        "404":
          $ref: "#/components/responses/NotFound"
        "5XX":
          $ref: "#/components/responses/UnexpectedError"

    delete:
      operationId: "delete-policy"
      summary: Remove policy.
      description: |
        If the unique identifier of the policy does not exist, a 404 status code will be returned.
        You can override this behavior by passing the 'force' parameter in the query.
      tags:
        - policy
      parameters:
        - $ref: "#/components/parameters/IgnoreMissing"
      responses:
        "200":
          description: Policy removed.
          headers:
            API-Version:
              schema:
                type: string
              description: Full version number of the API.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PolicyResponse"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/NotAuthorized"
        "403":
          $ref: "#/components/responses/AccessDenied"
        "404":
          $ref: "#/components/responses/NotFound"
        "5XX":
          $ref: "#/components/responses/UnexpectedError"

components:
  parameters:
    PolicyLanguage:
      in: path
      name: language
      schema:
        type: string
      required: true
      description: Language of a policy.

    PolicyID:
      in: path
      name: id
      schema:
        type: string
      required: true
      description: Unique identifier of a policy.

    ForceUpsert:
      in: query
      name: force
      schema:
        type: boolean
      required: false
      description: Force upsert during a put/post operation.

    IgnoreMissing:
      in: query
      name: force
      schema:
        type: boolean
      required: false
      description: Ignore missing data during a delete operation.

  responses:
    BadRequest:
      description: Bad request.
      headers:
        API-Version:
          schema:
            type: string
          description: Full version number of the API.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"

    NotAuthorized:
      description: Not authorized.
      headers:
        API-Version:
          schema:
            type: string
          description: Full version number of the API.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"

    AccessDenied:
      description: Access denied.
      headers:
        API-Version:
          schema:
            type: string
          description: Full version number of the API.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"

    NotFound:
      description: Resource not found.
      headers:
        API-Version:
          schema:
            type: string
          description: Full version number of the API.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"

    AlreadyExists:
      description: Resource already exists.
      headers:
        API-Version:
          schema:
            type: string
          description: Full version number of the API.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"

    UnexpectedError:
      description: Unexpected error.
      headers:
        API-Version:
          schema:
            type: string
          description: Full version number of the API.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"

  schemas:
    Policy:
      type: object
      description: The content of a policy.
      properties:
        id:
          type: string
          description: The unique identifier of the policy.
        language:
          type: string
          description: The language of the policy.
          example: "rego"
        rvvaId:
          type: string
          description: The unique identifier of the Register van Verwerkings-Activiteiten (RvVA).
        url:
          type: string
          description: Link to the actual policy.
      required:
        - id
        - language
        - url

    PoliciesResponse:
      type: array
      items:
        $ref: "#/components/schemas/Policy"

    PolicyResponse:
      $ref: "#/components/schemas/Policy"

    ErrorResponse:
      type: object
      description: The response for an error (as defined by RFC9457).
      properties:
        type:
          type: string
          format: uri
          description: Identification of the problem.
        status:
          type: integer
          description: Status code of the problem.
        title:
          type: string
          description: Summary of the problem.
        detail:
          type: string
          description: Detailed description of the problem.
        instance:
          type: string
          format: uri
          description: Identification of the problem instance.
