openapi: 3.0.0

info:
  description: |
    OpenAPI specification for maintaining policies.
  version: 1.4.0
  title: Policy management
  contact:
    name: G. Juijn
    url: https://gitlab.com/digilab.overheid.nl/ecosystem/ftv/open-ftv

servers:
  - url: https://localhost:8080/v1
    description: Local server.

tags:
  - name: language
    description: Operations on policy languages.
  - name: tag
    description: Operations on tags.
  - name: policy
    description: Operations on policies.

paths:
  /languages:
    get:
      operationId: "get-languages"
      summary: Retrieve languages.
      description: Endpoint to retrieve the list of supported policy languages.
      tags:
        - language
      responses:
        "200":
          $ref: "#/components/responses/LanguagesFound"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/NotAuthorized"
        "403":
          $ref: "#/components/responses/AccessDenied"
        "5XX":
          $ref: "#/components/responses/UnexpectedError"

  /tags:
    get:
      operationId: "get-tags"
      summary: Retrieve tags.
      description: Endpoint to retrieve the list of tags.
      tags:
        - tag
      responses:
        "200":
          $ref: "#/components/responses/TagsFound"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/NotAuthorized"
        "403":
          $ref: "#/components/responses/AccessDenied"
        "5XX":
          $ref: "#/components/responses/UnexpectedError"

  /policies:
    get:
      operationId: "get-policies"
      summary: Retrieve policies.
      description: Endpoint to retrieve all policy keys.
      tags:
        - policy
      responses:
        "200":
          $ref: "#/components/responses/PoliciesFound"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/NotAuthorized"
        "403":
          $ref: "#/components/responses/AccessDenied"
        "5XX":
          $ref: "#/components/responses/UnexpectedError"

  /policy/{language}/{id}:
    parameters:
      - $ref: "#/components/parameters/PolicyLanguage"
      - $ref: "#/components/parameters/PolicyID"

    get:
      operationId: "get-policy"
      summary: Retrieve policy.
      description: Retrieve a specified cached policy.
      tags:
        - policy
      responses:
        "200":
          $ref: "#/components/responses/PolicyFound"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/NotAuthorized"
        "403":
          $ref: "#/components/responses/AccessDenied"
        "404":
          $ref: "#/components/responses/NotFound"
        "5XX":
          $ref: "#/components/responses/UnexpectedError"

    post:
      operationId: "create-policy"
      summary: Add policy.
      description: |
        If the unique identifier of the policy already exists, a 409 status code will be returned.        
        You can override this behavior by passing the 'force' parameter in the query.
      tags:
        - policy
      parameters:
        - $ref: "#/components/parameters/ForceUpsert"
      requestBody:
        description: Definition of the new policy.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Policy"
      responses:
        "201":
          $ref: "#/components/responses/PolicyCreated"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/NotAuthorized"
        "403":
          $ref: "#/components/responses/AccessDenied"
        "409":
          $ref: "#/components/responses/AlreadyExists"
        "5XX":
          $ref: "#/components/responses/UnexpectedError"

    put:
      operationId: "update-policy"
      summary: Replace policy.
      description: |
        If the unique identifier of the policy does not exist, a 404 status code will be returned.
        You can override this behavior by passing the 'force' parameter in the query.
      tags:
        - policy
      parameters:
        - $ref: "#/components/parameters/ForceUpsert"
      requestBody:
        description: Definition of the new policy.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Policy"
      responses:
        "200":
          $ref: "#/components/responses/PolicyReplaced"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/NotAuthorized"
        "403":
          $ref: "#/components/responses/AccessDenied"
        "404":
          $ref: "#/components/responses/NotFound"
        "5XX":
          $ref: "#/components/responses/UnexpectedError"

    delete:
      operationId: "delete-policy"
      summary: Remove policy.
      description: |
        If the unique identifier of the policy does not exist, a 404 status code will be returned.
        You can override this behavior by passing the 'force' parameter in the query.
      tags:
        - policy
      parameters:
        - $ref: "#/components/parameters/IgnoreMissing"
      responses:
        "200":
          $ref: "#/components/responses/PolicyRemoved"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/NotAuthorized"
        "403":
          $ref: "#/components/responses/AccessDenied"
        "404":
          $ref: "#/components/responses/NotFound"
        "5XX":
          $ref: "#/components/responses/UnexpectedError"

components:
  parameters:
    PolicyLanguage:
      in: path
      name: language
      schema:
        type: string
      required: true
      description: Language of a policy.

    PolicyID:
      in: path
      name: id
      schema:
        type: string
      required: true
      description: Unique identifier of a policy.

    ForceUpsert:
      in: query
      name: force
      schema:
        type: boolean
      required: false
      description: Force upsert during a put/post operation.

    IgnoreMissing:
      in: query
      name: force
      schema:
        type: boolean
      required: false
      description: Ignore missing data during a delete operation.

  responses:
    LanguagesFound:
      description: Languages found.
      headers:
        API-Version:
          schema:
            type: string
          description: Full version number of the API.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Languages"

    TagsFound:
      description: Tags found.
      headers:
        API-Version:
          schema:
            type: string
          description: Full version number of the API.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Tags"

    PoliciesFound:
      description: Policies found.
      headers:
        API-Version:
          schema:
            type: string
          description: Full version number of the API.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Policies"

    PolicyFound:
      description: Policy found.
      headers:
        API-Version:
          schema:
            type: string
          description: Full version number of the API.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Policy"

    PolicyCreated:
      description: Policy created.
      headers:
        API-Version:
          schema:
            type: string
          description: Full version number of the API.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Policy"

    PolicyReplaced:
      description: Policy replaced.
      headers:
        API-Version:
          schema:
            type: string
          description: Full version number of the API.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Policy"

    PolicyRemoved:
      description: Policy removed.
      headers:
        API-Version:
          schema:
            type: string
          description: Full version number of the API.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Policy"

    BadRequest:
      description: Bad request.
      headers:
        API-Version:
          schema:
            type: string
          description: Full version number of the API.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorMessage"

    NotAuthorized:
      description: Not authorized.
      headers:
        API-Version:
          schema:
            type: string
          description: Full version number of the API.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorMessage"

    AccessDenied:
      description: Access denied.
      headers:
        API-Version:
          schema:
            type: string
          description: Full version number of the API.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorMessage"

    NotFound:
      description: Resource not found.
      headers:
        API-Version:
          schema:
            type: string
          description: Full version number of the API.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorMessage"

    AlreadyExists:
      description: Resource already exists.
      headers:
        API-Version:
          schema:
            type: string
          description: Full version number of the API.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorMessage"

    UnexpectedError:
      description: Unexpected error.
      headers:
        API-Version:
          schema:
            type: string
          description: Full version number of the API.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorMessage"

  schemas:
    Languages:
      type: array
      items:
        $ref: "#/components/schemas/Language"

    Language:
      type: object
      description: The details of a policy language.
      properties:
        id:
          type: string
          description: The unique identifier of the policy language.
        name:
          type: string
          description: Name of the policy language in human-readable form.

    Tags:
      type: array
      items:
        $ref: "#/components/schemas/Tag"

    Tag:
      type: object
      description: The details of a tag.
      properties:
        id:
          type: string
          description: The unique identifier of the tag.
        name:
          type: string
          description: Name of the tag in human-readable form.

    Policies:
      type: array
      items:
        $ref: "#/components/schemas/Policy"

    Policy:
      type: object
      description: The content of a policy.
      properties:
        id:
          type: string
          description: The unique identifier of the policy.
        language:
          type: string
          description: |
            The language of the policy.
            The value is case-insensitive.
            The value is considered as one of the tags of the policy.
            
            Supported values:
            - "opa/rego"; alternatives: "opa", "rego", "opa-rego".
            - "cedar".
            - "cerbos/cel"; alternatives: "cerbos", "cel", "cerbos-cel". 
            - "openfga"; alternative: "open-fga".
        version:
          type: integer
          description: |
            The most recent version number of the policy.
            This is a read-only field.
            It is automatically updated during the deploy process.
        description:
          type: string
          description: Description and/or comments for the policy.
        rvvaId:
          type: string
          description: |
            The unique identifier of the Register van Verwerkings-Activiteiten (RvVA).
            Only required when the policy is linked directly with an item in the RvVA.
            The value is considered as one of the tags of the policy.
        additionalTags:
          type: array
          description: |
            List of additional tags associated with the policy.
            This is used to determine which PDP (or set of PDPs) policies can be pushed to.
            Note that the language and rvvaId fields are also tags.
          items:
            type: string
        url:
          type: string
          description: Link to the policy. Required when the policy is stored externally.
        data:
          type: string
          description: Content of the policy. Required when the policy is stored internally.
      required:
        - id
        - language

    ErrorMessage:
      type: object
      description: The response for an error (as defined by RFC9457).
      properties:
        type:
          type: string
          format: uri
          description: Identification of the problem.
        status:
          type: integer
          description: Status code of the problem.
        title:
          type: string
          description: Summary of the problem.
        detail:
          type: string
          description: Detailed description of the problem.
        instance:
          type: string
          format: uri
          description: Identification of the problem instance.
