// Package policies provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package policies

// ErrorMessage The response for an error (as defined by RFC9457).
type ErrorMessage struct {
	// Detail Detailed description of the problem.
	Detail string `json:"detail,omitempty"`

	// Instance Identification of the problem instance.
	Instance string `json:"instance,omitempty"`

	// Status Status code of the problem.
	Status int `json:"status,omitempty"`

	// Title Summary of the problem.
	Title string `json:"title,omitempty"`

	// Type Identification of the problem.
	Type string `json:"type,omitempty"`
}

// Language The details of a policy language.
type Language struct {
	// Id The unique identifier of the policy language.
	Id string `json:"id,omitempty"`

	// Name Name of the policy language in human-readable form.
	Name string `json:"name,omitempty"`
}

// Languages defines model for Languages.
type Languages = []Language

// Policies defines model for Policies.
type Policies = []Policy

// Policy The content of a policy.
type Policy struct {
	// AdditionalTags List of additional tags associated with the policy.
	// This is used to determine which PDP (or set of PDPs) policies can be pushed to.
	// Note that the language and rvvaId fields are also tags.
	AdditionalTags []string `json:"additionalTags,omitempty"`

	// Data Content of the policy. Required when the policy is stored internally.
	Data string `json:"data,omitempty"`

	// Description Description and/or comments for the policy.
	Description string `json:"description,omitempty"`

	// Id The unique identifier of the policy.
	Id string `json:"id"`

	// Language The language of the policy.
	// The value is case-insensitive.
	// The value is considered as one of the tags of the policy.
	//
	// Supported values:
	// - "opa/rego"; alternatives: "opa", "rego", "opa-rego".
	// - "cedar".
	// - "cerbos/cel"; alternatives: "cerbos", "cel", "cerbos-cel".
	// - "openfga"; alternative: "open-fga".
	Language string `json:"language"`

	// RvvaId The unique identifier of the Register van Verwerkings-Activiteiten (RvVA).
	// Only required when the policy is linked directly with an item in the RvVA.
	// The value is considered as one of the tags of the policy.
	RvvaId string `json:"rvvaId,omitempty"`

	// Url Link to the policy. Required when the policy is stored externally.
	Url string `json:"url,omitempty"`

	// Version The most recent version number of the policy.
	// This is a read-only field.
	// It is automatically updated during the deploy process.
	Version int `json:"version,omitempty"`
}

// Tag The details of a tag.
type Tag struct {
	// Id The unique identifier of the tag.
	Id string `json:"id,omitempty"`

	// Name Name of the tag in human-readable form.
	Name string `json:"name,omitempty"`
}

// Tags defines model for Tags.
type Tags = []Tag

// ForceUpsert defines model for ForceUpsert.
type ForceUpsert = bool

// IgnoreMissing defines model for IgnoreMissing.
type IgnoreMissing = bool

// PolicyID defines model for PolicyID.
type PolicyID = string

// PolicyLanguage defines model for PolicyLanguage.
type PolicyLanguage = string

// AccessDenied The response for an error (as defined by RFC9457).
type AccessDenied = ErrorMessage

// AlreadyExists The response for an error (as defined by RFC9457).
type AlreadyExists = ErrorMessage

// BadRequest The response for an error (as defined by RFC9457).
type BadRequest = ErrorMessage

// LanguagesFound defines model for LanguagesFound.
type LanguagesFound = Languages

// NotAuthorized The response for an error (as defined by RFC9457).
type NotAuthorized = ErrorMessage

// NotFound The response for an error (as defined by RFC9457).
type NotFound = ErrorMessage

// PoliciesFound defines model for PoliciesFound.
type PoliciesFound = Policies

// PolicyCreated The content of a policy.
type PolicyCreated = Policy

// PolicyFound The content of a policy.
type PolicyFound = Policy

// PolicyRemoved The content of a policy.
type PolicyRemoved = Policy

// PolicyReplaced The content of a policy.
type PolicyReplaced = Policy

// TagsFound defines model for TagsFound.
type TagsFound = Tags

// UnexpectedError The response for an error (as defined by RFC9457).
type UnexpectedError = ErrorMessage

// DeletePolicyParams defines parameters for DeletePolicy.
type DeletePolicyParams struct {
	// Force Ignore missing data during a delete operation.
	Force IgnoreMissing `form:"force,omitempty" json:"force,omitempty"`
}

// CreatePolicyParams defines parameters for CreatePolicy.
type CreatePolicyParams struct {
	// Force Force upsert during a put/post operation.
	Force ForceUpsert `form:"force,omitempty" json:"force,omitempty"`
}

// UpdatePolicyParams defines parameters for UpdatePolicy.
type UpdatePolicyParams struct {
	// Force Force upsert during a put/post operation.
	Force ForceUpsert `form:"force,omitempty" json:"force,omitempty"`
}

// CreatePolicyJSONRequestBody defines body for CreatePolicy for application/json ContentType.
type CreatePolicyJSONRequestBody = Policy

// UpdatePolicyJSONRequestBody defines body for UpdatePolicy for application/json ContentType.
type UpdatePolicyJSONRequestBody = Policy
