// Package policies provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package policies

import (
	apierrors "gitlab.com/digilab.overheid.nl/ecosystem/ftv/open-ftv/oas/errors"
)

// Defines values for PrincipalKind.
const (
	Legacy PrincipalKind = "legacy"
	System PrincipalKind = "system"
	User   PrincipalKind = "user"
)

// Valid indicates whether the value is a known member of the PrincipalKind enum.
func (e PrincipalKind) Valid() bool {
	switch e {
	case Legacy:
		return true
	case System:
		return true
	case User:
		return true
	default:
		return false
	}
}

// AuditEntry Metadata about how, when and by whom an object has been manipulated.
type AuditEntry struct {
	// Created Timestamp of the log entry in RFC3339 format.
	Created string `json:"created"`

	// Operation Operation performed on the object. Any of ["C", "U", "D"].
	Operation string `json:"operation"`

	// User Who performed an action. `id` is the stored attribution value and is always present;
	// `name` is filled in from the manager's local principal record and is absent when that
	// record is unknown, in which case clients show the raw `id`. Only a principal of kind
	// `user` identifies a real subject and may be linked to.
	User Principal `json:"user"`
}

// Error Error response model (as defined by RFC9457).
type Error = apierrors.ErrorResponse

// Language The details of a policy language.
type Language struct {
	// Audit The audit details of an object.
	Audit ObjectAudit `json:"audit"`

	// AuditLog Audit log for the policy language.
	AuditLog []AuditEntry `json:"auditLog,omitempty"`

	// Description Detailed description of the policy language.
	Description string `json:"description,omitempty"`

	// Id The unique identifier of the policy language.
	Id string `json:"id"`

	// Name Name of the policy language in human-readable form.
	Name string `json:"name"`
}

// Languages defines model for Languages.
type Languages = []Language

// Metadata The metadata associated with a policy.
type Metadata struct {
	// Description Detailed description of the policy.
	Description string `json:"description,omitempty"`

	// RvvaId The unique identifier of the Register van Verwerkings-Activiteiten (RvVA).
	// Only required when the policy is linked directly with an item in the RvVA.
	// The value is considered as one of the tags of the policy.
	RvvaId string `json:"rvvaId,omitempty"`

	// Tags List of tags the policy is annotated with.
	//
	// This is used to determine which PDP (or set of PDPs) objects can be pushed to.
	//
	// Verify with the tags endpoint.
	Tags []string `json:"tags,omitempty"`

	// Title The title of the policy. E.g., a short description.
	Title string `json:"title"`

	// Url Link to the policy. Required when the policy is stored externally.
	Url string `json:"url,omitempty"`
}

// ObjectAudit The audit details of an object.
type ObjectAudit struct {
	// Created Timestamp the object was created (RFC3339 format).
	Created string `json:"created"`

	// CreatedBy Who performed an action. `id` is the stored attribution value and is always present;
	// `name` is filled in from the manager's local principal record and is absent when that
	// record is unknown, in which case clients show the raw `id`. Only a principal of kind
	// `user` identifies a real subject and may be linked to.
	CreatedBy Principal `json:"createdBy"`

	// Updated Timestamp the object was last updated (RFC3339 format).
	Updated   string     `json:"updated,omitempty"`
	UpdatedBy *Principal `json:"updatedBy,omitempty"`
}

// Policies defines model for Policies.
type Policies = []Policy

// Policy The content of a policy.
type Policy struct {
	// Audit The audit details of an object.
	Audit ObjectAudit `json:"audit"`

	// AuditLog Audit log for the policy.
	AuditLog []AuditEntry `json:"auditLog,omitempty"`

	// Data Content of the policy. Required when the policy is stored internally.
	Data string `json:"data,omitempty"`

	// Id The unique identifier of the policy (UUID).
	Id string `json:"id"`

	// Language The language of the policy.
	// The value is case-insensitive.
	// The value is considered as one of the tags of the policy.
	//
	// Supported values:
	// - "opa/rego"; alternatives: "opa", "rego", "opa-rego".
	// - "cedar".
	// - "cerbos/cel"; alternatives: "cerbos", "cel", "cerbos-cel".
	// - "openfga"; alternative: "open-fga".
	//
	// Verify with the languages endpoint.
	Language string `json:"language"`

	// Metadata The metadata associated with a policy.
	Metadata Metadata `json:"metadata"`

	// Status The current status of the policy ('concept', 'accepted', 'deployed').
	Status string `json:"status"`

	// UsageData Usage data for the policy.
	UsageData []UsageData `json:"usageData,omitempty"`

	// Versions Previous version numbers of the policy.
	Versions []int `json:"versions,omitempty"`
}

// PolicyStatus The status of a policy.
type PolicyStatus struct {
	// Id The unique identifier of the policy (UUID).
	Id string `json:"id"`

	// Status The current status of the policy ('concept', 'accepted', 'deployed').
	Status string `json:"status"`
}

// PolicyVersion The content of a specific version of a policy.
type PolicyVersion struct {
	// Data Content of the policy. Required when the policy is stored internally.
	Data string `json:"data,omitempty"`

	// Id The unique identifier of the policy (UUID).
	Id string `json:"id"`

	// Language The language of the policy.
	// The value is case-insensitive.
	// The value is considered as one of the tags of the policy.
	//
	// Supported values:
	// - "opa/rego"; alternatives: "opa", "rego", "opa-rego".
	// - "cedar".
	// - "cerbos/cel"; alternatives: "cerbos", "cel", "cerbos-cel".
	// - "openfga"; alternative: "open-fga".
	//
	// Verify with the languages endpoint.
	Language string `json:"language"`

	// Metadata The metadata associated with a policy.
	Metadata Metadata `json:"metadata"`

	// Version The version number of the policy.
	Version int `json:"version"`
}

// PolicyVersions defines model for PolicyVersions.
type PolicyVersions = []PolicyVersion

// Principal Who performed an action. `id` is the stored attribution value and is always present;
// `name` is filled in from the manager's local principal record and is absent when that
// record is unknown, in which case clients show the raw `id`. Only a principal of kind
// `user` identifies a real subject and may be linked to.
type Principal struct {
	// Id Stable identifier of the principal, as stored on the object.
	Id string `json:"id"`

	// Kind `user` for an authenticated subject, `system` for the manager's own actions, and
	// `legacy` for an attribution value predating the principal record, which is shown
	// but identifies nobody.
	Kind PrincipalKind `json:"kind,omitempty"`

	// Name Display name of the principal, when known.
	Name string `json:"name,omitempty"`
}

// PrincipalKind `user` for an authenticated subject, `system` for the manager's own actions, and
// `legacy` for an attribution value predating the principal record, which is shown
// but identifies nobody.
type PrincipalKind string

// Tag The details of a tag.
type Tag struct {
	// Audit The audit details of an object.
	Audit ObjectAudit `json:"audit"`

	// AuditLog Audit log for the tag.
	AuditLog []AuditEntry `json:"auditLog,omitempty"`

	// Description Detailed description of the tag.
	Description string `json:"description,omitempty"`

	// Id The unique identifier of the tag.
	Id string `json:"id"`

	// Name Name of the tag in human-readable form.
	Name string `json:"name"`
}

// Tags defines model for Tags.
type Tags = []Tag

// UsageData Metadata about when and where the object is used.
type UsageData struct {
	// Bundle Code of the bundle the object was included in.
	Bundle string `json:"bundle,omitempty"`

	// Created Timestamp the deployment was created (RFC3339 format).
	Created   string     `json:"created,omitempty"`
	CreatedBy *Principal `json:"createdBy,omitempty"`

	// Status Status of the deployment.
	Status string `json:"status,omitempty"`

	// Version Version number of the deployment.
	Version int `json:"version,omitempty"`
}

// ForceUpsert defines model for ForceUpsert.
type ForceUpsert = bool

// IgnoreMissing defines model for IgnoreMissing.
type IgnoreMissing = bool

// PolicyID defines model for PolicyID.
type PolicyID = string

// Version defines model for Version.
type Version = int

// AccessDenied Error response model (as defined by RFC9457).
type AccessDenied = Error

// AlreadyExists Error response model (as defined by RFC9457).
type AlreadyExists = Error

// BadRequest Error response model (as defined by RFC9457).
type BadRequest = Error

// LanguagesResponse defines model for LanguagesResponse.
type LanguagesResponse = Languages

// NotAuthorized Error response model (as defined by RFC9457).
type NotAuthorized = Error

// NotFound Error response model (as defined by RFC9457).
type NotFound = Error

// PoliciesResponse defines model for PoliciesResponse.
type PoliciesResponse = Policies

// PolicyResponse The content of a policy.
type PolicyResponse = Policy

// TagsResponse defines model for TagsResponse.
type TagsResponse = Tags

// UnexpectedError Error response model (as defined by RFC9457).
type UnexpectedError = Error

// VersionResponse The content of a specific version of a policy.
type VersionResponse = PolicyVersion

// VersionsResponse defines model for VersionsResponse.
type VersionsResponse = PolicyVersions

// DeletePolicyParams defines parameters for DeletePolicy.
type DeletePolicyParams struct {
	// Force Ignore missing data during a delete operation.
	Force IgnoreMissing `form:"force,omitempty" json:"force,omitempty"`
}

// CreatePolicyParams defines parameters for CreatePolicy.
type CreatePolicyParams struct {
	// Force Force upsert during a put/post operation.
	Force ForceUpsert `form:"force,omitempty" json:"force,omitempty"`
}

// UpdatePolicyParams defines parameters for UpdatePolicy.
type UpdatePolicyParams struct {
	// Force Force upsert during a put/post operation.
	Force ForceUpsert `form:"force,omitempty" json:"force,omitempty"`
}

// CreatePolicyJSONRequestBody defines body for CreatePolicy for application/json ContentType.
type CreatePolicyJSONRequestBody = Policy

// UpdatePolicyJSONRequestBody defines body for UpdatePolicy for application/json ContentType.
type UpdatePolicyJSONRequestBody = Policy

// StatusPolicyJSONRequestBody defines body for StatusPolicy for application/json ContentType.
type StatusPolicyJSONRequestBody = PolicyStatus
