// Package policies provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package policies

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Data Optional extra context of the error.
	Data *map[string]interface{} `json:"data,omitempty"`

	// Message An optional message detailing the error.
	Message *string `json:"message,omitempty"`
}

// PoliciesResponse defines model for PoliciesResponse.
type PoliciesResponse = []Policy

// Policy The content of a policy.
type Policy struct {
	// Id The unique identifier of the policy.
	Id string `json:"id"`

	// Language The language of the policy.
	Language string `json:"language"`

	// Rvvaid The unique identifier of the Activity Register.
	Rvvaid *string `json:"rvvaid,omitempty"`

	// Source The unique identifier of the source peer (OIN).
	Source *string `json:"source,omitempty"`

	// Target The unique identifier of the target peer (OIN).
	Target *string `json:"target,omitempty"`

	// Url Link to the actual policy.
	Url string `json:"url"`
}
