/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/attributes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve attributes.
         * @description Endpoint to retrieve all attributes.
         */
        get: operations["get-attributes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attribute/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique key of an attribute. */
                key: components["parameters"]["AttributeKey"];
            };
            cookie?: never;
        };
        /**
         * Retrieve attribute.
         * @description Retrieve a specified cached attribute.
         */
        get: operations["get-attribute"];
        /**
         * Replace attribute.
         * @description If the unique key of the attribute does not exist, a 404 response status code will be returned.
         *     You can override this behavior by passing the 'force' parameter in the query.
         *
         */
        put: operations["replace-attribute"];
        /**
         * Add attribute.
         * @description If the unique key of the attribute already exists, a 409 response status code will be returned.
         *     You can override this behavior by passing the 'force' parameter in the query.
         *
         */
        post: operations["add-attribute"];
        /**
         * Remove attribute.
         * @description If the unique key of the attribute does not exist, a 404 response status code will be returned.
         *     You can override this behavior by passing the 'force' parameter in the query.
         *
         */
        delete: operations["remove-attribute"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve entities.
         * @description Endpoint to retrieve all entities.
         */
        get: operations["get-entities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entity/{type}/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Type of entity. */
                type: components["parameters"]["EntityType"];
                /** @description ID of an entity. */
                id: components["parameters"]["EntityID"];
            };
            cookie?: never;
        };
        /**
         * Retrieve entity.
         * @description Retrieve a specified cached entity.
         */
        get: operations["get-entity"];
        /**
         * Replace entity.
         * @description If the unique type+id of the entity does not exist, a 404 response status code will be returned.
         *     You can override this behavior by passing the 'force' parameter in the query.
         *
         */
        put: operations["remove-entity"];
        /**
         * Add entity.
         * @description If the unique type+id of the entity already exists, a 409 response status code will be returned.
         *     You can override this behavior by passing the 'force' parameter in the query.
         *
         */
        post: operations["add-entity"];
        /**
         * Remove entity.
         * @description If the unique type+id of the entity does not exist, a 404 response status code will be returned.
         *     You can override this behavior by passing the 'force' parameter in the query.
         *
         */
        delete: operations["delete-entity"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/relations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve relations.
         * @description Endpoint to retrieve all relations.
         */
        get: operations["get-relations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/relation/{subjectType}/{subjectID}/{relation}/{objectType}/{objectID}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Type of subject of a relation. */
                subjectType: components["parameters"]["SubjectType"];
                /** @description ID of the subject of a relation. */
                subjectID: components["parameters"]["SubjectID"];
                /** @description Type of relation. */
                relation: components["parameters"]["RelationType"];
                /** @description Type of object of a relation. */
                objectType: components["parameters"]["ObjectType"];
                /** @description ID of the object of a relation. */
                objectID: components["parameters"]["ObjectID"];
            };
            cookie?: never;
        };
        /**
         * Retrieve relation.
         * @description Retrieve a specified cached relation.
         */
        get: operations["get-relation"];
        /**
         * Replace relation.
         * @description If the unique subject+relation+object of the relation does not exist, a 404 response status code will be returned.
         *     You can override this behavior by passing the 'force' parameter in the query.
         *
         */
        put: operations["replace-relation"];
        /**
         * Add relation.
         * @description If the unique subject+relation+object of the relation already exists, a 409 response status code will be returned.
         *     You can override this behavior by passing the 'force' parameter in the query.
         *
         */
        post: operations["add-relation"];
        /**
         * Remove relation.
         * @description If the unique subject+relation+object of the relation does not exist, a 404 response status code will be returned.
         *     You can override this behavior by passing the 'force' parameter in the query.
         *
         */
        delete: operations["remove-relation"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description The content of an attribute (key/value pair). */
        Attribute: {
            /** @description The unique key of the attribute. */
            key: string;
            /** @description The value of the attribute. */
            value: unknown;
            /** @description The optional type of a value. By default a value is stored as-is.
             *
             *     The following codes for type are supported:
             *     "*string*", "*integer*", "*float*", "*boolean*", "*date*", "*time*", "*timestamp*".
             *     Optionally, the type can be specified as one of the standard XSD types (e.g. "*xsd:byte*").
             *
             *     An *integer* value is stored as a 64-bit signed integer.
             *
             *     A *float* value is stored with double precision.
             *
             *     A *boolean* value can be *true* (case-insensitive) or *1* to represent a true state,
             *     or any other value to represent a false state.
             *
             *     A *date*, *time* or *timestamp* value should adhere to the format as described in ISO-8601.
             *     If it cannot be decoded according to ISO-8601, a 400 response status code will be returned.
             *      */
            type?: string;
        };
        /** @description The content of an entity.
         *
         *     The combination of *type* and *id* defines the unique key of an entity.
         *      */
        Entity: {
            /**
             * @description The type of entity.
             * @example user
             */
            type: string;
            /**
             * @description The identification of the entity.
             * @example alice
             */
            id: string;
            /** @description Optional attributes of the entity. */
            attributes?: components["schemas"]["Attribute"][];
        };
        /** @description The content of a relation.
         *
         *     The combination of *subject type/id*, *relation* and *object type/id* defines the unique key of a relation.
         *      */
        Relation: {
            /**
             * @description The type of subject of the relation.
             * @example user
             */
            subjectType: string;
            /**
             * @description The identifier of the subject of the relation.
             * @example alice
             */
            subjectId: string;
            /**
             * @description The type of relation.
             * @example managerOf
             */
            relation: string;
            /**
             * @description The type of object of the relation.
             * @example user
             */
            objectType: string;
            /**
             * @description The identifier of the object of the relation.
             * @example bob
             */
            objectId: string;
            /** @description Optional attributes of the relation. */
            attributes?: components["schemas"]["Attribute"][];
        };
        AttributesResponse: components["schemas"]["Attribute"][];
        AttributeResponse: components["schemas"]["Attribute"];
        EntitiesResponse: components["schemas"]["Entity"][];
        EntityResponse: components["schemas"]["Entity"];
        RelationsResponse: components["schemas"]["Relation"][];
        RelationResponse: components["schemas"]["Relation"];
        /** @description The response for an error (as defined by RFC9457). */
        ErrorResponse: {
            /**
             * Format: uri
             * @description Identification of the problem.
             */
            type?: string;
            /** @description Status code of the problem. */
            status?: number;
            /** @description Summary of the problem. */
            title?: string;
            /** @description Detailed description of the problem. */
            detail?: string;
            /**
             * Format: uri
             * @description Identification of the problem instance.
             */
            instance?: string;
        };
    };
    responses: {
        /** @description Bad request. */
        BadRequest: {
            headers: {
                /** @description Full version number of the API. */
                "API-Version"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Not authorized. */
        NotAuthorized: {
            headers: {
                /** @description Full version number of the API. */
                "API-Version"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Access denied. */
        AccessDenied: {
            headers: {
                /** @description Full version number of the API. */
                "API-Version"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource not found. */
        NotFound: {
            headers: {
                /** @description Full version number of the API. */
                "API-Version"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource already exists. */
        AlreadyExists: {
            headers: {
                /** @description Full version number of the API. */
                "API-Version"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Unexpected error. */
        UnexpectedError: {
            headers: {
                /** @description Full version number of the API. */
                "API-Version"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /** @description Unique key of an attribute. */
        AttributeKey: string;
        /** @description Type of entity. */
        EntityType: string;
        /** @description ID of an entity. */
        EntityID: string;
        /** @description Type of subject of a relation. */
        SubjectType: string;
        /** @description ID of the subject of a relation. */
        SubjectID: string;
        /** @description Type of relation. */
        RelationType: string;
        /** @description Type of object of a relation. */
        ObjectType: string;
        /** @description ID of the object of a relation. */
        ObjectID: string;
        /** @description Force upsert during a put/post operation. */
        ForceUpsert: boolean;
        /** @description Ignore missing data during a delete operation. */
        IgnoreMissing: boolean;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "get-attributes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Attributes found. */
            200: {
                headers: {
                    /** @description Full version number of the API. */
                    "API-Version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttributesResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["NotAuthorized"];
            403: components["responses"]["AccessDenied"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    "get-attribute": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique key of an attribute. */
                key: components["parameters"]["AttributeKey"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Attribute found. */
            200: {
                headers: {
                    /** @description Full version number of the API. */
                    "API-Version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttributeResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["NotAuthorized"];
            403: components["responses"]["AccessDenied"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    "replace-attribute": {
        parameters: {
            query?: {
                /** @description Force upsert during a put/post operation. */
                force?: components["parameters"]["ForceUpsert"];
            };
            header?: never;
            path: {
                /** @description Unique key of an attribute. */
                key: components["parameters"]["AttributeKey"];
            };
            cookie?: never;
        };
        /** @description Content of the new attribute. */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["Attribute"];
            };
        };
        responses: {
            /** @description Attribute replaced. */
            200: {
                headers: {
                    /** @description Full version number of the API. */
                    "API-Version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttributeResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["NotAuthorized"];
            403: components["responses"]["AccessDenied"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    "add-attribute": {
        parameters: {
            query?: {
                /** @description Force upsert during a put/post operation. */
                force?: components["parameters"]["ForceUpsert"];
            };
            header?: never;
            path: {
                /** @description Unique key of an attribute. */
                key: components["parameters"]["AttributeKey"];
            };
            cookie?: never;
        };
        /** @description Content of the new attribute. */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["Attribute"];
            };
        };
        responses: {
            /** @description Attribute created. */
            201: {
                headers: {
                    /** @description Full version number of the API. */
                    "API-Version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttributeResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["NotAuthorized"];
            403: components["responses"]["AccessDenied"];
            409: components["responses"]["AlreadyExists"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    "remove-attribute": {
        parameters: {
            query?: {
                /** @description Ignore missing data during a delete operation. */
                force?: components["parameters"]["IgnoreMissing"];
            };
            header?: never;
            path: {
                /** @description Unique key of an attribute. */
                key: components["parameters"]["AttributeKey"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Attribute removed. */
            200: {
                headers: {
                    /** @description Full version number of the API. */
                    "API-Version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttributeResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["NotAuthorized"];
            403: components["responses"]["AccessDenied"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    "get-entities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Entities found. */
            200: {
                headers: {
                    /** @description Full version number of the API. */
                    "API-Version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntitiesResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["NotAuthorized"];
            403: components["responses"]["AccessDenied"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    "get-entity": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Type of entity. */
                type: components["parameters"]["EntityType"];
                /** @description ID of an entity. */
                id: components["parameters"]["EntityID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Entity found. */
            200: {
                headers: {
                    /** @description Full version number of the API. */
                    "API-Version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["NotAuthorized"];
            403: components["responses"]["AccessDenied"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    "remove-entity": {
        parameters: {
            query?: {
                /** @description Force upsert during a put/post operation. */
                force?: components["parameters"]["ForceUpsert"];
            };
            header?: never;
            path: {
                /** @description Type of entity. */
                type: components["parameters"]["EntityType"];
                /** @description ID of an entity. */
                id: components["parameters"]["EntityID"];
            };
            cookie?: never;
        };
        /** @description Content of the new entity. */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["Entity"];
            };
        };
        responses: {
            /** @description Entity replaced. */
            200: {
                headers: {
                    /** @description Full version number of the API. */
                    "API-Version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["NotAuthorized"];
            403: components["responses"]["AccessDenied"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    "add-entity": {
        parameters: {
            query?: {
                /** @description Force upsert during a put/post operation. */
                force?: components["parameters"]["ForceUpsert"];
            };
            header?: never;
            path: {
                /** @description Type of entity. */
                type: components["parameters"]["EntityType"];
                /** @description ID of an entity. */
                id: components["parameters"]["EntityID"];
            };
            cookie?: never;
        };
        /** @description Content of the new entity. */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["Entity"];
            };
        };
        responses: {
            /** @description Entity created. */
            201: {
                headers: {
                    /** @description Full version number of the API. */
                    "API-Version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["NotAuthorized"];
            403: components["responses"]["AccessDenied"];
            409: components["responses"]["AlreadyExists"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    "delete-entity": {
        parameters: {
            query?: {
                /** @description Ignore missing data during a delete operation. */
                force?: components["parameters"]["IgnoreMissing"];
            };
            header?: never;
            path: {
                /** @description Type of entity. */
                type: components["parameters"]["EntityType"];
                /** @description ID of an entity. */
                id: components["parameters"]["EntityID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Entity removed. */
            200: {
                headers: {
                    /** @description Full version number of the API. */
                    "API-Version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["NotAuthorized"];
            403: components["responses"]["AccessDenied"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    "get-relations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Relations found. */
            200: {
                headers: {
                    /** @description Full version number of the API. */
                    "API-Version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelationsResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["NotAuthorized"];
            403: components["responses"]["AccessDenied"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    "get-relation": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Type of subject of a relation. */
                subjectType: components["parameters"]["SubjectType"];
                /** @description ID of the subject of a relation. */
                subjectID: components["parameters"]["SubjectID"];
                /** @description Type of relation. */
                relation: components["parameters"]["RelationType"];
                /** @description Type of object of a relation. */
                objectType: components["parameters"]["ObjectType"];
                /** @description ID of the object of a relation. */
                objectID: components["parameters"]["ObjectID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Relation found. */
            200: {
                headers: {
                    /** @description Full version number of the API. */
                    "API-Version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelationResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["NotAuthorized"];
            403: components["responses"]["AccessDenied"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    "replace-relation": {
        parameters: {
            query?: {
                /** @description Force upsert during a put/post operation. */
                force?: components["parameters"]["ForceUpsert"];
            };
            header?: never;
            path: {
                /** @description Type of subject of a relation. */
                subjectType: components["parameters"]["SubjectType"];
                /** @description ID of the subject of a relation. */
                subjectID: components["parameters"]["SubjectID"];
                /** @description Type of relation. */
                relation: components["parameters"]["RelationType"];
                /** @description Type of object of a relation. */
                objectType: components["parameters"]["ObjectType"];
                /** @description ID of the object of a relation. */
                objectID: components["parameters"]["ObjectID"];
            };
            cookie?: never;
        };
        /** @description Content of the new relation. */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["Relation"];
            };
        };
        responses: {
            /** @description Relation replaced. */
            200: {
                headers: {
                    /** @description Full version number of the API. */
                    "API-Version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelationResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["NotAuthorized"];
            403: components["responses"]["AccessDenied"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    "add-relation": {
        parameters: {
            query?: {
                /** @description Force upsert during a put/post operation. */
                force?: components["parameters"]["ForceUpsert"];
            };
            header?: never;
            path: {
                /** @description Type of subject of a relation. */
                subjectType: components["parameters"]["SubjectType"];
                /** @description ID of the subject of a relation. */
                subjectID: components["parameters"]["SubjectID"];
                /** @description Type of relation. */
                relation: components["parameters"]["RelationType"];
                /** @description Type of object of a relation. */
                objectType: components["parameters"]["ObjectType"];
                /** @description ID of the object of a relation. */
                objectID: components["parameters"]["ObjectID"];
            };
            cookie?: never;
        };
        /** @description Content of the new relation. */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["Relation"];
            };
        };
        responses: {
            /** @description Entity created. */
            201: {
                headers: {
                    /** @description Full version number of the API. */
                    "API-Version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelationResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["NotAuthorized"];
            403: components["responses"]["AccessDenied"];
            409: components["responses"]["AlreadyExists"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    "remove-relation": {
        parameters: {
            query?: {
                /** @description Ignore missing data during a delete operation. */
                force?: components["parameters"]["IgnoreMissing"];
            };
            header?: never;
            path: {
                /** @description Type of subject of a relation. */
                subjectType: components["parameters"]["SubjectType"];
                /** @description ID of the subject of a relation. */
                subjectID: components["parameters"]["SubjectID"];
                /** @description Type of relation. */
                relation: components["parameters"]["RelationType"];
                /** @description Type of object of a relation. */
                objectType: components["parameters"]["ObjectType"];
                /** @description ID of the object of a relation. */
                objectID: components["parameters"]["ObjectID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Relation removed. */
            200: {
                headers: {
                    /** @description Full version number of the API. */
                    "API-Version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelationResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["NotAuthorized"];
            403: components["responses"]["AccessDenied"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["UnexpectedError"];
        };
    };
}
