/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/attributes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve attributes.
         * @description Retrieve a list of all attributes.
         */
        get: operations["get-attributes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attribute/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique key of an attribute. */
                key: components["parameters"]["AttributeKey"];
            };
            cookie?: never;
        };
        /**
         * Retrieve attribute.
         * @description Retrieve a single specified attribute.
         */
        get: operations["get-attribute"];
        /**
         * Replace attribute.
         * @description Replace an existing attribute.
         *
         *     If the unique key of the attribute does not exist, a 404 response status code will be returned.
         *     You can override this behavior by passing the 'force' parameter in the query.
         */
        put: operations["replace-attribute"];
        /**
         * Add attribute.
         * @description Create a new attribute.
         *
         *     If the unique key of the attribute already exists, a 409 response status code will be returned.
         *     You can override this behavior by passing the 'force' parameter in the query.
         */
        post: operations["add-attribute"];
        /**
         * Remove attribute.
         * @description Remove an existing attribute.
         *
         *     If the unique key of the attribute does not exist, a 404 response status code will be returned.
         *     You can override this behavior by passing the 'force' parameter in the query.
         */
        delete: operations["remove-attribute"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attribute/{key}/status": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique key of an attribute. */
                key: components["parameters"]["AttributeKey"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Modify attribute status.
         * @description Modify the status of an existing attribute.
         */
        patch: operations["status-attribute"];
        trace?: never;
    };
    "/entities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve entities.
         * @description Retrieve a list of all entities.
         */
        get: operations["get-entities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entity/{type}/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Type of entity. */
                type: components["parameters"]["EntityType"];
                /** @description ID of an entity. */
                id: components["parameters"]["EntityID"];
            };
            cookie?: never;
        };
        /**
         * Retrieve entity.
         * @description Retrieve a specified entity.
         */
        get: operations["get-entity"];
        /**
         * Replace entity.
         * @description Replace an existing entity.
         *
         *     If the unique type+id of the entity does not exist, a 404 response status code will be returned.
         *     You can override this behavior by passing the 'force' parameter in the query.
         */
        put: operations["remove-entity"];
        /**
         * Add entity.
         * @description Create a new entity.
         *
         *     If the unique type+id of the entity already exists, a 409 response status code will be returned.
         *     You can override this behavior by passing the 'force' parameter in the query.
         */
        post: operations["add-entity"];
        /**
         * Remove entity.
         * @description Remove an existing entity.
         *
         *     If the unique type+id of the entity does not exist, a 404 response status code will be returned.
         *     You can override this behavior by passing the 'force' parameter in the query.
         */
        delete: operations["delete-entity"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entity/{type}/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Type of entity. */
                type: components["parameters"]["EntityType"];
                /** @description ID of an entity. */
                id: components["parameters"]["EntityID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Modify entity status.
         * @description Modify the status of an existing entity.
         */
        patch: operations["status-entity"];
        trace?: never;
    };
    "/relations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve relations.
         * @description Retrieve a list of all relations.
         */
        get: operations["get-relations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/relation/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of a relation (UUID). */
                id: components["parameters"]["RelationID"];
            };
            cookie?: never;
        };
        /**
         * Retrieve relation.
         * @description Retrieve a specified relation.
         */
        get: operations["get-relation"];
        /**
         * Replace relation.
         * @description Replace an existing relation.
         *
         *     If the unique subject+relation+object of the relation does not exist, a 404 response status code will be returned.
         *     You can override this behavior by passing the 'force' parameter in the query.
         */
        put: operations["replace-relation"];
        /**
         * Add relation.
         * @description Create a new relation.
         *
         *     If the unique subject+relation+object of the relation already exists, a 409 response status code will be returned.
         *     You can override this behavior by passing the 'force' parameter in the query.
         */
        post: operations["add-relation"];
        /**
         * Remove relation.
         * @description Remove an existing relation.
         *
         *     If the unique subject+relation+object of the relation does not exist, a 404 response status code will be returned.
         *     You can override this behavior by passing the 'force' parameter in the query.
         */
        delete: operations["remove-relation"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/relation/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of a relation (UUID). */
                id: components["parameters"]["RelationID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Modify relation status.
         * @description Modify the status of an existing relation.
         */
        patch: operations["status-relation"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Who performed an action. `id` is the stored attribution value and is always present;
         *     `name` is filled in from the manager's local principal record and is absent when that
         *     record is unknown, in which case clients show the raw `id`. Only a principal of kind
         *     `user` identifies a real subject and may be linked to.
         */
        Principal: {
            /**
             * @description Stable identifier of the principal, as stored on the object.
             * @example 8f14e45f-ceea-467a-9c1b-1a1b0c2d3e4f
             */
            id: string;
            /**
             * @description Display name of the principal, when known.
             * @example alice@wonderland.cc
             */
            name?: string;
            /**
             * @description `user` for an authenticated subject, `system` for the manager's own actions, and
             *     `legacy` for an attribution value predating the principal record, which is shown
             *     but identifies nobody.
             * @example user
             * @enum {string}
             */
            kind?: "user" | "system" | "legacy";
        };
        /** @description The metadata associated with an object. */
        Metadata: {
            /**
             * @description The title of the object. E.g., a short description.
             * @example Worktimes schedule
             */
            title: string;
            /**
             * @description Detailed description of the object.
             * @example Daily schedule with start and end of working period
             */
            description?: string;
            /**
             * @description List of tags the object is annotated with.
             *
             *     This is used to determine which PDP (or set of PDPs) objects can be pushed to.
             *
             *     Verify with the policies.tags endpoint.
             */
            tags?: string[];
        };
        /** @description The audit details for an object. */
        ObjectAudit: {
            /**
             * @description Timestamp the object was created (RFC3339 format).
             * @example 2025-08-15T07:53:41.493415Z
             */
            created: string;
            createdBy: components["schemas"]["Principal"];
            /**
             * @description Timestamp the object was last updated (RFC3339 format).
             * @example 2025-08-15T07:53:41.493415Z
             */
            updated?: string;
            updatedBy?: components["schemas"]["Principal"];
        };
        /** @description Metadata about how, when and by whom an object has been manipulated. */
        AuditEntry: {
            /**
             * @description Timestamp of the log entry in RFC3339 format.
             * @example 2025-08-15T07:53:41.493415Z
             */
            created: string;
            /**
             * @description Operation performed on the object. Any of ["C", "U", "D"].
             * @example C
             */
            operation: string;
            userId: components["schemas"]["Principal"];
        };
        /** @description Metadata about when and where the object is used. */
        UsageData: {
            /**
             * @description Code of the bundle the object was included in.
             * @example pdp1
             */
            bundle?: string;
            /**
             * @description Version number of the deployment.
             * @example 1
             */
            version?: number;
            /**
             * @description Timestamp the deployment was created (RFC3339 format).
             * @example 2025-08-15T07:53:41.493415Z
             */
            created?: string;
            createdBy?: components["schemas"]["Principal"];
            /**
             * @description Status of the deployment.
             * @example completed
             */
            status?: string;
        };
        Attributes: components["schemas"]["Attribute"][];
        /** @description The content of an attribute (key/value pair). */
        Attribute: {
            /**
             * @description The unique key of the attribute.
             * @example gemeentecode
             */
            key: string;
            /**
             * @description The value of the attribute.
             * @example 0123
             */
            value: unknown;
            /**
             * @description The current status of the attribute ('concept', 'accepted', 'deployed').
             * @example concept
             */
            status: string;
            /**
             * @description The optional type of a value. By default a value is stored as-is (e.g., JSON type).
             *
             *     The following codes for type are supported:
             *     "*string*", "*integer*", "*float*", "*boolean*", "*date*", "*time*", "*timestamp*".
             *     Optionally, the type can be specified as one of the standard XSD types (e.g. "*xsd:byte*").
             *
             *     An *integer* value (of any size) is stored as a 64-bit signed or unsigned integer.
             *
             *     A *float* value is stored with double precision.
             *
             *     A *boolean* value can be *true* (case-insensitive) or *1* to represent a true state,
             *     or any other value to represent a false state.
             *
             *     A *date*, *time* or *timestamp* value should adhere to the format as described in RFC3339.
             *     If it cannot be decoded according to RFC3339, a 400 response status code will be returned.
             */
            type?: string;
            metadata: components["schemas"]["Metadata"];
            audit: components["schemas"]["ObjectAudit"];
            /** @description Audit log for the attribute. */
            auditLog?: components["schemas"]["AuditEntry"][];
            /** @description Usage data for the policy. */
            usageData?: components["schemas"]["UsageData"][];
        };
        /** @description The status of an attribute (key/value pair). */
        AttributeStatus: {
            /**
             * @description The unique key of the attribute.
             * @example gemeentecode
             */
            key: string;
            /**
             * @description The current status of the attribute ('concept', 'accepted', 'deployed').
             * @example concept
             */
            status: string;
        };
        Entities: components["schemas"]["Entity"][];
        /**
         * @description The content of an entity.
         *
         *     The combination of *type* and *id* defines the unique key of an entity.
         */
        Entity: {
            /**
             * @description The type of entity.
             * @example user
             */
            type: string;
            /**
             * @description The identification of the entity.
             * @example alice
             */
            id: string;
            /**
             * @description The current status of the entity ('concept', 'accepted', 'deployed').
             * @example concept
             */
            status: string;
            /** @description Optional attributes of the entity. */
            attributes?: components["schemas"]["Attribute"][];
            metadata: components["schemas"]["Metadata"];
            audit: components["schemas"]["ObjectAudit"];
            /** @description Audit log for the entity. */
            auditLog?: components["schemas"]["AuditEntry"][];
            /** @description Usage data for the policy. */
            usageData?: components["schemas"]["UsageData"][];
        };
        /** @description The status of an entity. */
        EntityStatus: {
            /**
             * @description The type of entity.
             * @example user
             */
            type: string;
            /**
             * @description The identification of the entity.
             * @example alice
             */
            id: string;
            /**
             * @description The current status of the entity ('concept', 'accepted', 'deployed').
             * @example concept
             */
            status: string;
        };
        Relations: components["schemas"]["Relation"][];
        /**
         * @description The content of a relation.
         *
         *     The combination of *subject type/id*, *relation* and *object type/id* must be unique for all relations.
         */
        Relation: {
            /**
             * @description The unique identifier of the relation (UUID).
             * @example f1e40dfa-7e2a-4767-81a7-65f790d3bbcd
             */
            id: string;
            /**
             * @description The current status of the relation ('concept', 'accepted', 'deployed').
             * @example concept
             */
            status: string;
            /**
             * @description The type of subject of the relation.
             * @example user
             */
            subjectType: string;
            /**
             * @description The identifier of the subject of the relation.
             * @example alice
             */
            subjectId: string;
            /**
             * @description The type of relation.
             * @example managerOf
             */
            relation: string;
            /**
             * @description The type of object of the relation.
             * @example user
             */
            objectType: string;
            /**
             * @description The identifier of the object of the relation.
             * @example bob
             */
            objectId: string;
            /** @description Optional attributes of the relation. */
            attributes?: components["schemas"]["Attribute"][];
            metadata: components["schemas"]["Metadata"];
            audit: components["schemas"]["ObjectAudit"];
            /** @description Audit log for the relation. */
            auditLog?: components["schemas"]["AuditEntry"][];
            /** @description Usage data for the policy. */
            usageData?: components["schemas"]["UsageData"][];
        };
        /** @description The status of a relation. */
        RelationStatus: {
            /**
             * @description The unique identifier of the relation (UUID).
             * @example f1e40dfa-7e2a-4767-81a7-65f790d3bbcd
             */
            id: string;
            /**
             * @description The current status of the relation ('concept', 'accepted', 'deployed').
             * @example concept
             */
            status: string;
        };
        /** @description The response for an error (as defined by RFC9457). */
        Error: {
            /**
             * Format: uri
             * @description Identification of the problem.
             */
            type?: string;
            /** @description Status code of the problem. */
            status?: number;
            /** @description Summary of the problem. */
            title?: string;
            /** @description Detailed description of the problem. */
            detail?: string;
            /**
             * Format: uri
             * @description Identification of the problem instance.
             */
            instance?: string;
        };
    };
    responses: {
        /** @description Attributes found. */
        AttributesResponse: {
            headers: {
                /** @description Full version number of the API. */
                "API-Version"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Attributes"];
            };
        };
        /** @description Attribute found, created, replaced or removed. */
        AttributeResponse: {
            headers: {
                /** @description Full version number of the API. */
                "API-Version"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Attribute"];
            };
        };
        /** @description Entities found. */
        EntitiesResponse: {
            headers: {
                /** @description Full version number of the API. */
                "API-Version"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Entities"];
            };
        };
        /** @description Entity found, created, replaced or removed. */
        EntityResponse: {
            headers: {
                /** @description Full version number of the API. */
                "API-Version"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Entity"];
            };
        };
        /** @description Relations found. */
        RelationsResponse: {
            headers: {
                /** @description Full version number of the API. */
                "API-Version"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Relations"];
            };
        };
        /** @description Relation found, created, replaced or removed. */
        RelationResponse: {
            headers: {
                /** @description Full version number of the API. */
                "API-Version"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Relation"];
            };
        };
        /** @description Bad request. */
        BadRequest: {
            headers: {
                /** @description Full version number of the API. */
                "API-Version"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Not authorized. */
        NotAuthorized: {
            headers: {
                /** @description Full version number of the API. */
                "API-Version"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Access denied. */
        AccessDenied: {
            headers: {
                /** @description Full version number of the API. */
                "API-Version"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource not found. */
        NotFound: {
            headers: {
                /** @description Full version number of the API. */
                "API-Version"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource already exists. */
        AlreadyExists: {
            headers: {
                /** @description Full version number of the API. */
                "API-Version"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Unexpected error. */
        UnexpectedError: {
            headers: {
                /** @description Full version number of the API. */
                "API-Version"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description Unique key of an attribute. */
        AttributeKey: string;
        /** @description Type of entity. */
        EntityType: string;
        /** @description ID of an entity. */
        EntityID: string;
        /** @description Unique identifier of a relation (UUID). */
        RelationID: string;
        /** @description Force upsert during a put/post operation. */
        ForceUpsert: boolean;
        /** @description Ignore missing data during a delete operation. */
        IgnoreMissing: boolean;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "get-attributes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["AttributesResponse"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["NotAuthorized"];
            403: components["responses"]["AccessDenied"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    "get-attribute": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique key of an attribute. */
                key: components["parameters"]["AttributeKey"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["AttributeResponse"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["NotAuthorized"];
            403: components["responses"]["AccessDenied"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    "replace-attribute": {
        parameters: {
            query?: {
                /** @description Force upsert during a put/post operation. */
                force?: components["parameters"]["ForceUpsert"];
            };
            header?: never;
            path: {
                /** @description Unique key of an attribute. */
                key: components["parameters"]["AttributeKey"];
            };
            cookie?: never;
        };
        /** @description Content of the new attribute. */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["Attribute"];
            };
        };
        responses: {
            200: components["responses"]["AttributeResponse"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["NotAuthorized"];
            403: components["responses"]["AccessDenied"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    "add-attribute": {
        parameters: {
            query?: {
                /** @description Force upsert during a put/post operation. */
                force?: components["parameters"]["ForceUpsert"];
            };
            header?: never;
            path: {
                /** @description Unique key of an attribute. */
                key: components["parameters"]["AttributeKey"];
            };
            cookie?: never;
        };
        /** @description Content of the new attribute. */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["Attribute"];
            };
        };
        responses: {
            201: components["responses"]["AttributeResponse"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["NotAuthorized"];
            403: components["responses"]["AccessDenied"];
            409: components["responses"]["AlreadyExists"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    "remove-attribute": {
        parameters: {
            query?: {
                /** @description Ignore missing data during a delete operation. */
                force?: components["parameters"]["IgnoreMissing"];
            };
            header?: never;
            path: {
                /** @description Unique key of an attribute. */
                key: components["parameters"]["AttributeKey"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["AttributeResponse"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["NotAuthorized"];
            403: components["responses"]["AccessDenied"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    "status-attribute": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique key of an attribute. */
                key: components["parameters"]["AttributeKey"];
            };
            cookie?: never;
        };
        /** @description New status of the attribute. */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AttributeStatus"];
            };
        };
        responses: {
            200: components["responses"]["AttributeResponse"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["NotAuthorized"];
            403: components["responses"]["AccessDenied"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    "get-entities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["EntitiesResponse"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["NotAuthorized"];
            403: components["responses"]["AccessDenied"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    "get-entity": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Type of entity. */
                type: components["parameters"]["EntityType"];
                /** @description ID of an entity. */
                id: components["parameters"]["EntityID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["EntityResponse"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["NotAuthorized"];
            403: components["responses"]["AccessDenied"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    "remove-entity": {
        parameters: {
            query?: {
                /** @description Force upsert during a put/post operation. */
                force?: components["parameters"]["ForceUpsert"];
            };
            header?: never;
            path: {
                /** @description Type of entity. */
                type: components["parameters"]["EntityType"];
                /** @description ID of an entity. */
                id: components["parameters"]["EntityID"];
            };
            cookie?: never;
        };
        /** @description Content of the new entity. */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["Entity"];
            };
        };
        responses: {
            200: components["responses"]["EntityResponse"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["NotAuthorized"];
            403: components["responses"]["AccessDenied"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    "add-entity": {
        parameters: {
            query?: {
                /** @description Force upsert during a put/post operation. */
                force?: components["parameters"]["ForceUpsert"];
            };
            header?: never;
            path: {
                /** @description Type of entity. */
                type: components["parameters"]["EntityType"];
                /** @description ID of an entity. */
                id: components["parameters"]["EntityID"];
            };
            cookie?: never;
        };
        /** @description Content of the new entity. */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["Entity"];
            };
        };
        responses: {
            201: components["responses"]["EntityResponse"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["NotAuthorized"];
            403: components["responses"]["AccessDenied"];
            409: components["responses"]["AlreadyExists"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    "delete-entity": {
        parameters: {
            query?: {
                /** @description Ignore missing data during a delete operation. */
                force?: components["parameters"]["IgnoreMissing"];
            };
            header?: never;
            path: {
                /** @description Type of entity. */
                type: components["parameters"]["EntityType"];
                /** @description ID of an entity. */
                id: components["parameters"]["EntityID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["EntityResponse"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["NotAuthorized"];
            403: components["responses"]["AccessDenied"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    "status-entity": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Type of entity. */
                type: components["parameters"]["EntityType"];
                /** @description ID of an entity. */
                id: components["parameters"]["EntityID"];
            };
            cookie?: never;
        };
        /** @description New status of the entity. */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["EntityStatus"];
            };
        };
        responses: {
            200: components["responses"]["EntityResponse"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["NotAuthorized"];
            403: components["responses"]["AccessDenied"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    "get-relations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["RelationsResponse"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["NotAuthorized"];
            403: components["responses"]["AccessDenied"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    "get-relation": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of a relation (UUID). */
                id: components["parameters"]["RelationID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["RelationResponse"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["NotAuthorized"];
            403: components["responses"]["AccessDenied"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    "replace-relation": {
        parameters: {
            query?: {
                /** @description Force upsert during a put/post operation. */
                force?: components["parameters"]["ForceUpsert"];
            };
            header?: never;
            path: {
                /** @description Unique identifier of a relation (UUID). */
                id: components["parameters"]["RelationID"];
            };
            cookie?: never;
        };
        /** @description Content of the new relation. */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["Relation"];
            };
        };
        responses: {
            200: components["responses"]["RelationResponse"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["NotAuthorized"];
            403: components["responses"]["AccessDenied"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    "add-relation": {
        parameters: {
            query?: {
                /** @description Force upsert during a put/post operation. */
                force?: components["parameters"]["ForceUpsert"];
            };
            header?: never;
            path: {
                /** @description Unique identifier of a relation (UUID). */
                id: components["parameters"]["RelationID"];
            };
            cookie?: never;
        };
        /** @description Content of the new relation. */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["Relation"];
            };
        };
        responses: {
            201: components["responses"]["RelationResponse"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["NotAuthorized"];
            403: components["responses"]["AccessDenied"];
            409: components["responses"]["AlreadyExists"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    "remove-relation": {
        parameters: {
            query?: {
                /** @description Ignore missing data during a delete operation. */
                force?: components["parameters"]["IgnoreMissing"];
            };
            header?: never;
            path: {
                /** @description Unique identifier of a relation (UUID). */
                id: components["parameters"]["RelationID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["RelationResponse"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["NotAuthorized"];
            403: components["responses"]["AccessDenied"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["UnexpectedError"];
        };
    };
    "status-relation": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of a relation (UUID). */
                id: components["parameters"]["RelationID"];
            };
            cookie?: never;
        };
        /** @description New status of the relation. */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RelationStatus"];
            };
        };
        responses: {
            200: components["responses"]["RelationResponse"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["NotAuthorized"];
            403: components["responses"]["AccessDenied"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["UnexpectedError"];
        };
    };
}
