/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/adl/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Query Authorization Decision Log.
         * @description Endpoint to search for and retrieve Authorization Decision Log entries.
         *
         *     Resulting entries are sorted in descending order of creation.
         *
         */
        get: operations["get-adl-entries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description A set of Authorization Decision Log entries. */
        AuthlogEntries: components["schemas"]["AuthlogEntry"][];
        /** @description An Authorization Decision Log entry. */
        AuthlogEntry: {
            /**
             * Format: int64
             * @description Unique identifier.
             */
            id?: number;
            /** @description Timestamp the entry was created. */
            created?: string;
            /** @description Type of AuthZEN request. */
            requestType?: string;
            /** @description Unique identifier of the policy bundle used during the authorization process. */
            policies?: string;
            /** @description AuthZEN request. */
            request?: Record<string, never>;
            /** @description AuthZEN response. */
            response?: Record<string, never>;
            /** @description Information (attributes) used during the authorization process. */
            information?: Record<string, never>;
            /** @description Details of the PDP engine. */
            engine?: Record<string, never>;
            /** @description W3C trace identifier from the authorization request. */
            traceId?: string;
            /** @description W3C span identifier from the authorization request. */
            spanId?: string;
        };
        /** @description The body for an error response (as defined by RFC9457). */
        ErrorObject: {
            /**
             * Format: uri
             * @description Identification of the problem.
             */
            type?: string;
            /** @description Status code of the problem. */
            status?: number;
            /** @description Summary of the problem. */
            title?: string;
            /** @description Detailed description of the problem. */
            detail?: string;
            /**
             * Format: uri
             * @description Identification of the problem instance.
             */
            instance?: string;
        };
    };
    responses: {
        /** @description Log entries found. */
        AuthlogResponse: {
            headers: {
                /** @description Full version number of the API. */
                "API-Version"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["AuthlogEntries"];
            };
        };
        /** @description Bad request. */
        BadRequest: {
            headers: {
                /** @description Full version number of the API. */
                "API-Version"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorObject"];
            };
        };
        /** @description Not authorized. */
        NotAuthorized: {
            headers: {
                /** @description Full version number of the API. */
                "API-Version"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorObject"];
            };
        };
        /** @description Access denied. */
        AccessDenied: {
            headers: {
                /** @description Full version number of the API. */
                "API-Version"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorObject"];
            };
        };
        /** @description Resource not found. */
        NotFound: {
            headers: {
                /** @description Full version number of the API. */
                "API-Version"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorObject"];
            };
        };
        /** @description Unexpected error. */
        UnexpectedError: {
            headers: {
                /** @description Full version number of the API. */
                "API-Version"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorObject"];
            };
        };
    };
    parameters: {
        /** @description Select exact decision log identifier.
         *
         *     This is mutually exclusive with all other parameters.
         *      */
        DecisionId: number;
        /** @description Select a period upto and including the current timestamp.
         *
         *     This parameter is mutually exclusive with the start timestamp.
         *
         *     The string should be formatted as a to Golang duration.
         *     E.g.:
         *     - "1m"       = 1 minute.
         *     - "12s"      = 12 seconds.
         *     - "3h"       = 3 hours.
         *     - "1h10m15s" = 1 hour, 10 minutes and 15 seconds.
         *      */
        RecentPeriod: string;
        /** @description Filter entries with a created timestamp greater of equal this (RFC3339).
         *
         *     This parameter is mutually exclusive with the recent period.
         *      */
        StartTimestamp: string;
        /** @description Filter entries with a created timestamp lesser of equal this (RFC3339).
         *
         *     Default is the current timestamp.
         *      */
        EndTimestamp: string;
        /** @description Filter entries matching one of the AuthZEN request types.
         *
         *     Valid values are:
         *     - evaluation
         *     - evaluations
         *     - search_subject
         *     - search_action
         *     - search_resource
         *
         *     Duplicate values are not allowed.
         *      */
        RequestTypes: string[];
        /** @description Filter entries matching one of the policy bundle identifiers.
         *
         *     Maximum 10 bundle identifiers can be supplied.
         *     Duplicate values are not allowed.
         *      */
        Policies: string[];
        /** @description Filter entries with a matching W3C trace identifier.
         *
         *     Must be exactly 32 characters in hexadecimal.
         *      */
        TraceId: string;
        /** @description Filter entries with a matching W3C span identifier.
         *
         *     Must be exactly 16 characters in hexadecimal.
         *      */
        SpanId: string;
        /** @description Filter entries with a matching subject type. */
        SubjectType: string;
        /** @description Filter entries with a matching subject identifier.
         *
         *     Use of this parameter may considerably impact performance.
         *      */
        SubjectId: string;
        /** @description Filter entries with a matching action name.
         *
         *     Use of this parameter may considerably impact performance.
         *      */
        ActionName: string;
        /** @description Filter entries with a matching resource type.
         *
         *     Use of this parameter may considerably impact performance.
         *      */
        ResourceType: string;
        /** @description Filter entries with a matching resource identifier.
         *
         *     Use of this parameter may considerably impact performance.
         *      */
        ResourceId: string;
        /** @description Limit the result to this many entries.
         *
         *     The default limit is 100 entries.
         *     All entries are sorted in descending order of creation.
         *      */
        Limit: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "get-adl-entries": {
        parameters: {
            query?: {
                /** @description Select exact decision log identifier.
                 *
                 *     This is mutually exclusive with all other parameters.
                 *      */
                id?: components["parameters"]["DecisionId"];
                /** @description Filter entries with a created timestamp greater of equal this (RFC3339).
                 *
                 *     This parameter is mutually exclusive with the recent period.
                 *      */
                start?: components["parameters"]["StartTimestamp"];
                /** @description Filter entries with a created timestamp lesser of equal this (RFC3339).
                 *
                 *     Default is the current timestamp.
                 *      */
                end?: components["parameters"]["EndTimestamp"];
                /** @description Select a period upto and including the current timestamp.
                 *
                 *     This parameter is mutually exclusive with the start timestamp.
                 *
                 *     The string should be formatted as a to Golang duration.
                 *     E.g.:
                 *     - "1m"       = 1 minute.
                 *     - "12s"      = 12 seconds.
                 *     - "3h"       = 3 hours.
                 *     - "1h10m15s" = 1 hour, 10 minutes and 15 seconds.
                 *      */
                recent?: components["parameters"]["RecentPeriod"];
                /** @description Filter entries matching one of the AuthZEN request types.
                 *
                 *     Valid values are:
                 *     - evaluation
                 *     - evaluations
                 *     - search_subject
                 *     - search_action
                 *     - search_resource
                 *
                 *     Duplicate values are not allowed.
                 *      */
                types?: components["parameters"]["RequestTypes"];
                /** @description Filter entries matching one of the policy bundle identifiers.
                 *
                 *     Maximum 10 bundle identifiers can be supplied.
                 *     Duplicate values are not allowed.
                 *      */
                policies?: components["parameters"]["Policies"];
                /** @description Filter entries with a matching W3C trace identifier.
                 *
                 *     Must be exactly 32 characters in hexadecimal.
                 *      */
                traceId?: components["parameters"]["TraceId"];
                /** @description Filter entries with a matching W3C span identifier.
                 *
                 *     Must be exactly 16 characters in hexadecimal.
                 *      */
                spanId?: components["parameters"]["SpanId"];
                /** @description Filter entries with a matching subject type. */
                subjectType?: components["parameters"]["SubjectType"];
                /** @description Filter entries with a matching subject identifier.
                 *
                 *     Use of this parameter may considerably impact performance.
                 *      */
                subjectId?: components["parameters"]["SubjectId"];
                /** @description Filter entries with a matching action name.
                 *
                 *     Use of this parameter may considerably impact performance.
                 *      */
                actionName?: components["parameters"]["ActionName"];
                /** @description Filter entries with a matching resource type.
                 *
                 *     Use of this parameter may considerably impact performance.
                 *      */
                resourceType?: components["parameters"]["ResourceType"];
                /** @description Filter entries with a matching resource identifier.
                 *
                 *     Use of this parameter may considerably impact performance.
                 *      */
                resourceId?: components["parameters"]["ResourceId"];
                /** @description Limit the result to this many entries.
                 *
                 *     The default limit is 100 entries.
                 *     All entries are sorted in descending order of creation.
                 *      */
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["AuthlogResponse"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["NotAuthorized"];
            403: components["responses"]["AccessDenied"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["UnexpectedError"];
        };
    };
}
