/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/statuses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve deployment status codes.
         * @description Endpoint to retrieve all deployment status codes and names.
         */
        get: operations["get-statuses"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/compression-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve deployment compression types.
         * @description Endpoint to retrieve all bundle compression types.
         */
        get: operations["get-compression-types"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bundle-configurations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve bundle configurations.
         * @description Endpoint to retrieve the list of bundle configurations.
         */
        get: operations["get-configurations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deployments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve deployments.
         * @description Endpoint to retrieve the details of all deployments.
         */
        get: operations["get-deployments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deployment/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve deployment.
         * @description Endpoint to retrieve the details of a specific deployment.
         */
        get: operations["get-deployment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deployment/last": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve last deployment.
         * @description Endpoint to retrieve the details of the last deployment.
         */
        get: operations["get-last-deployment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deployment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Deploy a new version.
         * @description Endpoint to start a new deployment.
         */
        post: operations["start-deployment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bundle/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve the latest deployment bundle.
         * @description Endpoint to retrieve the latest deployment bundle and initialize the set of policies and static data.
         *
         *     This endpoint should be called by PDPs during initialization
         *     when they are **not** configured with local policies and data.
         */
        get: operations["get-bundle"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bundle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Receive a new deployment bundle.
         * @description Endpoint to receive a new deployment bundle and replace the full set of policies and static data.
         *
         *     This endpoint should be implemented by PDPs
         *     when they are **not** configured with local policies and data.
         */
        post: operations["push-bundle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Body content for a new deployment request. */
        NewDeploymentBody: {
            /** @description Title of the new deployment. */
            title: string;
            /** @description Optional description of the new deployment. */
            description?: string;
        };
        /** @description The audit details for an object. */
        ObjectAudit: {
            /**
             * @description Timestamp the object was created (RFC3339 format).
             * @example 2025-08-15T07:53:41.493415Z
             */
            created: string;
            /**
             * @description User that created the object.
             * @example alice@wonderland.cc
             */
            createdBy: string;
            /**
             * @description Timestamp the object was last updated (RFC3339 format).
             * @example 2025-08-15T07:53:41.493415Z
             */
            updated?: string;
            /**
             * @description User that last updated the object.
             * @example bob@wonderworld.cc
             */
            updatedBy?: string;
        };
        /** @description List of deployment status codes and names. */
        Statuses: components["schemas"]["Status"][];
        /** @description The code and name of a deployment status. */
        Status: {
            /**
             * @description Code of the status.
             * @example 1
             */
            code: number;
            /**
             * @description Display name for the status.
             * @example Created
             */
            name: string;
        };
        /** @description List of compression type codes and names. */
        CompressTypes: components["schemas"]["CompressType"][];
        /** @description The code and name of a compression type. */
        CompressType: {
            /**
             * @description Code of the compression type.
             * @example 2
             */
            code: number;
            /**
             * @description Display name for the compression type.
             * @example BZip2
             */
            name: string;
        };
        /** @description List of bundle deployment configurations. */
        BundleConfigs: components["schemas"]["BundleConfig"][];
        /** @description Bundle deployment configuration. */
        BundleConfig: {
            /** @description Unique identifier of this bundle deployment configuration (UUID). */
            id: string;
            /** @description Title of this bundle deployment configuration. */
            title: string;
            /** @description Optional description of this bundle deployment configuration. */
            description?: string;
            /** @description Indicates to bundle the version number. */
            version?: boolean;
            /** @description Indicates to bundle policies with matching tag. */
            policies?: boolean;
            /** @description Indicates to bundle attributes, entities and relations with matching tag. */
            data?: boolean;
            /** @description Tags to match against. A single matching tag is sufficient. */
            tags: string[];
            targets: components["schemas"]["Target"][];
        };
        /** @description The details of a bundle target. */
        Target: {
            /** @description URI of the target PDP. */
            uri: string;
            /** @description Indicates the connection will force the use of TLS. */
            tls?: boolean;
            /** @description Indicates an API-key is configured. */
            apikey?: boolean;
            /** @description Type of compression to use for the bundle (default = gzip). */
            compression?: number;
            /** @description List of optional HTTP headers to send. */
            headers?: string[];
        };
        /** @description List of bundle deployments. */
        Deployments: components["schemas"]["Deployment"][];
        /** @description The details of a bundle deployment. */
        Deployment: {
            /** @description Version number of the last deployment. */
            version: number;
            /** @description Title of the deployment. */
            title: string;
            /** @description Optional description of the deployment. */
            description?: string;
            /** @description Status of the deployment. */
            status: number;
            /** @description Message for a failed deployment. */
            message?: string;
            audit: components["schemas"]["ObjectAudit"];
        };
        /** @description The details of a deployment bundle activation. */
        BundleActivated: {
            /** @description Version number of the replaced deployment. */
            previousVersion: number;
        };
        /** @description The response for an error (as defined by RFC9457). */
        ErrorMessage: {
            /**
             * Format: uri
             * @description Identification of the problem.
             */
            type?: string;
            /** @description Status code of the problem. */
            status?: number;
            /** @description Summary of the problem. */
            title?: string;
            /** @description Detailed description of the problem. */
            detail?: string;
            /**
             * Format: uri
             * @description Identification of the problem instance.
             */
            instance?: string;
        };
    };
    responses: {
        /** @description Statuses found. */
        StatusesFound: {
            headers: {
                /** @description Full version number of the API. */
                "API-Version"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Statuses"];
            };
        };
        /** @description Compression types found. */
        CompressTypesFound: {
            headers: {
                /** @description Full version number of the API. */
                "API-Version"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["CompressTypes"];
            };
        };
        /** @description Bundle configurations found. */
        ConfigFound: {
            headers: {
                /** @description Full version number of the API. */
                "API-Version"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["BundleConfigs"];
            };
        };
        /** @description Deployments found. */
        DeploymentsFound: {
            headers: {
                /** @description Full version number of the API. */
                "API-Version"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Deployments"];
            };
        };
        /** @description Deployment found. */
        DeploymentFound: {
            headers: {
                /** @description Full version number of the API. */
                "API-Version"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Deployment"];
            };
        };
        /** @description Bundle deployment started. */
        DeployStarted: {
            headers: {
                /** @description Full version number of the API. */
                "API-Version"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Deployment"];
            };
        };
        /** @description Deployment bundle activated. */
        BundleActivated: {
            headers: {
                /** @description Full version number of the API. */
                "API-Version"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["BundleActivated"];
            };
        };
        /** @description Deployment bundle found. */
        BundleFound: {
            headers: {
                /** @description Full version number of the API. */
                "API-Version"?: string;
                /** @description Compression type. */
                "Content-Encoding"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/octet-stream": string;
            };
        };
        /** @description Bad request. */
        BadRequest: {
            headers: {
                /** @description Full version number of the API. */
                "API-Version"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorMessage"];
            };
        };
        /** @description Not authenticated (401 status code). */
        NotAuthenticated: {
            headers: {
                /** @description Full version number of the API. */
                "API-Version"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorMessage"];
            };
        };
        /** @description Not authorized (403 status code - access denied). */
        NotAuthorized: {
            headers: {
                /** @description Full version number of the API. */
                "API-Version"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorMessage"];
            };
        };
        /** @description Resource not found. */
        NotFound: {
            headers: {
                /** @description Full version number of the API. */
                "API-Version"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorMessage"];
            };
        };
        /** @description Unexpected error. */
        UnexpectedError: {
            headers: {
                /** @description Full version number of the API. */
                "API-Version"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorMessage"];
            };
        };
    };
    parameters: {
        /** @description Unique version number of a deployment. */
        DeploymentID: number;
        /** @description Unique deployment bundle identifier (UUID). */
        BundleID: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "get-statuses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["StatusesFound"];
            401: components["responses"]["NotAuthenticated"];
            403: components["responses"]["NotAuthorized"];
            "5XX": components["responses"]["UnexpectedError"];
        };
    };
    "get-compression-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["CompressTypesFound"];
            401: components["responses"]["NotAuthenticated"];
            403: components["responses"]["NotAuthorized"];
            "5XX": components["responses"]["UnexpectedError"];
        };
    };
    "get-configurations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["ConfigFound"];
            401: components["responses"]["NotAuthenticated"];
            403: components["responses"]["NotAuthorized"];
            "5XX": components["responses"]["UnexpectedError"];
        };
    };
    "get-deployments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["DeploymentsFound"];
            401: components["responses"]["NotAuthenticated"];
            403: components["responses"]["NotAuthorized"];
            "5XX": components["responses"]["UnexpectedError"];
        };
    };
    "get-deployment": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique version number of a deployment. */
                key: components["parameters"]["DeploymentID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["DeploymentFound"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["NotAuthenticated"];
            403: components["responses"]["NotAuthorized"];
            404: components["responses"]["NotFound"];
            "5XX": components["responses"]["UnexpectedError"];
        };
    };
    "get-last-deployment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["DeploymentFound"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["NotAuthenticated"];
            403: components["responses"]["NotAuthorized"];
            404: components["responses"]["NotFound"];
            "5XX": components["responses"]["UnexpectedError"];
        };
    };
    "start-deployment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Parameters for a new bundle deployment. */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["NewDeploymentBody"];
            };
        };
        responses: {
            201: components["responses"]["DeployStarted"];
            401: components["responses"]["NotAuthenticated"];
            403: components["responses"]["NotAuthorized"];
            "5XX": components["responses"]["UnexpectedError"];
        };
    };
    "get-bundle": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique deployment bundle identifier (UUID). */
                id: components["parameters"]["BundleID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["BundleFound"];
            401: components["responses"]["NotAuthenticated"];
            403: components["responses"]["NotAuthorized"];
            "5XX": components["responses"]["UnexpectedError"];
        };
    };
    "push-bundle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Deployment bundle. */
        requestBody?: {
            content: {
                "application/octet-stream": string;
            };
        };
        responses: {
            201: components["responses"]["BundleActivated"];
            401: components["responses"]["NotAuthenticated"];
            403: components["responses"]["NotAuthorized"];
            "5XX": components["responses"]["UnexpectedError"];
        };
    };
}
