/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/languages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve languages.
         * @description Endpoint to retrieve the list of supported policy languages.
         */
        get: operations["get-languages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve tags.
         * @description Endpoint to retrieve the list of tags.
         */
        get: operations["get-tags"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/policies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve policies.
         * @description Endpoint to retrieve all policy keys.
         */
        get: operations["get-policies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/policy/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Unique identifier of a policy (UUID).
                 * @example b4911124-e92a-482f-80b4-eb02383378ae
                 */
                id: components["parameters"]["PolicyID"];
            };
            cookie?: never;
        };
        /**
         * Retrieve policy.
         * @description Retrieve a specified cached policy.
         */
        get: operations["get-policy"];
        /**
         * Replace policy.
         * @description If the unique identifier of the policy does not exist, a 404 status code will be returned.
         *     You can override this behavior by passing the 'force' parameter in the query.
         */
        put: operations["update-policy"];
        /**
         * Add policy.
         * @description If the unique identifier of the policy already exists, a 409 status code will be returned.
         *     You can override this behavior by passing the 'force' parameter in the query.
         */
        post: operations["create-policy"];
        /**
         * Remove policy.
         * @description If the unique identifier of the policy does not exist, a 404 status code will be returned.
         *     You can override this behavior by passing the 'force' parameter in the query.
         */
        delete: operations["delete-policy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/policy/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Unique identifier of a policy (UUID).
                 * @example b4911124-e92a-482f-80b4-eb02383378ae
                 */
                id: components["parameters"]["PolicyID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Modify policy status.
         * @description Modify the status of an existing policy.
         */
        patch: operations["status-policy"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Who performed an action. `id` is the stored attribution value and is always present;
         *     `name` is filled in from the manager's local principal record and is absent when that
         *     record is unknown, in which case clients show the raw `id`. Only a principal of kind
         *     `user` identifies a real subject and may be linked to.
         */
        Principal: {
            /**
             * @description Stable identifier of the principal, as stored on the object.
             * @example 8f14e45f-ceea-467a-9c1b-1a1b0c2d3e4f
             */
            id: string;
            /**
             * @description Display name of the principal, when known.
             * @example alice@wonderland.cc
             */
            name?: string;
            /**
             * @description `user` for an authenticated subject, `system` for the manager's own actions, and
             *     `legacy` for an attribution value predating the principal record, which is shown
             *     but identifies nobody.
             * @example user
             * @enum {string}
             */
            kind?: "user" | "system" | "legacy";
        };
        /** @description The metadata associated with a policy. */
        Metadata: {
            /**
             * @description The title of the policy. E.g., a short description.
             * @example BRP:Person:Subsidy
             */
            title: string;
            /**
             * @description Detailed description of the policy.
             * @example BRP - access person details for a subsidy
             */
            description?: string;
            /**
             * @description The unique identifier of the Register van Verwerkings-Activiteiten (RvVA).
             *     Only required when the policy is linked directly with an item in the RvVA.
             *     The value is considered as one of the tags of the policy.
             * @example <RvVA-identifier>
             */
            rvvaId?: string;
            /** @description Link to the policy. Required when the policy is stored externally. */
            url?: string;
            /**
             * @description List of tags the policy is annotated with.
             *
             *     This is used to determine which PDP (or set of PDPs) objects can be pushed to.
             *
             *     Verify with the tags endpoint.
             */
            tags?: string[];
        };
        /** @description The audit details of an object. */
        ObjectAudit: {
            /**
             * @description Timestamp the object was created (RFC3339 format).
             * @example 2025-08-15T07:53:41.493415Z
             */
            created: string;
            createdBy: components["schemas"]["Principal"];
            /**
             * @description Timestamp the object was last updated (RFC3339 format).
             * @example 2025-08-15T07:53:41.493415Z
             */
            updated?: string;
            updatedBy?: components["schemas"]["Principal"];
        };
        /** @description Metadata about how, when and by whom an object has been manipulated. */
        AuditEntry: {
            /**
             * @description Timestamp of the log entry in RFC3339 format.
             * @example 2025-08-15T07:53:41.493415Z
             */
            created: string;
            /**
             * @description Operation performed on the object. Any of ["C", "U", "D"].
             * @example C
             */
            operation: string;
            user: components["schemas"]["Principal"];
        };
        /** @description Metadata about when and where the object is used. */
        UsageData: {
            /**
             * @description Code of the bundle the object was included in.
             * @example pdp1
             */
            bundle?: string;
            /**
             * @description Version number of the deployment.
             * @example 1
             */
            version?: number;
            /**
             * @description Timestamp the deployment was created (RFC3339 format).
             * @example 2025-08-15T07:53:41.493415Z
             */
            created?: string;
            createdBy?: components["schemas"]["Principal"];
            /**
             * @description Status of the deployment.
             * @example completed
             */
            status?: string;
        };
        Languages: components["schemas"]["Language"][];
        /** @description The details of a policy language. */
        Language: {
            /**
             * @description The unique identifier of the policy language.
             * @example rego
             */
            id: string;
            /**
             * @description Name of the policy language in human-readable form.
             * @example Open Policy Agent - REGO language
             */
            name: string;
            /** @description Detailed description of the policy language. */
            description?: string;
            audit: components["schemas"]["ObjectAudit"];
            /** @description Audit log for the policy language. */
            auditLog?: components["schemas"]["AuditEntry"][];
        };
        Tags: components["schemas"]["Tag"][];
        /** @description The details of a tag. */
        Tag: {
            /**
             * @description The unique identifier of the tag.
             * @example brp
             */
            id: string;
            /**
             * @description Name of the tag in human-readable form.
             * @example Basis Registratie Personen
             */
            name: string;
            /** @description Detailed description of the tag. */
            description?: string;
            audit: components["schemas"]["ObjectAudit"];
            /** @description Audit log for the tag. */
            auditLog?: components["schemas"]["AuditEntry"][];
        };
        Policies: components["schemas"]["Policy"][];
        /** @description The content of a policy. */
        Policy: {
            /**
             * @description The unique identifier of the policy (UUID).
             * @example e8fce68e-beb6-494f-b6c1-9b0f8f6cac56
             */
            id: string;
            /**
             * @description The language of the policy.
             *     The value is case-insensitive.
             *     The value is considered as one of the tags of the policy.
             *
             *     Supported values:
             *     - "opa/rego"; alternatives: "opa", "rego", "opa-rego".
             *     - "cedar".
             *     - "cerbos/cel"; alternatives: "cerbos", "cel", "cerbos-cel".
             *     - "openfga"; alternative: "open-fga".
             *
             *     Verify with the languages endpoint.
             * @example cedar
             */
            language: string;
            /**
             * @description The current status of the policy ('concept', 'accepted', 'deployed').
             * @example concept
             */
            status: string;
            /**
             * @description Content of the policy. Required when the policy is stored internally.
             * @example permit (
             *       principal == doelbinding::"subsidies",
             *       action == action::"POST",
             *       resource is service
             *     )
             *     when {
             *       principal has brpPersonen &&
             *       resource.code == "BRP"
             *     };
             */
            data?: string;
            metadata: components["schemas"]["Metadata"];
            audit: components["schemas"]["ObjectAudit"];
            /** @description Audit log for the policy. */
            auditLog?: components["schemas"]["AuditEntry"][];
            /** @description Usage data for the policy. */
            usageData?: components["schemas"]["UsageData"][];
        };
        /** @description The status of a policy. */
        PolicyStatus: {
            /**
             * @description The unique identifier of the policy (UUID).
             * @example e8fce68e-beb6-494f-b6c1-9b0f8f6cac56
             */
            id: string;
            /**
             * @description The current status of the policy ('concept', 'accepted', 'deployed').
             * @example concept
             */
            status: string;
        };
        /** @description The response for an error (as defined by RFC9457). */
        Error: {
            /**
             * Format: uri
             * @description Identification of the problem.
             */
            type?: string;
            /** @description Status code of the problem. */
            status?: number;
            /** @description Summary of the problem. */
            title?: string;
            /** @description Detailed description of the problem. */
            detail?: string;
            /**
             * Format: uri
             * @description Identification of the problem instance.
             */
            instance?: string;
        };
    };
    responses: {
        /** @description Languages found. */
        LanguagesResponse: {
            headers: {
                /**
                 * @description Full version number of the API.
                 * @example 1.0.0
                 */
                "API-Version"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Languages"];
            };
        };
        /** @description Tags found. */
        TagsResponse: {
            headers: {
                /**
                 * @description Full version number of the API.
                 * @example 1.0.0
                 */
                "API-Version"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Tags"];
            };
        };
        /** @description Policies found. */
        PoliciesResponse: {
            headers: {
                /**
                 * @description Full version number of the API.
                 * @example 1.0.0
                 */
                "API-Version"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Policies"];
            };
        };
        /** @description Policy found, created, replaced or removed. */
        PolicyResponse: {
            headers: {
                /**
                 * @description Full version number of the API.
                 * @example 1.0.0
                 */
                "API-Version"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Policy"];
            };
        };
        /** @description Bad request. */
        BadRequest: {
            headers: {
                /**
                 * @description Full version number of the API.
                 * @example 1.0.0
                 */
                "API-Version"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Not authorized. */
        NotAuthorized: {
            headers: {
                /**
                 * @description Full version number of the API.
                 * @example 1.0.0
                 */
                "API-Version"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Access denied. */
        AccessDenied: {
            headers: {
                /**
                 * @description Full version number of the API.
                 * @example 1.0.0
                 */
                "API-Version"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource not found. */
        NotFound: {
            headers: {
                /**
                 * @description Full version number of the API.
                 * @example 1.0.0
                 */
                "API-Version"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource already exists. */
        AlreadyExists: {
            headers: {
                /**
                 * @description Full version number of the API.
                 * @example 1.0.0
                 */
                "API-Version"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Unexpected error. */
        UnexpectedError: {
            headers: {
                /**
                 * @description Full version number of the API.
                 * @example 1.0.0
                 */
                "API-Version"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /**
         * @description Unique identifier of a policy (UUID).
         * @example b4911124-e92a-482f-80b4-eb02383378ae
         */
        PolicyID: string;
        /**
         * @description Force upsert during a put/post operation.
         * @example true
         */
        ForceUpsert: boolean;
        /**
         * @description Ignore missing data during a delete operation.
         * @example true
         */
        IgnoreMissing: boolean;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "get-languages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["LanguagesResponse"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["NotAuthorized"];
            403: components["responses"]["AccessDenied"];
            "5XX": components["responses"]["UnexpectedError"];
        };
    };
    "get-tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["TagsResponse"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["NotAuthorized"];
            403: components["responses"]["AccessDenied"];
            "5XX": components["responses"]["UnexpectedError"];
        };
    };
    "get-policies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["PoliciesResponse"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["NotAuthorized"];
            403: components["responses"]["AccessDenied"];
            "5XX": components["responses"]["UnexpectedError"];
        };
    };
    "get-policy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Unique identifier of a policy (UUID).
                 * @example b4911124-e92a-482f-80b4-eb02383378ae
                 */
                id: components["parameters"]["PolicyID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["PolicyResponse"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["NotAuthorized"];
            403: components["responses"]["AccessDenied"];
            404: components["responses"]["NotFound"];
            "5XX": components["responses"]["UnexpectedError"];
        };
    };
    "update-policy": {
        parameters: {
            query?: {
                /**
                 * @description Force upsert during a put/post operation.
                 * @example true
                 */
                force?: components["parameters"]["ForceUpsert"];
            };
            header?: never;
            path: {
                /**
                 * @description Unique identifier of a policy (UUID).
                 * @example b4911124-e92a-482f-80b4-eb02383378ae
                 */
                id: components["parameters"]["PolicyID"];
            };
            cookie?: never;
        };
        /** @description Definition of the new policy. */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["Policy"];
            };
        };
        responses: {
            200: components["responses"]["PolicyResponse"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["NotAuthorized"];
            403: components["responses"]["AccessDenied"];
            404: components["responses"]["NotFound"];
            "5XX": components["responses"]["UnexpectedError"];
        };
    };
    "create-policy": {
        parameters: {
            query?: {
                /**
                 * @description Force upsert during a put/post operation.
                 * @example true
                 */
                force?: components["parameters"]["ForceUpsert"];
            };
            header?: never;
            path: {
                /**
                 * @description Unique identifier of a policy (UUID).
                 * @example b4911124-e92a-482f-80b4-eb02383378ae
                 */
                id: components["parameters"]["PolicyID"];
            };
            cookie?: never;
        };
        /** @description Definition of the new policy. */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["Policy"];
            };
        };
        responses: {
            201: components["responses"]["PolicyResponse"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["NotAuthorized"];
            403: components["responses"]["AccessDenied"];
            409: components["responses"]["AlreadyExists"];
            "5XX": components["responses"]["UnexpectedError"];
        };
    };
    "delete-policy": {
        parameters: {
            query?: {
                /**
                 * @description Ignore missing data during a delete operation.
                 * @example true
                 */
                force?: components["parameters"]["IgnoreMissing"];
            };
            header?: never;
            path: {
                /**
                 * @description Unique identifier of a policy (UUID).
                 * @example b4911124-e92a-482f-80b4-eb02383378ae
                 */
                id: components["parameters"]["PolicyID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["PolicyResponse"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["NotAuthorized"];
            403: components["responses"]["AccessDenied"];
            404: components["responses"]["NotFound"];
            "5XX": components["responses"]["UnexpectedError"];
        };
    };
    "status-policy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Unique identifier of a policy (UUID).
                 * @example b4911124-e92a-482f-80b4-eb02383378ae
                 */
                id: components["parameters"]["PolicyID"];
            };
            cookie?: never;
        };
        /** @description New status of the policy. */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PolicyStatus"];
            };
        };
        responses: {
            200: components["responses"]["PolicyResponse"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["NotAuthorized"];
            403: components["responses"]["AccessDenied"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["UnexpectedError"];
        };
    };
}
