/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/languages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve languages.
         * @description Endpoint to retrieve the list of supported policy languages.
         */
        get: operations["get-languages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve tags.
         * @description Endpoint to retrieve the list of tags.
         */
        get: operations["get-tags"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/policies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve policies.
         * @description Endpoint to retrieve all policy keys.
         */
        get: operations["get-policies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/policy/{language}/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Language of a policy. */
                language: components["parameters"]["PolicyLanguage"];
                /** @description Unique identifier of a policy. */
                id: components["parameters"]["PolicyID"];
            };
            cookie?: never;
        };
        /**
         * Retrieve policy.
         * @description Retrieve a specified cached policy.
         */
        get: operations["get-policy"];
        /**
         * Replace policy.
         * @description If the unique identifier of the policy does not exist, a 404 status code will be returned.
         *     You can override this behavior by passing the 'force' parameter in the query.
         *
         */
        put: operations["update-policy"];
        /**
         * Add policy.
         * @description If the unique identifier of the policy already exists, a 409 status code will be returned.
         *     You can override this behavior by passing the 'force' parameter in the query.
         *
         */
        post: operations["create-policy"];
        /**
         * Remove policy.
         * @description If the unique identifier of the policy does not exist, a 404 status code will be returned.
         *     You can override this behavior by passing the 'force' parameter in the query.
         *
         */
        delete: operations["delete-policy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description The metadata associated with a policy. */
        Metadata: {
            /** @description The title of the policy. E.g., a short description. */
            title?: string;
            /** @description Detailed description of the policy. */
            description?: string;
            /** @description The unique identifier of the Register van Verwerkings-Activiteiten (RvVA).
             *     Only required when the policy is linked directly with an item in the RvVA.
             *     The value is considered as one of the tags of the policy.
             *      */
            rvvaId?: string;
            /** @description Link to the policy. Required when the policy is stored externally. */
            url?: string;
            /** @description List of tags the policy is annotated with.
             *
             *     This is used to determine which PDP (or set of PDPs) objects can be pushed to.
             *      */
            tags?: string[];
            /** @description Timestamp the policy was created (RFC3339 format). */
            createDate?: string;
            /** @description User that created the policy. */
            createUser?: string;
            /** @description Timestamp the policy was last updated (RFC3339 format). */
            updateDate?: string;
            /** @description User that last updated the policy. */
            updateUser?: string;
        };
        /** @description Metadata about how and where the policy is used. */
        UsageData: {
            /** @description Bundles the policy is used by. */
            bundles?: string[];
        };
        /** @description Metadata about how, when and by whom an object has been manipulated. */
        AuditEntry: {
            /** @description Timestamp of the log entry in RFC3339 format. */
            timestamp?: string;
            /** @description Operation performed on the object. Any of ["CREATE", "UPDATE", "DELETE"]. */
            operation?: string;
            /** @description Unique identifier of the user who operated on the object. */
            user?: string;
        };
        Languages: components["schemas"]["Language"][];
        /** @description The details of a policy language. */
        Language: {
            /** @description The unique identifier of the policy language. */
            id?: string;
            /** @description Name of the policy language in human-readable form. */
            name?: string;
        };
        Tags: components["schemas"]["Tag"][];
        /** @description The details of a tag. */
        Tag: {
            /** @description The unique identifier of the tag. */
            id?: string;
            /** @description Name of the tag in human-readable form. */
            name?: string;
            /** @description Detailed description of the tag. */
            description?: string;
            /** @description Timestamp the tag was created (RFC3339 format). */
            createDate?: string;
            /** @description User that created the tag. */
            createUser?: string;
            /** @description Timestamp the tag was last updated (RFC3339 format). */
            updateDate?: string;
            /** @description User that last updated the tag. */
            updateUser?: string;
            /** @description Audit log for the tag. */
            auditLog?: components["schemas"]["AuditEntry"][];
        };
        Policies: components["schemas"]["Policy"][];
        /** @description The content of a policy. */
        Policy: {
            /** @description The unique identifier of the policy. */
            id: string;
            /** @description The language of the policy.
             *     The value is case-insensitive.
             *     The value is considered as one of the tags of the policy.
             *
             *     Supported values:
             *     - "opa/rego"; alternatives: "opa", "rego", "opa-rego".
             *     - "cedar".
             *     - "cerbos/cel"; alternatives: "cerbos", "cel", "cerbos-cel".
             *     - "openfga"; alternative: "open-fga".
             *      */
            language: string;
            /** @description Content of the policy. Required when the policy is stored internally. */
            data?: string;
            metadata?: components["schemas"]["Metadata"];
            usageData?: components["schemas"]["UsageData"];
            /** @description Audit log for the policy. */
            auditLog?: components["schemas"]["AuditEntry"][];
        };
        /** @description The response for an error (as defined by RFC9457). */
        Error: {
            /**
             * Format: uri
             * @description Identification of the problem.
             */
            type?: string;
            /** @description Status code of the problem. */
            status?: number;
            /** @description Summary of the problem. */
            title?: string;
            /** @description Detailed description of the problem. */
            detail?: string;
            /**
             * Format: uri
             * @description Identification of the problem instance.
             */
            instance?: string;
        };
    };
    responses: {
        /** @description Languages found. */
        LanguagesResponse: {
            headers: {
                /** @description Full version number of the API. */
                "API-Version"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Languages"];
            };
        };
        /** @description Tags found. */
        TagsResponse: {
            headers: {
                /** @description Full version number of the API. */
                "API-Version"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Tags"];
            };
        };
        /** @description Policies found. */
        PoliciesResponse: {
            headers: {
                /** @description Full version number of the API. */
                "API-Version"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Policies"];
            };
        };
        /** @description Policy found, created, replaced or removed. */
        PolicyResponse: {
            headers: {
                /** @description Full version number of the API. */
                "API-Version"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Policy"];
            };
        };
        /** @description Bad request. */
        BadRequest: {
            headers: {
                /** @description Full version number of the API. */
                "API-Version"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Not authorized. */
        NotAuthorized: {
            headers: {
                /** @description Full version number of the API. */
                "API-Version"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Access denied. */
        AccessDenied: {
            headers: {
                /** @description Full version number of the API. */
                "API-Version"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource not found. */
        NotFound: {
            headers: {
                /** @description Full version number of the API. */
                "API-Version"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource already exists. */
        AlreadyExists: {
            headers: {
                /** @description Full version number of the API. */
                "API-Version"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Unexpected error. */
        UnexpectedError: {
            headers: {
                /** @description Full version number of the API. */
                "API-Version"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description Language of a policy. */
        PolicyLanguage: string;
        /** @description Unique identifier of a policy. */
        PolicyID: string;
        /** @description Force upsert during a put/post operation. */
        ForceUpsert: boolean;
        /** @description Ignore missing data during a delete operation. */
        IgnoreMissing: boolean;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "get-languages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["LanguagesResponse"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["NotAuthorized"];
            403: components["responses"]["AccessDenied"];
            "5XX": components["responses"]["UnexpectedError"];
        };
    };
    "get-tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["TagsResponse"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["NotAuthorized"];
            403: components["responses"]["AccessDenied"];
            "5XX": components["responses"]["UnexpectedError"];
        };
    };
    "get-policies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["PoliciesResponse"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["NotAuthorized"];
            403: components["responses"]["AccessDenied"];
            "5XX": components["responses"]["UnexpectedError"];
        };
    };
    "get-policy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Language of a policy. */
                language: components["parameters"]["PolicyLanguage"];
                /** @description Unique identifier of a policy. */
                id: components["parameters"]["PolicyID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["PolicyResponse"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["NotAuthorized"];
            403: components["responses"]["AccessDenied"];
            404: components["responses"]["NotFound"];
            "5XX": components["responses"]["UnexpectedError"];
        };
    };
    "update-policy": {
        parameters: {
            query?: {
                /** @description Force upsert during a put/post operation. */
                force?: components["parameters"]["ForceUpsert"];
            };
            header?: never;
            path: {
                /** @description Language of a policy. */
                language: components["parameters"]["PolicyLanguage"];
                /** @description Unique identifier of a policy. */
                id: components["parameters"]["PolicyID"];
            };
            cookie?: never;
        };
        /** @description Definition of the new policy. */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["Policy"];
            };
        };
        responses: {
            200: components["responses"]["PolicyResponse"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["NotAuthorized"];
            403: components["responses"]["AccessDenied"];
            404: components["responses"]["NotFound"];
            "5XX": components["responses"]["UnexpectedError"];
        };
    };
    "create-policy": {
        parameters: {
            query?: {
                /** @description Force upsert during a put/post operation. */
                force?: components["parameters"]["ForceUpsert"];
            };
            header?: never;
            path: {
                /** @description Language of a policy. */
                language: components["parameters"]["PolicyLanguage"];
                /** @description Unique identifier of a policy. */
                id: components["parameters"]["PolicyID"];
            };
            cookie?: never;
        };
        /** @description Definition of the new policy. */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["Policy"];
            };
        };
        responses: {
            201: components["responses"]["PolicyResponse"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["NotAuthorized"];
            403: components["responses"]["AccessDenied"];
            409: components["responses"]["AlreadyExists"];
            "5XX": components["responses"]["UnexpectedError"];
        };
    };
    "delete-policy": {
        parameters: {
            query?: {
                /** @description Ignore missing data during a delete operation. */
                force?: components["parameters"]["IgnoreMissing"];
            };
            header?: never;
            path: {
                /** @description Language of a policy. */
                language: components["parameters"]["PolicyLanguage"];
                /** @description Unique identifier of a policy. */
                id: components["parameters"]["PolicyID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["PolicyResponse"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["NotAuthorized"];
            403: components["responses"]["AccessDenied"];
            404: components["responses"]["NotFound"];
            "5XX": components["responses"]["UnexpectedError"];
        };
    };
}
