/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/policies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve policies.
         * @description Endpoint to retrieve all policy keys.
         */
        get: operations["get-policies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/policy/{language}/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Language of a policy. */
                language: components["parameters"]["PolicyLanguage"];
                /** @description Unique identifier of a policy. */
                id: components["parameters"]["PolicyID"];
            };
            cookie?: never;
        };
        /**
         * Retrieve policy.
         * @description Retrieve a specified cached policy.
         */
        get: operations["get-policy"];
        /**
         * Replace policy.
         * @description If the unique identifier of the policy does not exist, a 404 status code will be returned.
         *     You can override this behavior by passing the 'force' parameter in the query.
         *
         */
        put: operations["replace-policy"];
        /**
         * Add policy.
         * @description If the unique identifier of the policy already exists, a 409 status code will be returned.
         *     You can override this behavior by passing the 'force' parameter in the query.
         *
         */
        post: operations["add-policy"];
        /**
         * Remove policy.
         * @description If the unique identifier of the policy does not exist, a 404 status code will be returned.
         *     You can override this behavior by passing the 'force' parameter in the query.
         *
         */
        delete: operations["delete-policy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description The content of a policy. */
        Policy: {
            /** @description The unique identifier of the policy. */
            id: string;
            /** @description The language of the policy.
             *     The value is case-insensitive.
             *
             *     Supported values:
             *     - "opa/rego"; alternatives: "opa", "rego", "opa-rego".
             *     - "cedar".
             *     - "cerbos/cel"; alternatives: "cerbos", "cel", "cerbos-cel".
             *     - "openfga"; alternative: "open-fga".
             *      */
            language: string;
            /** @description The unique identifier of the Register van Verwerkings-Activiteiten (RvVA).
             *     Required when the policy is linked 1-on-1 with an item in the RvVA.
             *      */
            rvvaId?: string;
            /** @description Link to the policy. Required when the policy is stored externally. */
            url?: string;
            /** @description Content of the policy. Required when the policy is stored internally. */
            data?: string;
        };
        PoliciesResponse: components["schemas"]["Policy"][];
        PolicyResponse: components["schemas"]["Policy"];
        /** @description The response for an error (as defined by RFC9457). */
        ErrorResponse: {
            /**
             * Format: uri
             * @description Identification of the problem.
             */
            type?: string;
            /** @description Status code of the problem. */
            status?: number;
            /** @description Summary of the problem. */
            title?: string;
            /** @description Detailed description of the problem. */
            detail?: string;
            /**
             * Format: uri
             * @description Identification of the problem instance.
             */
            instance?: string;
        };
    };
    responses: {
        /** @description Bad request. */
        BadRequest: {
            headers: {
                /** @description Full version number of the API. */
                "API-Version"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Not authorized. */
        NotAuthorized: {
            headers: {
                /** @description Full version number of the API. */
                "API-Version"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Access denied. */
        AccessDenied: {
            headers: {
                /** @description Full version number of the API. */
                "API-Version"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource not found. */
        NotFound: {
            headers: {
                /** @description Full version number of the API. */
                "API-Version"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource already exists. */
        AlreadyExists: {
            headers: {
                /** @description Full version number of the API. */
                "API-Version"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Unexpected error. */
        UnexpectedError: {
            headers: {
                /** @description Full version number of the API. */
                "API-Version"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /** @description Language of a policy. */
        PolicyLanguage: string;
        /** @description Unique identifier of a policy. */
        PolicyID: string;
        /** @description Force upsert during a put/post operation. */
        ForceUpsert: boolean;
        /** @description Ignore missing data during a delete operation. */
        IgnoreMissing: boolean;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "get-policies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Policies found. */
            200: {
                headers: {
                    /** @description Full version number of the API. */
                    "API-Version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PoliciesResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["NotAuthorized"];
            403: components["responses"]["AccessDenied"];
            "5XX": components["responses"]["UnexpectedError"];
        };
    };
    "get-policy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Language of a policy. */
                language: components["parameters"]["PolicyLanguage"];
                /** @description Unique identifier of a policy. */
                id: components["parameters"]["PolicyID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Policy found. */
            200: {
                headers: {
                    /** @description Full version number of the API. */
                    "API-Version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["NotAuthorized"];
            403: components["responses"]["AccessDenied"];
            404: components["responses"]["NotFound"];
            "5XX": components["responses"]["UnexpectedError"];
        };
    };
    "replace-policy": {
        parameters: {
            query?: {
                /** @description Force upsert during a put/post operation. */
                force?: components["parameters"]["ForceUpsert"];
            };
            header?: never;
            path: {
                /** @description Language of a policy. */
                language: components["parameters"]["PolicyLanguage"];
                /** @description Unique identifier of a policy. */
                id: components["parameters"]["PolicyID"];
            };
            cookie?: never;
        };
        /** @description Definition of the new policy. */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["Policy"];
            };
        };
        responses: {
            /** @description Policy replaced. */
            200: {
                headers: {
                    /** @description Full version number of the API. */
                    "API-Version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["NotAuthorized"];
            403: components["responses"]["AccessDenied"];
            404: components["responses"]["NotFound"];
            "5XX": components["responses"]["UnexpectedError"];
        };
    };
    "add-policy": {
        parameters: {
            query?: {
                /** @description Force upsert during a put/post operation. */
                force?: components["parameters"]["ForceUpsert"];
            };
            header?: never;
            path: {
                /** @description Language of a policy. */
                language: components["parameters"]["PolicyLanguage"];
                /** @description Unique identifier of a policy. */
                id: components["parameters"]["PolicyID"];
            };
            cookie?: never;
        };
        /** @description Definition of the new policy. */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["Policy"];
            };
        };
        responses: {
            /** @description Policy created. */
            201: {
                headers: {
                    /** @description Full version number of the API. */
                    "API-Version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["NotAuthorized"];
            403: components["responses"]["AccessDenied"];
            409: components["responses"]["AlreadyExists"];
            "5XX": components["responses"]["UnexpectedError"];
        };
    };
    "delete-policy": {
        parameters: {
            query?: {
                /** @description Ignore missing data during a delete operation. */
                force?: components["parameters"]["IgnoreMissing"];
            };
            header?: never;
            path: {
                /** @description Language of a policy. */
                language: components["parameters"]["PolicyLanguage"];
                /** @description Unique identifier of a policy. */
                id: components["parameters"]["PolicyID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Policy removed. */
            200: {
                headers: {
                    /** @description Full version number of the API. */
                    "API-Version"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["NotAuthorized"];
            403: components["responses"]["AccessDenied"];
            404: components["responses"]["NotFound"];
            "5XX": components["responses"]["UnexpectedError"];
        };
    };
}
