/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve settings.
         * @description Retrieve the manager ui settings.
         *
         *     If no settings have been saved yet, the current default values are returned.
         */
        get: operations["get-settings"];
        /**
         * Replace settings.
         * @description Replace the manager ui settings.
         */
        put: operations["update-settings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description The manager ui settings. */
        Settings: {
            /**
             * @description Header title.
             * @example OpenFTV beheeromgeving
             */
            headerTitle: string;
            /**
             * @description Background color of the header, as a hex color code.
             * @example #F7E8E8
             */
            headerColor: string;
            /**
             * @description Text color of the header title, as a hex color code.
             * @example #000000
             */
            titleColor: string;
            /**
             * Format: byte
             * @description Logo shown on the left side of the header, base64-encoded. Omit or leave empty to remove the logo.
             */
            logo?: string;
            /**
             * @description Media type of the logo, required if logo is set.
             * @enum {string}
             */
            logoMediaType?: "image/png" | "image/jpeg" | "image/svg+xml" | "image/webp";
            /**
             * @description Timestamp the settings were last updated (RFC3339 format).
             * @example 2025-08-15T07:53:41.493415Z
             */
            readonly updated?: string;
            /**
             * @description User that last updated the settings.
             * @example alice@wonderland.cc
             */
            readonly updatedBy?: string;
        };
        Error: components["schemas"]["ErrorResponse"];
        /** @description Error code that clients can use to look up their own localized message. An OpenFTV extension. */
        ErrorCode: string;
        /** @description Error response model (as defined by RFC9457). */
        ErrorResponse: {
            /**
             * Format: uri
             * @description Identification of the problem.
             */
            type?: string;
            /** @description Status code of the problem. */
            status?: number;
            /** @description Summary of the problem. */
            title?: string;
            /** @description Detailed description of the problem. */
            detail?: string;
            /**
             * Format: uri
             * @description Identification of the problem instance.
             */
            instance?: string;
            code?: components["schemas"]["ErrorCode"];
        };
    };
    responses: {
        /** @description Settings found or saved. */
        SettingsResponse: {
            headers: {
                /**
                 * @description Full version number of the API.
                 * @example 1.0.0
                 */
                "API-Version"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Settings"];
            };
        };
        /** @description Bad request. */
        BadRequest: {
            headers: {
                /**
                 * @description Full version number of the API.
                 * @example 1.0.0
                 */
                "API-Version"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Not authorized. */
        NotAuthorized: {
            headers: {
                /**
                 * @description Full version number of the API.
                 * @example 1.0.0
                 */
                "API-Version"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Access denied. */
        AccessDenied: {
            headers: {
                /**
                 * @description Full version number of the API.
                 * @example 1.0.0
                 */
                "API-Version"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Unexpected error. */
        UnexpectedError: {
            headers: {
                /**
                 * @description Full version number of the API.
                 * @example 1.0.0
                 */
                "API-Version"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "get-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["SettingsResponse"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["NotAuthorized"];
            403: components["responses"]["AccessDenied"];
            "5XX": components["responses"]["UnexpectedError"];
        };
    };
    "update-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description New ui settings. */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["Settings"];
            };
        };
        responses: {
            200: components["responses"]["SettingsResponse"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["NotAuthorized"];
            403: components["responses"]["AccessDenied"];
            "5XX": components["responses"]["UnexpectedError"];
        };
    };
}
