services:
  pip:
    build:
      context: ../
      dockerfile: ./apps/pip/Dockerfile
    container_name: openftv-pip
    ports:
      - "9000:8443"
    depends_on:
      - db
    environment:
      - PIP_PERSIST_TYPE=postgres
      - PIP_PERSIST_POSTGRES_URL=postgres://user:password@db:5432/openftv_pip?sslmode=disable
      - PIP_PERSIST_PREFIX=local
      - PIP_PERSIST_POSTGRES_TABLE=kv
      - PIP_AUTHENTICATION_TYPE=none
    networks:
      - openftv
  pap:
    build:
      context: ../
      dockerfile: ./apps/pap/Dockerfile
    container_name: openftv-pap
    ports:
      - "9001:8443"
    depends_on:
      - db
    environment:
      - PAP_PERSIST_TYPE=postgres
      - PAP_PERSIST_POSTGRES_URL=postgres://user:password@db:5432/openftv_pap?sslmode=disable
      - PAP_PERSIST_PREFIX=local
      - PAP_PERSIST_POSTGRES_TABLE=kv
      - PAP_AUTHENTICATION_TYPE=none
      - PAP_POLICIES_STORE=testdata/policies/cedar/pap
    networks:
      - openftv
  frontend:
    build:
      context: ../
      dockerfile: ./apps/management-interface/Dockerfile
    container_name: openftv-management-ui
    ports:
      - "8080:80"
    depends_on:
      - pip
      - pap
    networks:
      - openftv
  db:
    image: postgres:15
    container_name: openftv-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5400:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./../scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    networks:
      - openftv

volumes:
  postgres-data:

networks:
  openftv:
    driver: bridge