services:
  vlierdam-db:
    image: postgres:15
    container_name: openftv-vlierdam-db
    ports:
      - "5400:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./../scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 4s
      timeout: 10s
      retries: 5
      start_period: 2s
    networks:
      - openftv

  vlierdam-dataspace:
    build:
      context: ../
      dockerfile: ./mock/datasources/generic/Dockerfile
    container_name: openftv-vlierdam-dataspace
    ports:
      - "9010:8443"
    environment:
      - GEN_DS_DATA_PATH=/tmp/data
    volumes:
      - ./../testdata/apps/gemeente-vlierdam/dataspace:/tmp/data
    networks:
      - openftv

  vlierdam-manager:
    build:
      context: ../
      dockerfile: ./apps/manager/Dockerfile
    container_name: openftv-vlierdam-manager
    ports:
      - "9000:8443"
    environment:
      - MANAGER_PERSIST_TYPE=postgres             # persistent storage for the managed policies and data.
      - MANAGER_PERSIST_POSTGRES_URL=postgres://user:password@vlierdam-db:5432/openftv?sslmode=disable
      - MANAGER_MIGRATE_AUTO=true                 # migration setup for the persistent storage.
      - MANAGER_MIGRATE_SOURCE=*embed*
      - MANAGER_POLICIES_LANGUAGE=cedar           # default policy language.
      - MANAGER_POLICIES_STORE=/tmp/data/policies # local policies to evaluate access by the management-interface.
      - MANAGER_POLICIES_STORE_RECURSE=true
      - MANAGER_PIP_STORE=/tmp/data/data          # local (design-time) data used by local policies.
      - MANAGER_PIP_STORE_RECURSE=true
      - MANAGER_TAGS_PATH=/tmp/data/tags          # tags for the managed policies and data.
      - MANAGER_AUTHENTICATION_TYPE=none          # local authentication type.
      - MANAGER_BUNDLE_CONFIGS=/tmp/data/bundles  # bundle management for PDPs.
      - MANAGER_BUNDLE_RECURSE=true
      - MANAGER_BUNDLE_SEND_TIMEOUT=60s
      - MANAGER_ADL_TYPE=postgresql
      - MANAGER_ADL_SERVICE_NAME=vlierdam
      - MANAGER_ADL_PG_URL=postgres://user:password@vlierdam-db:5432/openftv_adl?sslmode=disable
      - PDP_ADL_TYPE=postgresql
      - PDP_ADL_SERVICE_NAME=vlierdam
      - PDP_ADL_PG_URL=postgres://user:password@vlierdam-db:5432/openftv?sslmode=disable
    depends_on:
      vlierdam-db:
        condition: service_healthy
    volumes:
      - ./../testdata/apps/gemeente-vlierdam/manager:/tmp/data
    networks:
      - openftv
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8443/healthz"]
      interval: 4s
      timeout: 10s
      retries: 5
      start_period: 2s

  vlierdam-pdp1:
    build:
      context: ../
      dockerfile: ./apps/pdp/Dockerfile
    container_name: openftv-vlierdam-pdp1
    ports:
      - "9004:8443"
    environment:
      - PDP_BUNDLE_MANAGER=http://vlierdam-manager:8443/v1/bundle/pdp1  # bundle retrieval.
      - PDP_BUNDLE_ENCODING=bzip2
      - PDP_BUNDLE_TIMEOUT=30s
      - PDP_BUNDLE_RETRIES=5
      - PDP_POLICIES_LANGUAGE=cedar                                     # policy language.
      - PDP_PIP_PULL_CONFIGS=/tmp/data/pull-config/config.yaml          # runtime data retrieval.
      - PDP_ADL_TYPE=postgresql
      - PDP_ADL_SERVICE_NAME=vlierdam
      - PDP_ADL_PG_URL=postgres://user:password@vlierdam-db:5432/openftv_adl?sslmode=disable
      - PDP_MIGRATE_AUTO=true
      - PDP_MIGRATE_SOURCE=*embed*
    depends_on:
      vlierdam-manager:
        condition: service_healthy
    volumes:
      - ./../testdata/apps/gemeente-vlierdam/pdp1:/tmp/data
    networks:
      - openftv
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8443/livez"]
      interval: 4s
      timeout: 10s
      retries: 5
      start_period: 2s

  vlierdam-frontend:
    build:
      context: ../
      dockerfile: ./apps/management-interface/Dockerfile
    container_name: openftv-vlierdam-frontend
    environment:
      VITE_PAP_BASE_URL: "http://localhost:9000"
      VITE_PIP_BASE_URL: "http://localhost:9000"
    ports:
      - "8080:80"
    depends_on:
      vlierdam-manager:
        condition: service_healthy
    networks:
      - openftv

volumes:
  postgres-data:

networks:
  openftv:
    driver: bridge
