networks:
  openfga:

services:
  openfga-db:
    image: postgres:17
    container_name: openfga-db
    networks:
      - openfga
    ports:
      - "5500:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  openfga-migrate:
    depends_on:
      openfga-db:
        condition: service_healthy
    image: openfga/openfga:latest
    container_name: openfga-migrate
    command: migrate
    environment:
      - OPENFGA_DATASTORE_ENGINE=postgres
      - OPENFGA_DATASTORE_URI=postgres://user:password@openfga-db:5432/postgres?sslmode=disable
    networks:
      - openfga

  openfga-service:
    depends_on:
      openfga-migrate:
        condition: service_completed_successfully
    image: openfga/openfga:latest
    container_name: openfga-service
    environment:
      - OPENFGA_DATASTORE_ENGINE=postgres
      - OPENFGA_DATASTORE_URI=postgres://user:password@openfga-db:5432/postgres?sslmode=disable
      - OPENFGA_LOG_FORMAT=json
    command: run
    networks:
      - openfga
    ports:
      - "8080:8080"
      - "8081:8081"
      - "3000:3000"
