// Package authzen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package authzen

// Action The action associated with an authorization request.
type Action struct {
	// Name The name of the action.
	Name string `json:"name,omitempty"`

	// Properties Optional attributes for the action.
	Properties map[string]any `json:"properties,omitempty"`
}

// AuthorizationRequest Authorization request model.
type AuthorizationRequest struct {
	// Action The action associated with an authorization request.
	Action Action `json:"action"`

	// Context Optional context of the request.
	Context map[string]any `json:"context,omitempty"`

	// Resource The entity associated with an authorization request.
	// This can be the subject (e.g. principal) or the resource.
	Resource Entity `json:"resource"`

	// Subject The entity associated with an authorization request.
	// This can be the subject (e.g. principal) or the resource.
	Subject Entity `json:"subject"`
}

// AuthorizationResponse Authorization response model.
type AuthorizationResponse struct {
	// Context Optional context returned by the policy engine.
	Context map[string]any `json:"context,omitempty"`

	// Decision true if the request is authorized.
	Decision bool `json:"decision"`
}

// Entity The entity associated with an authorization request.
// This can be the subject (e.g. principal) or the resource.
type Entity struct {
	// Id The unique ID of the entity.
	Id string `json:"id"`

	// Properties Optional attributes for the entity.
	Properties map[string]any `json:"properties,omitempty"`

	// Type The type of the entity.
	Type string `json:"type"`
}

// ErrorResponse Error response model (as defined by RFC9457).
type ErrorResponse struct {
	// Detail Detailed description of the problem.
	Detail string `json:"detail,omitempty"`

	// Instance Identification of the problem instance.
	Instance string `json:"instance,omitempty"`

	// Status Status code of the problem.
	Status *int `json:"status,omitempty"`

	// Title Summary of the problem.
	Title string `json:"title,omitempty"`

	// Type Identification of the problem.
	Type string `json:"type,omitempty"`
}

// PoliciesResponse A set of policies.
type PoliciesResponse = []Policy

// Policy The content of a policy.
type Policy struct {
	// Id The unique identifier of the policy.
	Id string `json:"id"`

	// Language The language of the policy.
	Language string `json:"language"`

	// RvvaId The unique identifier of the Register of Activities (RvVA).
	RvvaId string `json:"rvvaId,omitempty"`

	// Source The unique identifier of the source.
	Source string `json:"source,omitempty"`

	// Target The unique identifier of the target.
	Target string `json:"target,omitempty"`

	// Url Link to the actual policy.
	Url string `json:"url"`
}

// PolicyResponse The content of a policy.
type PolicyResponse = Policy

// ReasonField Map of one or more reasons, with a language-identifier as the key.
type ReasonField = map[string]any

// ReasonObject Specifies a particular reason.
type ReasonObject struct {
	// Id Unique identifier of the reason.
	Id string `json:"id"`

	// ReasonAdmin Map of one or more reasons, with a language-identifier as the key.
	ReasonAdmin ReasonField `json:"reasonAdmin,omitempty"`

	// ReasonUser Map of one or more reasons, with a language-identifier as the key.
	ReasonUser ReasonField `json:"reasonUser,omitempty"`
}

// PolicyID defines model for PolicyID.
type PolicyID = string

// AccessDenied Error response model (as defined by RFC9457).
type AccessDenied = ErrorResponse

// AlreadyExists Error response model (as defined by RFC9457).
type AlreadyExists = ErrorResponse

// BadRequest Error response model (as defined by RFC9457).
type BadRequest = ErrorResponse

// NotAuthorized Error response model (as defined by RFC9457).
type NotAuthorized = ErrorResponse

// NotFound Error response model (as defined by RFC9457).
type NotFound = ErrorResponse

// UnexpectedError Error response model (as defined by RFC9457).
type UnexpectedError = ErrorResponse

// AuthRequestParams defines parameters for AuthRequest.
type AuthRequestParams struct {
	// Authorization Request header containing the credentials to authenticate the client (PEP) to the authentication service (PDP).
	Authorization string `json:"Authorization,omitempty"`

	// XRequestID Request header containing the unique ID of the request.
	// This will be returned in the response.
	XRequestID string `json:"X-Request-ID,omitempty"`
}

// AuthRequestJSONRequestBody defines body for AuthRequest for application/json ContentType.
type AuthRequestJSONRequestBody = AuthorizationRequest

// ReplacePolicyJSONRequestBody defines body for ReplacePolicy for application/json ContentType.
type ReplacePolicyJSONRequestBody = Policy

// AddPolicyJSONRequestBody defines body for AddPolicy for application/json ContentType.
type AddPolicyJSONRequestBody = Policy
