// Package authzen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package authzen

import (
	"encoding/json"
	"fmt"

	apierrors "gitlab.com/digilab.overheid.nl/ecosystem/ftv/open-ftv/oas/errors"
)

// Action The action associated with an authorization request.
type Action struct {
	// Name The name of the action.
	Name string `json:"name"`

	// Properties Optional attributes for the action.
	Properties map[string]interface{} `json:"properties,omitempty"`
}

// Entity The entity associated with an authorization request.
// This can be the subject (e.g. principal) or the resource.
type Entity struct {
	// Id The unique ID of the entity.
	Id string `json:"id"`

	// Properties Optional attributes for the entity.
	Properties map[string]interface{} `json:"properties,omitempty"`

	// Type The type of the entity.
	Type string `json:"type"`
}

// ErrorResponse Error response model (as defined by RFC9457).
type ErrorResponse = apierrors.ErrorResponse

// EvaluationDecision Evaluation decision model.
type EvaluationDecision struct {
	// Context Specifies a particular reason.
	//
	// Besides the properties below, the object carries the constraints the policy published beside
	// its decision, as free-form key/value pairs. The PDP passes them through verbatim and never
	// interprets them: their shape is a contract between the policy author and the caller. Callers
	// use them to narrow a query that the boolean decision on its own cannot express.
	//
	// Only the Rego controller fills these in, from a `context` rule in the decision package. The
	// other policy languages have no way to publish JSON alongside a decision, and always omit them.
	Context ReasonObject `json:"context,omitempty"`

	// Decision true if the request is authorized.
	Decision bool `json:"decision"`
}

// EvaluationObject Evaluation object model.
type EvaluationObject struct {
	// Action The action associated with an authorization request.
	Action Action `json:"action"`

	// Context Optional context of the request.
	Context map[string]interface{} `json:"context,omitempty"`

	// Resource The entity associated with an authorization request.
	// This can be the subject (e.g. principal) or the resource.
	Resource Entity `json:"resource"`

	// Subject The entity associated with an authorization request.
	// This can be the subject (e.g. principal) or the resource.
	Subject Entity `json:"subject"`
}

// EvaluationsDecision Evaluations decision model.
type EvaluationsDecision struct {
	// Evaluations List of evaluation decisions.
	Evaluations []EvaluationDecision `json:"evaluations"`
}

// EvaluationsObject Evaluations object model.
type EvaluationsObject struct {
	// Action The action associated with an authorization request.
	Action Action `json:"action,omitempty"`

	// Context Optional default context of the request.
	Context map[string]interface{} `json:"context,omitempty"`

	// Evaluations list of evaluation requests to test.
	Evaluations []EvaluationObject `json:"evaluations"`

	// Options Options for the evaluations request.
	Options struct {
		// EvaluationSemantics By default, every request in the evaluations array is executed and a response returned in the same array order.
		// This is the most common use-case for boxcarring multiple evaluation requests in a single payload.
		//
		// To select the desired evaluations semantic, use exactly one of the following values:
		//   - execute_all = default.
		//   - deny_on_first_deny = halt processing after first deny.
		//   - permit_on_first_permit = halt processing after first allow.
		EvaluationSemantics string `json:"evaluation_semantics,omitempty"`
	} `json:"options,omitempty"`

	// Resource The entity associated with an authorization request.
	// This can be the subject (e.g. principal) or the resource.
	Resource Entity `json:"resource,omitempty"`

	// Subject The entity associated with an authorization request.
	// This can be the subject (e.g. principal) or the resource.
	Subject Entity `json:"subject,omitempty"`
}

// MetadataObject Metadata model.
type MetadataObject struct {
	// AccessEvaluationEndpoint URL to AuthZEN compatible evaluation endpoint.
	AccessEvaluationEndpoint string `json:"access_evaluation_endpoint"`

	// AccessEvaluationsEndpoint URL to AuthZEN compatible evaluations endpoint.
	AccessEvaluationsEndpoint string `json:"access_evaluations_endpoint,omitempty"`

	// Capabilities list of registered IANA URNs referencing PDP specific capabilities.
	Capabilities []string `json:"capabilities,omitempty"`

	// PolicyDecisionPoint Base URL of the PDP. Must match with the base URL used to retrieve the metadata.
	PolicyDecisionPoint string `json:"policy_decision_point"`

	// SearchActionEndpoint URL to AuthZEN action search endpoint.
	SearchActionEndpoint string `json:"search_action_endpoint,omitempty"`

	// SearchResourceEndpoint URL to AuthZEN compatible resource search endpoint.
	SearchResourceEndpoint string `json:"search_resource_endpoint,omitempty"`

	// SearchSubjectEndpoint URL to AuthZEN compatible subject search endpoint.
	SearchSubjectEndpoint string `json:"search_subject_endpoint,omitempty"`

	// SignedMetadata JWT containing metadata parameters about the endpoints as claims.
	SignedMetadata string `json:"signed_metadata,omitempty"`
}

// PageRequest Pagination options.
type PageRequest struct {
	// Limit Maximum number of results to return.
	Limit int `json:"limit,omitempty"`

	// Properties Implementation-specific pagination request attributes.
	Properties map[string]interface{} `json:"properties,omitempty"`

	// Token Token used for pagination.
	Token string `json:"token,omitempty"`
}

// PageResponse Pagination options.
type PageResponse struct {
	// Count Number of results returned.
	Count int `json:"count,omitempty"`

	// NextToken Token used for pagination.
	NextToken string `json:"next_token,omitempty"`

	// Properties Implementation-specific pagination response attributes.
	Properties map[string]interface{} `json:"properties,omitempty"`

	// Total Total number of results available.
	Total int `json:"total,omitempty"`
}

// ReasonField Map of one or more reasons, with a language-identifier as the key.
type ReasonField = map[string]interface{}

// ReasonObject Specifies a particular reason.
//
// Besides the properties below, the object carries the constraints the policy published beside
// its decision, as free-form key/value pairs. The PDP passes them through verbatim and never
// interprets them: their shape is a contract between the policy author and the caller. Callers
// use them to narrow a query that the boolean decision on its own cannot express.
//
// Only the Rego controller fills these in, from a `context` rule in the decision package. The
// other policy languages have no way to publish JSON alongside a decision, and always omit them.
type ReasonObject struct {
	// Id Identifies the reason for this response, within the scope of this response.
	Id string `json:"id"`

	// ReasonAdmin Map of one or more reasons, with a language-identifier as the key.
	ReasonAdmin map[string]interface{} `json:"reason_admin,omitempty"`

	// ReasonUser Map of one or more reasons, with a language-identifier as the key.
	ReasonUser           map[string]interface{} `json:"reason_user,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// SearchActionObject Search action object model.
type SearchActionObject struct {
	// Context Optional context of the request.
	Context map[string]interface{} `json:"context,omitempty"`

	// Page Pagination options.
	Page PageRequest `json:"page,omitempty"`

	// Resource The entity associated with an authorization request.
	// This can be the subject (e.g. principal) or the resource.
	Resource Entity `json:"resource"`

	// Subject The entity associated with an authorization request.
	// This can be the subject (e.g. principal) or the resource.
	Subject Entity `json:"subject"`
}

// SearchActionResult Search action result model.
type SearchActionResult struct {
	// Name The name of the action.
	Name string `json:"name,omitempty"`
}

// SearchActionResults Search action results model.
type SearchActionResults struct {
	// Page Pagination options.
	Page PageResponse `json:"page,omitempty"`

	// Results List of action search results.
	Results []SearchActionResult `json:"results"`
}

// SearchEntity An entity (subject or resource) associated with a search request.
// This means the id can be empty.
type SearchEntity struct {
	// Id The unique ID of the search entity.
	Id string `json:"id,omitempty"`

	// Properties Optional attributes for the search entity.
	Properties map[string]interface{} `json:"properties,omitempty"`

	// Type The type of the search entity.
	Type string `json:"type"`
}

// SearchObject Search object model.
type SearchObject struct {
	// Action The action associated with an authorization request.
	Action Action `json:"action"`

	// Context Optional context of the request.
	Context map[string]interface{} `json:"context,omitempty"`

	// Page Pagination options.
	Page PageRequest `json:"page,omitempty"`

	// Resource An entity (subject or resource) associated with a search request.
	// This means the id can be empty.
	Resource SearchEntity `json:"resource"`

	// Subject An entity (subject or resource) associated with a search request.
	// This means the id can be empty.
	Subject SearchEntity `json:"subject"`
}

// SearchResult Search result model.
type SearchResult struct {
	// Id The unique ID of the entity.
	Id string `json:"id,omitempty"`

	// Type The type of the entity.
	Type string `json:"type,omitempty"`
}

// SearchResults Search results model.
type SearchResults struct {
	// Page Pagination options.
	Page PageResponse `json:"page,omitempty"`

	// Results List of search results.
	Results []SearchResult `json:"results"`
}

// AccessDenied Error response model (as defined by RFC9457).
type AccessDenied = ErrorResponse

// BadRequest Error response model (as defined by RFC9457).
type BadRequest = ErrorResponse

// EvaluationResponse Evaluation decision model.
type EvaluationResponse = EvaluationDecision

// EvaluationsResponse Evaluations decision model.
type EvaluationsResponse = EvaluationsDecision

// MetadataResponse Metadata model.
type MetadataResponse = MetadataObject

// NotAuthorized Error response model (as defined by RFC9457).
type NotAuthorized = ErrorResponse

// SearchActionResponse Search action results model.
type SearchActionResponse = SearchActionResults

// SearchResponse Search results model.
type SearchResponse = SearchResults

// UnexpectedError Error response model (as defined by RFC9457).
type UnexpectedError = ErrorResponse

// EvaluationRequest Evaluation object model.
type EvaluationRequest = EvaluationObject

// EvaluationsRequest Evaluations object model.
type EvaluationsRequest = EvaluationsObject

// SearchActionRequest Search action object model.
type SearchActionRequest = SearchActionObject

// SearchRequest Search object model.
type SearchRequest = SearchObject

// AccessEvaluationParams defines parameters for AccessEvaluation.
type AccessEvaluationParams struct {
	// Authorization Request header containing the credentials to authenticate the client (PEP) to the authentication service (PDP).
	Authorization string `json:"Authorization,omitempty"`

	// XRequestID Request header containing the unique ID of the request.
	// This will be returned in the response.
	XRequestID string `json:"X-Request-ID,omitempty"`
}

// AccessEvaluationsParams defines parameters for AccessEvaluations.
type AccessEvaluationsParams struct {
	// Authorization Request header containing the credentials to authenticate the client (PEP) to the authentication service (PDP).
	Authorization string `json:"Authorization,omitempty"`

	// XRequestID Request header containing the unique ID of the request.
	// This will be returned in the response.
	XRequestID string `json:"X-Request-ID,omitempty"`
}

// ActionSearchParams defines parameters for ActionSearch.
type ActionSearchParams struct {
	// Authorization Request header containing the credentials to authenticate the client (PEP) to the authentication service (PDP).
	Authorization string `json:"Authorization,omitempty"`

	// XRequestID Request header containing the unique ID of the request.
	// This will be returned in the response.
	XRequestID string `json:"X-Request-ID,omitempty"`
}

// ResourceSearchParams defines parameters for ResourceSearch.
type ResourceSearchParams struct {
	// Authorization Request header containing the credentials to authenticate the client (PEP) to the authentication service (PDP).
	Authorization string `json:"Authorization,omitempty"`

	// XRequestID Request header containing the unique ID of the request.
	// This will be returned in the response.
	XRequestID string `json:"X-Request-ID,omitempty"`
}

// SubjectSearchParams defines parameters for SubjectSearch.
type SubjectSearchParams struct {
	// Authorization Request header containing the credentials to authenticate the client (PEP) to the authentication service (PDP).
	Authorization string `json:"Authorization,omitempty"`

	// XRequestID Request header containing the unique ID of the request.
	// This will be returned in the response.
	XRequestID string `json:"X-Request-ID,omitempty"`
}

// AccessEvaluationJSONRequestBody defines body for AccessEvaluation for application/json ContentType.
type AccessEvaluationJSONRequestBody = EvaluationObject

// AccessEvaluationsJSONRequestBody defines body for AccessEvaluations for application/json ContentType.
type AccessEvaluationsJSONRequestBody = EvaluationsObject

// ActionSearchJSONRequestBody defines body for ActionSearch for application/json ContentType.
type ActionSearchJSONRequestBody = SearchActionObject

// ResourceSearchJSONRequestBody defines body for ResourceSearch for application/json ContentType.
type ResourceSearchJSONRequestBody = SearchObject

// SubjectSearchJSONRequestBody defines body for SubjectSearch for application/json ContentType.
type SubjectSearchJSONRequestBody = SearchObject

// Getter for additional properties for ReasonObject. Returns the specified
// element and whether it was found
func (a ReasonObject) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ReasonObject
func (a *ReasonObject) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ReasonObject to handle AdditionalProperties
func (a *ReasonObject) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["id"]; found {
		err = json.Unmarshal(raw, &a.Id)
		if err != nil {
			return fmt.Errorf("error reading 'id': %w", err)
		}
		delete(object, "id")
	}

	if raw, found := object["reason_admin"]; found {
		err = json.Unmarshal(raw, &a.ReasonAdmin)
		if err != nil {
			return fmt.Errorf("error reading 'reason_admin': %w", err)
		}
		delete(object, "reason_admin")
	}

	if raw, found := object["reason_user"]; found {
		err = json.Unmarshal(raw, &a.ReasonUser)
		if err != nil {
			return fmt.Errorf("error reading 'reason_user': %w", err)
		}
		delete(object, "reason_user")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ReasonObject to handle AdditionalProperties
func (a ReasonObject) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["id"], err = json.Marshal(a.Id)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'id': %w", err)
	}

	if a.ReasonAdmin != nil {
		object["reason_admin"], err = json.Marshal(a.ReasonAdmin)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'reason_admin': %w", err)
		}
	}

	if a.ReasonUser != nil {
		object["reason_user"], err = json.Marshal(a.ReasonUser)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'reason_user': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}
