# yaml-language-server: $schema=https://raw.githubusercontent.com/deepmap/oapi-codegen/HEAD/configuration-schema.json
package: authzen
output: authzen.go
generate:
  models: true
output-options:
  skip-prune: true
  prefer-skip-optional-pointer: true
