openapi: 3.0.0

info:
  description: |
    OpenAPI specification for AuthZEN spec.
  version: 1.1.0
  title: "AuthZEN"
  contact:
    name: G. Juijn

servers:
  - url: https://localhost:8080/authzen/v1
    description: Local server.

tags:
  - name: authZEN
    description: AuthZEN specification.
  - name: policy
    description: Operations on policies.

paths:
  /evaluation:
    post:
      operationId: "auth-request"
      summary: Authorization request.
      description: Endpoint to evaluate the authorize of a request.
      tags:
        - authZEN
      parameters:
        - name: "Authorization"
          in: header
          description: Request header containing the credentials to authenticate the client (PEP) to the authentication service (PDP).
          schema:
            type: string
        - name: "X-Request-ID"
          in: header
          description: |
            Request header containing the unique ID of the request.
            This will be returned in the response.
          schema:
            type: string

      responses:
        "200":
          description: |
            The authorization request has been handled successfully.
            This does not mean the request is authorized, it means that the request has been processed successfully.
          headers:
            API-Version:
              schema:
                type: string
              description: Full version number of the API.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthorizationResponse"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/NotAuthorized"
        "403":
          $ref: "#/components/responses/AccessDenied"
        "5XX":
          $ref: "#/components/responses/UnexpectedError"
      requestBody:
        $ref: "#/components/requestBodies/AuthorizationRequest"

  /policies:
    get:
      operationId: "get-policies"
      summary: Retrieve policies.
      description: Endpoint to retrieve a list of all cached policies.
      tags:
        - policy
      responses:
        "200":
          description: Policies found.
          headers:
            API-Version:
              schema:
                type: string
              description: Full version number of the API.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PoliciesResponse"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/NotAuthorized"
        "403":
          $ref: "#/components/responses/AccessDenied"
        "404":
          $ref: "#/components/responses/NotFound"
        "5XX":
          $ref: "#/components/responses/UnexpectedError"

  /policy/{id}:
    parameters:
      - $ref: "#/components/parameters/PolicyID"

    get:
      operationId: "get-policy"
      summary: Retrieve policy.
      description: |
        Endpoint to retrieve a specific cached policy.
        If the unique identifier of the policy does not exist, a 404 status code will be returned.
      tags:
        - policy
      responses:
        "200":
          description: Policy found.
          headers:
            API-Version:
              schema:
                type: string
              description: Full version number of the API.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PolicyResponse"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/NotAuthorized"
        "403":
          $ref: "#/components/responses/AccessDenied"
        "404":
          $ref: "#/components/responses/NotFound"
        "5XX":
          $ref: "#/components/responses/UnexpectedError"

    put:
      operationId: "add-policy"
      summary: Add policy.
      description: |
        Endpoint to add a new policy to the cache.
        If the unique identifier of the policy already exists, a 409 status code will be returned.
      tags:
        - policy
      requestBody:
        description: Definition of the new policy.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Policy"
      responses:
        "201":
          description: Policy created.
          headers:
            API-Version:
              schema:
                type: string
              description: Full version number of the API.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PolicyResponse"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/NotAuthorized"
        "403":
          $ref: "#/components/responses/AccessDenied"
        "409":
          $ref: "#/components/responses/AlreadyExists"
        "5XX":
          $ref: "#/components/responses/UnexpectedError"

    post:
      operationId: "replace-policy"
      summary: Replace policy.
      description: |
        Endpoint to replace an existing policy in teh cache.
        If the unique identifier of the policy does not exist, a 404 status code will be returned.
      tags:
        - policy
      requestBody:
        description: Definition of the new policy.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Policy"
      responses:
        "200":
          description: Policy replaced.
          headers:
            API-Version:
              schema:
                type: string
              description: Full version number of the API.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PolicyResponse"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/NotAuthorized"
        "403":
          $ref: "#/components/responses/AccessDenied"
        "404":
          $ref: "#/components/responses/NotFound"
        "5XX":
          $ref: "#/components/responses/UnexpectedError"

    delete:
      operationId: "delete-policy"
      summary: Remove policy.
      description: |
        Endpoint to remove an existing policy from the cache.
        If the unique identifier of the policy does not exist, a 404 status code will be returned.
      tags:
        - policy
      responses:
        "200":
          description: Policy removed.
          headers:
            API-Version:
              schema:
                type: string
              description: Full version number of the API.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PolicyResponse"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/NotAuthorized"
        "403":
          $ref: "#/components/responses/AccessDenied"
        "404":
          $ref: "#/components/responses/NotFound"
        "5XX":
          $ref: "#/components/responses/UnexpectedError"

components:
  parameters:
    PolicyID:
      in: path
      name: "id"
      schema:
        type: string
      required: true
      description: Unique identifier of a policy.

  requestBodies:
    AuthorizationRequest:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/AuthorizationRequest"
      description: The body of the request sent to the authorization service.
      required: true

  responses:
    BadRequest:
      description: The request has failed due to malformed or invalid input data.
      headers:
        API-Version:
          schema:
            type: string
          description: Full version number of the API.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
    NotAuthorized:
      description: The request has failed due to an unauthorized request.
      headers:
        API-Version:
          schema:
            type: string
          description: Full version number of the API.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
    AccessDenied:
      description: The request has failed due to being forbidden.
      headers:
        API-Version:
          schema:
            type: string
          description: Full version number of the API.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
    NotFound:
      description: The request has failed due to the resource not existing.
      headers:
        API-Version:
          schema:
            type: string
          description: Full version number of the API.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
    AlreadyExists:
      description: The request has failed due to the resource existing.
      headers:
        API-Version:
          schema:
            type: string
          description: Full version number of the API.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
    UnexpectedError:
      description: The request has failed due to an unexpected error.
      headers:
        API-Version:
          schema:
            type: string
          description: Full version number of the API.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"

  schemas:
    Entity:
      type: object
      description: |
        The entity associated with an authorization request.
        This can be the subject (e.g. principal) or the resource.
      properties:
        type:
          type: string
          description: The type of the entity.
          example: "user"
        id:
          type: string
          description: The unique ID of the entity.
          example: "alice"
        properties:
          type: object
          description: Optional attributes for the entity.
      required:
        - type
        - id

    Action:
      type: object
      description: The action associated with an authorization request.
      properties:
        name:
          type: string
          description: The name of the action.
          example: "can_read"
        properties:
          type: object
          description: Optional attributes for the action.
      required:
        - type

    ReasonField:
      type: object
      description: Map of one or more reasons, with a language-identifier as the key.

    ReasonObject:
      type: object
      description: Specifies a particular reason.
      properties:
        id:
          type: string
          description: Unique identifier of the reason.
        reasonAdmin:
          $ref: "#/components/schemas/ReasonField"
        reasonUser:
          $ref: "#/components/schemas/ReasonField"
      required:
        - id

    AuthorizationRequest:
      type: object
      description: Authorization request model.
      properties:
        subject:
          $ref: "#/components/schemas/Entity"
        action:
          $ref: "#/components/schemas/Action"
        resource:
          $ref: "#/components/schemas/Entity"
        context:
          description: Optional context of the request.
          type: object
      required:
        - subject
        - action
        - resource

    AuthorizationResponse:
      type: object
      description: Authorization response model.
      properties:
        decision:
          type: boolean
          description: true if the request is authorized.
        context:
          type: object
          description: Optional context returned by the policy engine.
      required:
        - decision

    Policy:
      type: object
      description: The content of a policy.
      properties:
        id:
          type: string
          description: The unique identifier of the policy.
        source:
          type: string
          description: The unique identifier of the source.
        target:
          type: string
          description: The unique identifier of the target.
        rvvaId:
          type: string
          description: The unique identifier of the Register of Activities (RvVA).
        language:
          type: string
          description: The language of the policy.
          example: "rego"
        url:
          type: string
          description: Link to the actual policy.
      required:
        - id
        - language
        - url

    PoliciesResponse:
      description: A set of policies.
      type: array
      items:
        $ref: "#/components/schemas/Policy"

    PolicyResponse:
      $ref: "#/components/schemas/Policy"

    ErrorResponse:
      type: object
      description: Error response model (as defined by RFC9457).
      properties:
        type:
          type: string
          format: uri
          description: Identification of the problem.
        status:
          type: integer
          description: Status code of the problem.
        title:
          type: string
          description: Summary of the problem.
        detail:
          type: string
          description: Detailed description of the problem.
        instance:
          type: string
          format: uri
          description: Identification of the problem instance.
