openapi: 3.0.0

info:
  description: |
    OpenAPI specification for AuthZEN spec.
    See: https://openid.net/specs/authorization-api-1_0-01.html
  version: 1.2.0
  title: "AuthZEN"
  contact:
    name: G. Juijn
    url: https://gitlab.com/digilab.overheid.nl/ecosystem/ftv/ftv-implementatie

servers:
  - url: https://localhost:8080/authzen/v1
    description: Local server.

tags:
  - name: authZEN
    description: AuthZEN specification.
  - name: evaluation
    description: AuthZEN evaluation endpoints.
  - name: search
    description: AuthZEN search endpoints.

paths:
  /evaluation:
    post:
      operationId: "access-evaluation"
      summary: Access evaluation request.
      description: Endpoint to evaluate a single access request.
      tags:
        - authZEN
        - evaluation
      parameters:
        - name: "Authorization"
          in: header
          description: Request header containing the credentials to authenticate the client (PEP) to the authentication service (PDP).
          schema:
            type: string
        - name: "X-Request-ID"
          in: header
          description: |
            Request header containing the unique ID of the request.
            This will be returned in the response.
          schema:
            type: string

      responses:
        "200":
          description: |
            The authorization request has been handled successfully.
            This does not mean the request is authorized, it means that the request has been processed successfully.
          headers:
            API-Version:
              description: Full version number of the API.
              schema:
                type: string
            X-Request-ID:
              description: Returns the X-Request-ID from the request.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthorizationResponse"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/NotAuthorized"
        "403":
          $ref: "#/components/responses/AccessDenied"
        "5XX":
          $ref: "#/components/responses/UnexpectedError"
      requestBody:
        $ref: "#/components/requestBodies/AuthorizationRequest"

components:
  requestBodies:
    AuthorizationRequest:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/AuthorizationRequest"
      description: The body of the request sent to the authorization service.
      required: true

  responses:
    BadRequest:
      description: The request has failed due to malformed or invalid input data.
      headers:
        API-Version:
          schema:
            type: string
          description: Full version number of the API.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
    NotAuthorized:
      description: The request has failed due to an unauthorized request.
      headers:
        API-Version:
          schema:
            type: string
          description: Full version number of the API.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
    AccessDenied:
      description: The request has failed due to being forbidden.
      headers:
        API-Version:
          schema:
            type: string
          description: Full version number of the API.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
    UnexpectedError:
      description: The request has failed due to an unexpected error.
      headers:
        API-Version:
          schema:
            type: string
          description: Full version number of the API.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"

  schemas:
    Entity:
      type: object
      description: |
        The entity associated with an authorization request.
        This can be the subject (e.g. principal) or the resource.
      properties:
        type:
          type: string
          description: The type of the entity.
          example: "user"
        id:
          type: string
          description: The unique ID of the entity.
          example: "alice"
        properties:
          type: object
          description: Optional attributes for the entity.
      required:
        - type
        - id

    Action:
      type: object
      description: The action associated with an authorization request.
      properties:
        name:
          type: string
          description: The name of the action.
          example: "can_read"
        properties:
          type: object
          description: Optional attributes for the action.
      required:
        - type

    ReasonField:
      type: object
      description: Map of one or more reasons, with a language-identifier as the key.

    ReasonObject:
      type: object
      description: Specifies a particular reason.
      properties:
        id:
          type: string
          description: Unique identifier of the reason.
        reasonAdmin:
          $ref: "#/components/schemas/ReasonField"
        reasonUser:
          $ref: "#/components/schemas/ReasonField"
      required:
        - id

    AuthorizationRequest:
      type: object
      description: Authorization request model.
      properties:
        subject:
          $ref: "#/components/schemas/Entity"
        action:
          $ref: "#/components/schemas/Action"
        resource:
          $ref: "#/components/schemas/Entity"
        context:
          description: Optional context of the request.
          type: object
      required:
        - subject
        - action
        - resource

    AuthorizationResponse:
      type: object
      description: Authorization response model.
      properties:
        decision:
          type: boolean
          description: true if the request is authorized.
        context:
          $ref: "#/components/schemas/ReasonObject"
      required:
        - decision

    ErrorResponse:
      type: object
      description: Error response model (as defined by RFC9457).
      properties:
        type:
          type: string
          format: uri
          description: Identification of the problem.
        status:
          type: integer
          description: Status code of the problem.
        title:
          type: string
          description: Summary of the problem.
        detail:
          type: string
          description: Detailed description of the problem.
        instance:
          type: string
          format: uri
          description: Identification of the problem instance.
