BEGIN;

DROP TABLE IF EXISTS language CASCADE;

DROP TABLE IF EXISTS tag CASCADE;

DROP TABLE IF EXISTS deployment CASCADE;

DROP TABLE IF EXISTS policy CASCADE;
DROP TABLE IF EXISTS policy_audit CASCADE;
DROP TABLE IF EXISTS policy_deployment CASCADE;

DROP TABLE IF EXISTS attribute CASCADE;
DROP TABLE IF EXISTS attribute_audit CASCADE;
DROP TABLE IF EXISTS attribute_deployment CASCADE;

DROP TABLE IF EXISTS entity CASCADE;
DROP TABLE IF EXISTS entity_audit CASCADE;
DROP TABLE IF EXISTS entity_deployment CASCADE;

DROP TABLE IF EXISTS relation CASCADE;
DROP TABLE IF EXISTS relation_audit CASCADE;
DROP TABLE IF EXISTS relation_deployment CASCADE;

COMMIT;
