// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package api

// Error The error that occurred while processing this request.
type Error struct {
	Message *string `json:"message,omitempty"`
}

// Nationaliteit defines model for Nationaliteit.
type Nationaliteit struct {
	// Code Code of a nationaliteit.
	Code string `json:"code"`

	// DatumEinde Date after which the element becomes invalid.
	DatumEinde *DatumEinde `json:"datumEinde,omitempty"`

	// DatumIngang Date on which the element becomes valid
	DatumIngang *DatumIngang `json:"datumIngang,omitempty"`

	// Omschrijving Omschrijving of a nationaliteit.
	Omschrijving string `json:"omschrijving"`
}

// DatumEinde Date after which the element becomes invalid.
type DatumEinde = string

// DatumIngang Date on which the element becomes valid
type DatumIngang = string

// DatumEindeFrom defines model for datumEindeFrom.
type DatumEindeFrom = string

// DatumEindeTo defines model for datumEindeTo.
type DatumEindeTo = string

// DatumIngangFrom defines model for datumIngangFrom.
type DatumIngangFrom = string

// DatumIngangTo defines model for datumIngangTo.
type DatumIngangTo = string

// OmschrijvingFrom defines model for omschrijvingFrom.
type OmschrijvingFrom = string

// OmschrijvingRx defines model for omschrijvingRx.
type OmschrijvingRx = string

// OmschrijvingTo defines model for omschrijvingTo.
type OmschrijvingTo = string

// BadRequestErrorResponse defines model for BadRequestErrorResponse.
type BadRequestErrorResponse struct {
	Errors []Error `json:"errors"`
}

// NationaliteitenResponse defines model for NationaliteitenResponse.
type NationaliteitenResponse struct {
	Data []Nationaliteit `json:"data"`
}

// FindNationailteitParams defines parameters for FindNationailteit.
type FindNationailteitParams struct {
	// CodeFrom The minimum Code of the Nationaliteit to search for.
	CodeFrom *int32 `form:"codeFrom,omitempty" json:"codeFrom,omitempty"`

	// CodeTo The maximum Code of the Nationaliteit to search for.
	CodeTo *int32 `form:"codeTo,omitempty" json:"codeTo,omitempty"`

	// OmschrijvingRx Regular expression to filter the Omschrijving of the element on.
	OmschrijvingRx *OmschrijvingRx `form:"omschrijvingRx,omitempty" json:"omschrijvingRx,omitempty"`

	// OmschrijvingFrom The minimum Omschrijving of the element to search for.
	OmschrijvingFrom *OmschrijvingFrom `form:"omschrijvingFrom,omitempty" json:"omschrijvingFrom,omitempty"`

	// OmschrijvingTo The maximum Omschrijving of the element to search for.
	OmschrijvingTo *OmschrijvingTo `form:"omschrijvingTo,omitempty" json:"omschrijvingTo,omitempty"`

	// DatumIngangFrom The minimum DatumIngang of the element to search for.
	DatumIngangFrom *DatumIngangFrom `form:"datumIngangFrom,omitempty" json:"datumIngangFrom,omitempty"`

	// DatumIngangTo The maximum DatumIngang of the element to search for.
	DatumIngangTo *DatumIngangTo `form:"datumIngangTo,omitempty" json:"datumIngangTo,omitempty"`

	// DatumEindeFrom The minimum DatumEinde of the element to search for.
	DatumEindeFrom *DatumEindeFrom `form:"datumEindeFrom,omitempty" json:"datumEindeFrom,omitempty"`

	// DatumEindeTo The maximum DatumEinde of the element to search for.
	DatumEindeTo *DatumEindeTo `form:"datumEindeTo,omitempty" json:"datumEindeTo,omitempty"`
}
