// Package auth provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package auth

// AuthorizationRequest defines model for AuthorizationRequest.
type AuthorizationRequest struct {
	Input *struct {
		// Body The HTTP request body as received by the Inway Base64 encoded
		Body *string `json:"body,omitempty"`

		// Headers Contains the HTTP-headers of the request made to the Outway
		Headers map[string][]string `json:"headers"`

		// Method the HTTP-method of the request made to the Outway
		Method string `json:"method"`

		// OutwayCertificateChain The x.509 certificate chain. The first entry in the array is the outway certificate; the other certificates can be used to verify this first certificate.
		OutwayCertificateChain []string `json:"outway_certificate_chain"`

		// Path path of the request to the Outway
		Path string `json:"path"`

		// Query query parameters of the request to the Outway
		Query string `json:"query"`
	} `json:"input,omitempty"`
}

// AuthorizationResponse defines model for AuthorizationResponse.
type AuthorizationResponse struct {
	Result *AuthorizationResponseData `json:"result,omitempty"`
}

// AuthorizationResponseData defines model for AuthorizationResponseData.
type AuthorizationResponseData struct {
	// Allowed true if the request is authorized. The Outway will continue to send the request to the targeted service. false when the authorization has failed for whatever reason. The Outway will return a 401 to the requesting client.
	Allowed *bool `json:"allowed,omitempty"`
	Status  *struct {
		// Reason reason why the request was not authorized
		Reason *string `json:"reason,omitempty"`
	} `json:"status,omitempty"`
}

// PostParams defines parameters for Post.
type PostParams struct {
	// ProxyAuthorization Request header contains the credentials to authenticate a user agent to the Outway. This header will be stripped
	ProxyAuthorization *string `json:"Proxy-Authorization,omitempty"`
}

// PostJSONRequestBody defines body for Post for application/json ContentType.
type PostJSONRequestBody = AuthorizationRequest
