apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: open-ftv
spec:
  url: oci://registry.gitlab.com/digilab.overheid.nl/ecosystem/ftv/open-ftv/charts/open-ftv
  ref:
    tag: ${OPEN_FTV_VERSION}
  interval: 10m
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: open-ftv
spec:
  serviceAccountName: flux-reconciler
  interval: 35m
  chartRef:
    kind: OCIRepository
    name: open-ftv
  values:
    pdp:
      config:
        authorizationDecisionLog:
          type: postgresql
    manager:
      enabled: true
      config:
        authorizationDecisionLog:
          type: postgresql
        corsOrigins:
          - https://open-ftv.simulatie.datastelsel.nl
        oidc:
          issuer: https://keycloak.simulatie.datastelsel.nl/realms/openftv
          jwksUrl: http://{{ .Release.Name }}-keycloak/realms/openftv/protocol/openid-connect/certs
          audience: openftv
    management-interface:
      enabled: true
      config:
        oidc:
          authority: https://keycloak.simulatie.datastelsel.nl/realms/openftv
          clientId: openftv
      httpRoute:
        enabled: true
        parentRefs:
          - group: gateway.networking.k8s.io
            kind: Gateway
            name: default-gateway
            namespace: fds-public
            sectionName: https
        hostnames:
          - open-ftv.simulatie.datastelsel.nl
    keycloak:
      enabled: true
      config:
        # Reach the admin console with: kubectl port-forward svc/open-ftv-keycloak 8080:80
        adminHostname: http://localhost:8080
        adminUsername: admin
        adminPassword: rS75MSriX685rzkUonPrZLxTsE39
        realm:
          redirectUris:
            - https://open-ftv.simulatie.datastelsel.nl/*
          webOrigins:
            - https://open-ftv.simulatie.datastelsel.nl
          users:
            adminPassword: password
            authorPassword: password
            auditorPassword: password
      httpRoute:
        enabled: true
        parentRefs:
          - group: gateway.networking.k8s.io
            kind: Gateway
            name: default-gateway
            namespace: fds-public
            sectionName: https
        hostnames:
          - keycloak.simulatie.datastelsel.nl
