package maps

var CategoryByCode = map[string]string{
	"01": "Persoon",
	"02": "Ouder1",
	"03": "Ouder2",
	"04": "Nationaliteit",
	"05": "Huwelijk/geregistreerd partnerschap",
	"06": "Overlijden",
	"07": "Inschrijving",
	"08": "Verblijfsplaats",
	"09": "Kind",
	"10": "Verblijfstitel",
	"11": "Gezagsverhouding",
	"12": "Reisdocument",
	"13": "Kiesrecht",
	"14": "Afnemersindicatie",
	"16": "Tijdelijk verblijfadres",
	"17": "Contactgegevens",
	"21": "Verwijzing",
	"51": "Persoon*",
	"52": "Ouder1*",
	"53": "Ouder2*",
	"54": "Nationaliteit*",
	"55": "Huwelijk/geregistreerd partnerschap*",
	"56": "Overlijden*",
	"58": "Verblijfsplaats*",
	"59": "Kind*",
	"60": "Verblijfstitel*",
	"61": "Gezagsverhouding*",
	"64": "Afnemersindicatie*",
	"66": "Tijdelijk verblijfadres*",
	"71": "Verwijzing*",
}
