package maps

var OperatorByCode = map[string]string{
	"+":      "+",
	"-":      "-",
	"ALS":    "IF",
	"DAN":    "THEN",
	"ENVGL":  "&&",
	"ENVWD":  "&&",
	"GA1":    "==",
	"GAA":    "==",
	"GD1":    ">",
	"GDA":    ">",
	"GDOG1":  ">=",
	"GDOGA":  ">=",
	"KD1":    "<",
	"KDA":    "<",
	"KDOG1":  "<=",
	"KDOGA":  "<=",
	"KLOPT1": "",
	"KLOPTA": "",
	"KNV":    "ISNULL",
	"KV":     "NOT ISNULL",
	"KVA":    "NOT ISNULL",
	"LIJST":  "",
	"NIET":   "NOT",
	"OFVGL":  "||",
	"OFVWD":  "||",
	"OGA1":   "!=",
	"OGAA":   "!=",
	"ONWAAR": "FALSE",
	"WAAR":   "TRUE",
}
