apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "open-ftv-management-interface.fullname" . }}
  labels:
    {{- include "open-ftv-management-interface.labels" . | nindent 4 }}
  {{- with .Values.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "open-ftv-management-interface.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "open-ftv-management-interface.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "open-ftv-management-interface.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: NGINX_ENTRYPOINT_QUIET_LOGS
              value: "1"
            - name: VITE_PAP_BASE_URL
              value: {{ .Values.config.managerURL | quote }}
            - name: VITE_PIP_BASE_URL
              value: {{ .Values.config.managerURL | quote }}
            - name: VITE_OIDC_AUTHORITY
              value: {{ .Values.config.oidc.authority | quote }}
            - name: VITE_OIDC_CLIENT_ID
              value: {{ .Values.config.oidc.clientId | quote }}
            - name: MANAGER_MAX_LOGO_SIZE
              value: {{ .Values.config.maxLogoSize | quote }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: http
          readinessProbe:
            tcpSocket:
              port: http
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: nginx-conf
          emptyDir:
            sizeLimit: 1Mi
            medium: Memory
        - name: tmp
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
