// Package liveness provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package liveness

// Error The response for an error (as defined by RFC9457).
type Error struct {
	// Detail Detailed description of the problem.
	Detail string `json:"detail,omitempty"`

	// Instance Identification of the problem instance.
	Instance string `json:"instance,omitempty"`

	// Status Status code of the problem.
	Status int `json:"status,omitempty"`

	// Title Summary of the problem.
	Title string `json:"title,omitempty"`

	// Type Identification of the problem.
	Type string `json:"type,omitempty"`
}

// BadRequest The response for an error (as defined by RFC9457).
type BadRequest = Error

// NotFound The response for an error (as defined by RFC9457).
type NotFound = Error

// OkResponse The response for an error (as defined by RFC9457).
type OkResponse = Error

// ServiceUnavailable The response for an error (as defined by RFC9457).
type ServiceUnavailable = Error

// UnexpectedError The response for an error (as defined by RFC9457).
type UnexpectedError = Error
