// Package liveness provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package liveness

import (
	apierrors "gitlab.com/digilab.overheid.nl/ecosystem/ftv/open-ftv/oas/errors"
)

// Error Error response model (as defined by RFC9457).
type Error = apierrors.ErrorResponse

// BadRequest Error response model (as defined by RFC9457).
type BadRequest = Error

// NotFound Error response model (as defined by RFC9457).
type NotFound = Error

// OkResponse Error response model (as defined by RFC9457).
type OkResponse = Error

// ServiceUnavailable Error response model (as defined by RFC9457).
type ServiceUnavailable = Error

// UnexpectedError Error response model (as defined by RFC9457).
type UnexpectedError = Error
