// Package ledenlijst provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package ledenlijst

// Error The error that occured while processing this request.
type Error struct {
	Message string `json:"message"`
}

// Organization Organization model
type Organization struct {
	// Attributes attributes of an Organization
	Attributes map[string]interface{} `json:"attributes"`
	Id         string                 `json:"id"`

	// Oin OIN (Public Organization Identification number)
	Oin Oin `json:"oin"`
}

// OrganizationUpdate organization to update.
type OrganizationUpdate struct {
	// Attributes attributes of an Organization
	Attributes map[string]interface{} `json:"attributes"`
}

// Oin OIN (Public Organization Identification number)
type Oin = string

// PathOIN OIN (Public Organization Identification number)
type PathOIN = Oin

// BadRequestErrorResponse defines model for BadRequestErrorResponse.
type BadRequestErrorResponse struct {
	Errors []Error `json:"errors"`
}

// InternalServerErrorResponse defines model for InternalServerErrorResponse.
type InternalServerErrorResponse struct {
	Errors *[]Error `json:"errors,omitempty"`
}

// NotFoundErrorResponse defines model for NotFoundErrorResponse.
type NotFoundErrorResponse struct {
	Errors *[]Error `json:"errors,omitempty"`
}

// OrganizationUpdateRequest defines model for OrganizationUpdateRequest.
type OrganizationUpdateRequest struct {
	// Data organization to update.
	Data *OrganizationUpdate `json:"data,omitempty"`
}

// UpdateOrganizationByOINJSONBody defines parameters for UpdateOrganizationByOIN.
type UpdateOrganizationByOINJSONBody struct {
	// Data organization to update.
	Data *OrganizationUpdate `json:"data,omitempty"`
}

// CreateOrganizationJSONRequestBody defines body for CreateOrganization for application/json ContentType.
type CreateOrganizationJSONRequestBody = Organization

// UpdateOrganizationByOINJSONRequestBody defines body for UpdateOrganizationByOIN for application/json ContentType.
type UpdateOrganizationByOINJSONRequestBody UpdateOrganizationByOINJSONBody
