/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublicatiesIndexRouteImport } from './routes/publicaties/index'
import { Route as PoliciesIndexRouteImport } from './routes/policies/index'
import { Route as LogboekIndexRouteImport } from './routes/logboek/index'
import { Route as AttributenIndexRouteImport } from './routes/attributen/index'
import { Route as PoliciesAddRouteImport } from './routes/policies/add'
import { Route as AttributenToevoegenRouteImport } from './routes/attributen/toevoegen'
import { Route as PoliciesIdIndexRouteImport } from './routes/policies/$id/index'
import { Route as LogboekIdIndexRouteImport } from './routes/logboek/$id/index'
import { Route as AttributenKeyIndexRouteImport } from './routes/attributen/$key/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicatiesIndexRoute = PublicatiesIndexRouteImport.update({
  id: '/publicaties/',
  path: '/publicaties/',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesIndexRoute = PoliciesIndexRouteImport.update({
  id: '/policies/',
  path: '/policies/',
  getParentRoute: () => rootRouteImport,
} as any)
const LogboekIndexRoute = LogboekIndexRouteImport.update({
  id: '/logboek/',
  path: '/logboek/',
  getParentRoute: () => rootRouteImport,
} as any)
const AttributenIndexRoute = AttributenIndexRouteImport.update({
  id: '/attributen/',
  path: '/attributen/',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesAddRoute = PoliciesAddRouteImport.update({
  id: '/policies/add',
  path: '/policies/add',
  getParentRoute: () => rootRouteImport,
} as any)
const AttributenToevoegenRoute = AttributenToevoegenRouteImport.update({
  id: '/attributen/toevoegen',
  path: '/attributen/toevoegen',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesIdIndexRoute = PoliciesIdIndexRouteImport.update({
  id: '/policies/$id/',
  path: '/policies/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const LogboekIdIndexRoute = LogboekIdIndexRouteImport.update({
  id: '/logboek/$id/',
  path: '/logboek/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const AttributenKeyIndexRoute = AttributenKeyIndexRouteImport.update({
  id: '/attributen/$key/',
  path: '/attributen/$key/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attributen/toevoegen': typeof AttributenToevoegenRoute
  '/policies/add': typeof PoliciesAddRoute
  '/attributen/': typeof AttributenIndexRoute
  '/logboek/': typeof LogboekIndexRoute
  '/policies/': typeof PoliciesIndexRoute
  '/publicaties/': typeof PublicatiesIndexRoute
  '/attributen/$key/': typeof AttributenKeyIndexRoute
  '/logboek/$id/': typeof LogboekIdIndexRoute
  '/policies/$id/': typeof PoliciesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attributen/toevoegen': typeof AttributenToevoegenRoute
  '/policies/add': typeof PoliciesAddRoute
  '/attributen': typeof AttributenIndexRoute
  '/logboek': typeof LogboekIndexRoute
  '/policies': typeof PoliciesIndexRoute
  '/publicaties': typeof PublicatiesIndexRoute
  '/attributen/$key': typeof AttributenKeyIndexRoute
  '/logboek/$id': typeof LogboekIdIndexRoute
  '/policies/$id': typeof PoliciesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/attributen/toevoegen': typeof AttributenToevoegenRoute
  '/policies/add': typeof PoliciesAddRoute
  '/attributen/': typeof AttributenIndexRoute
  '/logboek/': typeof LogboekIndexRoute
  '/policies/': typeof PoliciesIndexRoute
  '/publicaties/': typeof PublicatiesIndexRoute
  '/attributen/$key/': typeof AttributenKeyIndexRoute
  '/logboek/$id/': typeof LogboekIdIndexRoute
  '/policies/$id/': typeof PoliciesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/attributen/toevoegen'
    | '/policies/add'
    | '/attributen/'
    | '/logboek/'
    | '/policies/'
    | '/publicaties/'
    | '/attributen/$key/'
    | '/logboek/$id/'
    | '/policies/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attributen/toevoegen'
    | '/policies/add'
    | '/attributen'
    | '/logboek'
    | '/policies'
    | '/publicaties'
    | '/attributen/$key'
    | '/logboek/$id'
    | '/policies/$id'
  id:
    | '__root__'
    | '/'
    | '/attributen/toevoegen'
    | '/policies/add'
    | '/attributen/'
    | '/logboek/'
    | '/policies/'
    | '/publicaties/'
    | '/attributen/$key/'
    | '/logboek/$id/'
    | '/policies/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AttributenToevoegenRoute: typeof AttributenToevoegenRoute
  PoliciesAddRoute: typeof PoliciesAddRoute
  AttributenIndexRoute: typeof AttributenIndexRoute
  LogboekIndexRoute: typeof LogboekIndexRoute
  PoliciesIndexRoute: typeof PoliciesIndexRoute
  PublicatiesIndexRoute: typeof PublicatiesIndexRoute
  AttributenKeyIndexRoute: typeof AttributenKeyIndexRoute
  LogboekIdIndexRoute: typeof LogboekIdIndexRoute
  PoliciesIdIndexRoute: typeof PoliciesIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publicaties/': {
      id: '/publicaties/'
      path: '/publicaties'
      fullPath: '/publicaties/'
      preLoaderRoute: typeof PublicatiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies/': {
      id: '/policies/'
      path: '/policies'
      fullPath: '/policies/'
      preLoaderRoute: typeof PoliciesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logboek/': {
      id: '/logboek/'
      path: '/logboek'
      fullPath: '/logboek/'
      preLoaderRoute: typeof LogboekIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attributen/': {
      id: '/attributen/'
      path: '/attributen'
      fullPath: '/attributen/'
      preLoaderRoute: typeof AttributenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies/add': {
      id: '/policies/add'
      path: '/policies/add'
      fullPath: '/policies/add'
      preLoaderRoute: typeof PoliciesAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attributen/toevoegen': {
      id: '/attributen/toevoegen'
      path: '/attributen/toevoegen'
      fullPath: '/attributen/toevoegen'
      preLoaderRoute: typeof AttributenToevoegenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies/$id/': {
      id: '/policies/$id/'
      path: '/policies/$id'
      fullPath: '/policies/$id/'
      preLoaderRoute: typeof PoliciesIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logboek/$id/': {
      id: '/logboek/$id/'
      path: '/logboek/$id'
      fullPath: '/logboek/$id/'
      preLoaderRoute: typeof LogboekIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attributen/$key/': {
      id: '/attributen/$key/'
      path: '/attributen/$key'
      fullPath: '/attributen/$key/'
      preLoaderRoute: typeof AttributenKeyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AttributenToevoegenRoute: AttributenToevoegenRoute,
  PoliciesAddRoute: PoliciesAddRoute,
  AttributenIndexRoute: AttributenIndexRoute,
  LogboekIndexRoute: LogboekIndexRoute,
  PoliciesIndexRoute: PoliciesIndexRoute,
  PublicatiesIndexRoute: PublicatiesIndexRoute,
  AttributenKeyIndexRoute: AttributenKeyIndexRoute,
  LogboekIdIndexRoute: LogboekIdIndexRoute,
  PoliciesIdIndexRoute: PoliciesIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
