// Package bundles provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package bundles

import (
	apierrors "gitlab.com/digilab.overheid.nl/ecosystem/ftv/open-ftv/oas/errors"
)

// Defines values for PrincipalKind.
const (
	Legacy PrincipalKind = "legacy"
	System PrincipalKind = "system"
	User   PrincipalKind = "user"
)

// Valid indicates whether the value is a known member of the PrincipalKind enum.
func (e PrincipalKind) Valid() bool {
	switch e {
	case Legacy:
		return true
	case System:
		return true
	case User:
		return true
	default:
		return false
	}
}

// BundleActivated The details of a deployment bundle activation.
type BundleActivated struct {
	// PreviousVersion Version number of the replaced deployment.
	PreviousVersion int `json:"previousVersion"`
}

// BundleConfig Bundle deployment configuration.
type BundleConfig struct {
	// Data Indicates to bundle attributes, entities and relations with matching tag.
	Data bool `json:"data,omitempty"`

	// Description Optional description of this bundle deployment configuration.
	Description string `json:"description,omitempty"`

	// Id Unique identifier of this bundle deployment configuration (UUID).
	Id string `json:"id"`

	// Policies Indicates to bundle policies with matching tag.
	Policies bool `json:"policies,omitempty"`

	// Tags Tags to match against. A single matching tag is sufficient.
	Tags    []string `json:"tags"`
	Targets []Target `json:"targets"`

	// Title Title of this bundle deployment configuration.
	Title string `json:"title"`

	// Version Indicates to bundle the version number.
	Version bool `json:"version,omitempty"`
}

// BundleConfigs List of bundle deployment configurations.
type BundleConfigs = []BundleConfig

// CompressType The code and name of a compression type.
type CompressType struct {
	// Code Code of the compression type.
	Code int `json:"code"`

	// Name Display name for the compression type.
	Name string `json:"name"`
}

// CompressTypes List of compression type codes and names.
type CompressTypes = []CompressType

// Deployment The details of a bundle deployment.
type Deployment struct {
	// Audit The audit details for an object.
	Audit ObjectAudit `json:"audit"`

	// Description Optional description of the deployment.
	Description string `json:"description,omitempty"`

	// Message Message for a failed deployment.
	Message string `json:"message,omitempty"`

	// Status Status of the deployment.
	Status int `json:"status"`

	// Title Title of the deployment.
	Title string `json:"title"`

	// Version Version number of the last deployment.
	Version int `json:"version"`
}

// Deployments List of bundle deployments.
type Deployments = []Deployment

// ErrorMessage Error response model (as defined by RFC9457).
type ErrorMessage = apierrors.ErrorResponse

// NewDeploymentBody Body content for a new deployment request.
type NewDeploymentBody struct {
	// Description Optional description of the new deployment.
	Description string `json:"description,omitempty"`

	// Title Title of the new deployment.
	Title string `json:"title"`
}

// ObjectAudit The audit details for an object.
type ObjectAudit struct {
	// Created Timestamp the object was created (RFC3339 format).
	Created string `json:"created"`

	// CreatedBy Who performed an action. `id` is the stored attribution value and is always present;
	// `name` is filled in from the manager's local principal record and is absent when that
	// record is unknown, in which case clients show the raw `id`. Only a principal of kind
	// `user` identifies a real subject and may be linked to.
	CreatedBy Principal `json:"createdBy"`

	// Updated Timestamp the object was last updated (RFC3339 format).
	Updated   string     `json:"updated,omitempty"`
	UpdatedBy *Principal `json:"updatedBy,omitempty"`
}

// Principal Who performed an action. `id` is the stored attribution value and is always present;
// `name` is filled in from the manager's local principal record and is absent when that
// record is unknown, in which case clients show the raw `id`. Only a principal of kind
// `user` identifies a real subject and may be linked to.
type Principal struct {
	// Id Stable identifier of the principal, as stored on the object.
	Id string `json:"id"`

	// Kind `user` for an authenticated subject, `system` for the manager's own actions, and
	// `legacy` for an attribution value predating the principal record, which is shown
	// but identifies nobody.
	Kind PrincipalKind `json:"kind,omitempty"`

	// Name Display name of the principal, when known.
	Name string `json:"name,omitempty"`
}

// PrincipalKind `user` for an authenticated subject, `system` for the manager's own actions, and
// `legacy` for an attribution value predating the principal record, which is shown
// but identifies nobody.
type PrincipalKind string

// Status The code and name of a deployment status.
type Status struct {
	// Code Code of the status.
	Code int `json:"code"`

	// Name Display name for the status.
	Name string `json:"name"`
}

// Statuses List of deployment status codes and names.
type Statuses = []Status

// Target The details of a bundle target.
type Target struct {
	// Apikey Indicates an API-key is configured.
	Apikey bool `json:"apikey,omitempty"`

	// Compression Type of compression to use for the bundle (default = gzip).
	Compression int `json:"compression,omitempty"`

	// Headers List of optional HTTP headers to send.
	Headers []string `json:"headers,omitempty"`

	// Tls Indicates the connection will force the use of TLS.
	Tls bool `json:"tls,omitempty"`

	// Uri URI of the target PDP.
	Uri string `json:"uri"`
}

// BundleID defines model for BundleID.
type BundleID = string

// DeploymentID defines model for DeploymentID.
type DeploymentID = int

// BadRequest Error response model (as defined by RFC9457).
type BadRequest = ErrorMessage

// CompressTypesFound List of compression type codes and names.
type CompressTypesFound = CompressTypes

// ConfigFound List of bundle deployment configurations.
type ConfigFound = BundleConfigs

// DeployStarted The details of a bundle deployment.
type DeployStarted = Deployment

// DeploymentFound The details of a bundle deployment.
type DeploymentFound = Deployment

// DeploymentsFound List of bundle deployments.
type DeploymentsFound = Deployments

// NotAuthenticated Error response model (as defined by RFC9457).
type NotAuthenticated = ErrorMessage

// NotAuthorized Error response model (as defined by RFC9457).
type NotAuthorized = ErrorMessage

// NotFound Error response model (as defined by RFC9457).
type NotFound = ErrorMessage

// StatusesFound List of deployment status codes and names.
type StatusesFound = Statuses

// UnexpectedError Error response model (as defined by RFC9457).
type UnexpectedError = ErrorMessage

// StartDeploymentJSONRequestBody defines body for StartDeployment for application/json ContentType.
type StartDeploymentJSONRequestBody = NewDeploymentBody
