// Package bundles provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package bundles

// BundleActivated The details of a deployment bundle activation.
type BundleActivated struct {
	// PreviousVersion Version number of the replaced deployment.
	PreviousVersion int `json:"previousVersion"`
}

// BundleConfig Bundle deployment configuration.
type BundleConfig struct {
	// Data Indicates to bundle attributes, entities and relations with matching tag.
	Data bool `json:"data,omitempty"`

	// Description Optional description of this bundle deployment configuration.
	Description string `json:"description,omitempty"`

	// Id Unique identifier of this bundle deployment configuration.
	Id string `json:"id"`

	// Policies Indicates to bundle policies with matching tag.
	Policies bool `json:"policies,omitempty"`

	// Tags Tags to match against. A single matching tag is sufficient.
	Tags    []string `json:"tags"`
	Targets []Target `json:"targets"`

	// Title Title of this bundle deployment configuration.
	Title string `json:"title"`

	// Version Indicates to bundle the version number.
	Version bool `json:"version,omitempty"`
}

// BundleConfigs List of bundle deployment configurations.
type BundleConfigs = []BundleConfig

// CompressType The code and name of a compression type.
type CompressType struct {
	// Code Code of the compression type.
	Code int `json:"code"`

	// Name Display name for the compression type.
	Name string `json:"name"`
}

// CompressTypes List of compression type codes and names.
type CompressTypes = []CompressType

// Deployment The details of a bundle deployment.
type Deployment struct {
	// Audit The audit details for an object.
	Audit ObjectAudit `json:"audit"`

	// Description Optional description of the deployment.
	Description string `json:"description,omitempty"`

	// Message Message for a failed deployment.
	Message string `json:"message,omitempty"`

	// Status Status of the deployment.
	Status int `json:"status"`

	// Title Title of the deployment.
	Title string `json:"title"`

	// Version Version number of the last deployment.
	Version int `json:"version"`
}

// Deployments List of bundle deployments.
type Deployments = []Deployment

// ErrorMessage The response for an error (as defined by RFC9457).
type ErrorMessage struct {
	// Detail Detailed description of the problem.
	Detail string `json:"detail,omitempty"`

	// Instance Identification of the problem instance.
	Instance string `json:"instance,omitempty"`

	// Status Status code of the problem.
	Status int `json:"status,omitempty"`

	// Title Summary of the problem.
	Title string `json:"title,omitempty"`

	// Type Identification of the problem.
	Type string `json:"type,omitempty"`
}

// NewDeploymentBody Body content for a new deployment request.
type NewDeploymentBody struct {
	// Description Optional description of the new deployment.
	Description string `json:"description,omitempty"`

	// Title Title of the new deployment.
	Title string `json:"title"`
}

// ObjectAudit The audit details for an object.
type ObjectAudit struct {
	// Created Timestamp the object was created (RFC3339 format).
	Created string `json:"created"`

	// CreatedBy User that created the object.
	CreatedBy string `json:"createdBy"`

	// Updated Timestamp the object was last updated (RFC3339 format).
	Updated string `json:"updated,omitempty"`

	// UpdatedBy User that last updated the object.
	UpdatedBy string `json:"updatedBy,omitempty"`
}

// Status The code and name of a deployment status.
type Status struct {
	// Code Code of the status.
	Code int `json:"code"`

	// Name Display name for the status.
	Name string `json:"name"`
}

// Statuses List of deployment status codes and names.
type Statuses = []Status

// Target The details of a bundle target.
type Target struct {
	// Apikey Indicates an API-key is configured.
	Apikey bool `json:"apikey,omitempty"`

	// Compression Type of compression to use for the bundle (default = gzip).
	Compression int `json:"compression,omitempty"`

	// Headers List of optional HTTP headers to send.
	Headers []string `json:"headers,omitempty"`

	// Tls Indicates the connection will force the use of TLS.
	Tls bool `json:"tls,omitempty"`

	// Uri URI of the target PDP.
	Uri string `json:"uri"`
}

// BundleID defines model for BundleID.
type BundleID = string

// DeploymentID defines model for DeploymentID.
type DeploymentID = int

// BadRequest The response for an error (as defined by RFC9457).
type BadRequest = ErrorMessage

// CompressTypesFound List of compression type codes and names.
type CompressTypesFound = CompressTypes

// ConfigFound List of bundle deployment configurations.
type ConfigFound = BundleConfigs

// DeployStarted The details of a bundle deployment.
type DeployStarted = Deployment

// DeploymentFound The details of a bundle deployment.
type DeploymentFound = Deployment

// DeploymentsFound List of bundle deployments.
type DeploymentsFound = Deployments

// NotAuthenticated The response for an error (as defined by RFC9457).
type NotAuthenticated = ErrorMessage

// NotAuthorized The response for an error (as defined by RFC9457).
type NotAuthorized = ErrorMessage

// NotFound The response for an error (as defined by RFC9457).
type NotFound = ErrorMessage

// StatusesFound List of deployment status codes and names.
type StatusesFound = Statuses

// UnexpectedError The response for an error (as defined by RFC9457).
type UnexpectedError = ErrorMessage

// StartDeploymentJSONRequestBody defines body for StartDeployment for application/json ContentType.
type StartDeploymentJSONRequestBody = NewDeploymentBody
