openapi: 3.0.0

info:
  description: |
    OpenAPI specification for bundle management.
  version: 1.0.1
  title: Bundle management
  contact:
    name: G. Juijn
    url: https://gitlab.com/digilab.overheid.nl/ecosystem/ftv/open-ftv

servers:
  - url: https://localhost:8443/v1
    description: Local server.

tags:
  - name: status
    description: Operations on deployment statuses.
  - name: compression
    description: Operations on bundle compression types.
  - name: config
    description: Operations on bundle configuration.
  - name: deployment
    description: Operations on bundle deployments.
  - name: bundle
    description: Operations with bundles.

paths:
  /statuses:
    get:
      operationId: "get-statuses"
      summary: Retrieve deployment status codes.
      description: Endpoint to retrieve all deployment status codes and names.
      tags:
        - status
      responses:
        "200":
          $ref: "#/components/responses/StatusesFound"
        "401":
          $ref: "#/components/responses/NotAuthenticated"
        "403":
          $ref: "#/components/responses/NotAuthorized"
        "5XX":
          $ref: "#/components/responses/UnexpectedError"

  /compression-types:
    get:
      operationId: "get-compression-types"
      summary: Retrieve deployment compression types.
      description: Endpoint to retrieve all bundle compression types.
      tags:
        - compression
      responses:
        "200":
          $ref: "#/components/responses/CompressTypesFound"
        "401":
          $ref: "#/components/responses/NotAuthenticated"
        "403":
          $ref: "#/components/responses/NotAuthorized"
        "5XX":
          $ref: "#/components/responses/UnexpectedError"

  /bundle-configurations:
    get:
      operationId: "get-configurations"
      summary: Retrieve bundle configurations.
      description: Endpoint to retrieve the list of bundle configurations.
      tags:
        - config
      responses:
        "200":
          $ref: "#/components/responses/ConfigFound"
        "401":
          $ref: "#/components/responses/NotAuthenticated"
        "403":
          $ref: "#/components/responses/NotAuthorized"
        "5XX":
          $ref: "#/components/responses/UnexpectedError"

  /deployments:
    get:
      operationId: "get-deployments"
      summary: Retrieve deployments.
      description: Endpoint to retrieve the details of all deployments.
      tags:
        - deployment
      responses:
        "200":
          $ref: "#/components/responses/DeploymentsFound"
        "401":
          $ref: "#/components/responses/NotAuthenticated"
        "403":
          $ref: "#/components/responses/NotAuthorized"
        "5XX":
          $ref: "#/components/responses/UnexpectedError"

  /deployment/{key}:
    get:
      operationId: "get-deployment"
      summary: Retrieve deployment.
      description: Endpoint to retrieve the details of a specific deployment.
      tags:
        - deployment
      parameters:
        - $ref: "#/components/parameters/DeploymentID"
      responses:
        "200":
          $ref: "#/components/responses/DeploymentFound"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/NotAuthenticated"
        "403":
          $ref: "#/components/responses/NotAuthorized"
        "404":
          $ref: "#/components/responses/NotFound"
        "5XX":
          $ref: "#/components/responses/UnexpectedError"

  /deployment/last:
    get:
      operationId: "get-last-deployment"
      summary: Retrieve last deployment.
      description: Endpoint to retrieve the details of the last deployment.
      tags:
        - deployment
      responses:
        "200":
          $ref: "#/components/responses/DeploymentFound"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/NotAuthenticated"
        "403":
          $ref: "#/components/responses/NotAuthorized"
        "404":
          $ref: "#/components/responses/NotFound"
        "5XX":
          $ref: "#/components/responses/UnexpectedError"

  /deployment:
    post:
      operationId: "start-deployment"
      summary: Deploy a new version.
      description: Endpoint to start a new deployment.
      tags:
        - deployment
      requestBody:
        description: Parameters for a new bundle deployment.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewDeploymentBody"
      responses:
        "201":
          $ref: "#/components/responses/DeployStarted"
        "401":
          $ref: "#/components/responses/NotAuthenticated"
        "403":
          $ref: "#/components/responses/NotAuthorized"
        "5XX":
          $ref: "#/components/responses/UnexpectedError"

  /bundle/{id}:
    get:
      operationId: "get-bundle"
      summary: Retrieve the latest deployment bundle.
      description: |
        Endpoint to retrieve the latest deployment bundle and initialize the set of policies and static data.
        
        This endpoint should be called by PDPs during initialization
        when they are **not** configured with local policies and data.
      tags:
        - bundle
      parameters:
        - $ref: "#/components/parameters/BundleID"
      responses:
        "200":
          $ref: "#/components/responses/BundleFound"
        "401":
          $ref: "#/components/responses/NotAuthenticated"
        "403":
          $ref: "#/components/responses/NotAuthorized"
        "5XX":
          $ref: "#/components/responses/UnexpectedError"

  /bundle:
    post:
      operationId: "push-bundle"
      summary: Receive a new deployment bundle.
      description: |
        Endpoint to receive a new deployment bundle and replace the full set of policies and static data.
        
        This endpoint should be implemented by PDPs
        when they are **not** configured with local policies and data.
      tags:
        - bundle
      requestBody:
        description: Deployment bundle.
        content:
          application/octet-stream:
            schema:
              type: string
              format: byte
      responses:
        "201":
          $ref: "#/components/responses/BundleActivated"
        "401":
          $ref: "#/components/responses/NotAuthenticated"
        "403":
          $ref: "#/components/responses/NotAuthorized"
        "5XX":
          $ref: "#/components/responses/UnexpectedError"

components:
  parameters:
    DeploymentID:
      in: path
      name: key
      schema:
        type: integer
        minimum: 1
        maximum: 99999999
      required: true
      description: Unique version number of a deployment.
    BundleID:
      in: path
      name: id
      schema:
        type: string
        maxLength: 36
      required: true
      description: Unique deployment bundle identifier (UUID).

  responses:
    StatusesFound:
      description: Statuses found.
      headers:
        API-Version:
          schema:
            type: string
          description: Full version number of the API.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Statuses"

    CompressTypesFound:
      description: Compression types found.
      headers:
        API-Version:
          schema:
            type: string
          description: Full version number of the API.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/CompressTypes"

    ConfigFound:
      description: Bundle configurations found.
      headers:
        API-Version:
          schema:
            type: string
          description: Full version number of the API.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/BundleConfigs"

    DeploymentsFound:
      description: Deployments found.
      headers:
        API-Version:
          schema:
            type: string
          description: Full version number of the API.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Deployments"

    DeploymentFound:
      description: Deployment found.
      headers:
        API-Version:
          schema:
            type: string
          description: Full version number of the API.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Deployment"

    DeployStarted:
      description: Bundle deployment started.
      headers:
        API-Version:
          schema:
            type: string
          description: Full version number of the API.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Deployment"

    BundleActivated:
      description: Deployment bundle activated.
      headers:
        API-Version:
          schema:
            type: string
          description: Full version number of the API.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/BundleActivated"

    BundleFound:
      description: Deployment bundle found.
      headers:
        API-Version:
          schema:
            type: string
          description: Full version number of the API.
        Content-Encoding:
          schema:
            type: string
          description: Compression type.
      content:
        application/octet-stream:
          schema:
            type: string
            format: byte

    BadRequest:
      description: Bad request.
      headers:
        API-Version:
          schema:
            type: string
          description: Full version number of the API.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorMessage"

    NotAuthenticated:
      description: Not authenticated (401 status code).
      headers:
        API-Version:
          schema:
            type: string
          description: Full version number of the API.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorMessage"

    NotAuthorized:
      description: Not authorized (403 status code - access denied).
      headers:
        API-Version:
          schema:
            type: string
          description: Full version number of the API.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorMessage"

    NotFound:
      description: Resource not found.
      headers:
        API-Version:
          schema:
            type: string
          description: Full version number of the API.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorMessage"

    UnexpectedError:
      description: Unexpected error.
      headers:
        API-Version:
          schema:
            type: string
          description: Full version number of the API.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorMessage"

  schemas:
    NewDeploymentBody:
      type: object
      description: Body content for a new deployment request.
      properties:
        title:
          type: string
          minLength: 3
          maxLength: 80
          description: Title of the new deployment.
        description:
          type: string
          description: Optional description of the new deployment.
      required:
        - title

    ObjectAudit:
      type: object
      description: The audit details for an object.
      properties:
        created:
          type: string
          maxLength: 36
          description: Timestamp the object was created (RFC3339 format).
          example: "2025-08-15T07:53:41.493415Z"
        createdBy:
          type: string
          maxLength: 80
          description: User that created the object.
          example: "alice@wonderland.cc"
        updated:
          type: string
          maxLength: 36
          description: Timestamp the object was last updated (RFC3339 format).
          example: "2025-08-15T07:53:41.493415Z"
        updatedBy:
          type: string
          maxLength: 80
          description: User that last updated the object.
          example: "bob@wonderworld.cc"
      required:
        - created
        - createdBy

    Statuses:
      type: array
      description: List of deployment status codes and names.
      items:
        $ref: "#/components/schemas/Status"

    Status:
      type: object
      description: The code and name of a deployment status.
      properties:
        code:
          type: integer
          description: Code of the status.
          example: 1
        name:
          type: string
          description: Display name for the status.
          example: "Created"
      required:
        - code
        - name

    CompressTypes:
      type: array
      description: List of compression type codes and names.
      items:
        $ref: "#/components/schemas/CompressType"

    CompressType:
      type: object
      description: The code and name of a compression type.
      properties:
        code:
          type: integer
          description: Code of the compression type.
          example: 2
        name:
          type: string
          description: Display name for the compression type.
          example: "BZip2"
      required:
        - code
        - name

    BundleConfigs:
      type: array
      description: List of bundle deployment configurations.
      items:
        $ref: "#/components/schemas/BundleConfig"

    BundleConfig:
      type: object
      description: Bundle deployment configuration.
      properties:
        id:
          type: string
          maxLength: 36
          description: Unique identifier of this bundle deployment configuration (UUID).
        title:
          type: string
          maxLength: 80
          description: Title of this bundle deployment configuration.
        description:
          type: string
          description: Optional description of this bundle deployment configuration.
        version:
          type: boolean
          description: Indicates to bundle the version number.
        policies:
          type: boolean
          description: Indicates to bundle policies with matching tag.
        data:
          type: boolean
          description: Indicates to bundle attributes, entities and relations with matching tag.
        tags:
          type: array
          description: Tags to match against. A single matching tag is sufficient.
          items:
            type: string
            maxLength: 40
        targets:
          type: array
          items:
            $ref: "#/components/schemas/Target"
      required:
        - id
        - title
        - tags
        - targets

    Target:
      type: object
      description: The details of a bundle target.
      properties:
        uri:
          type: string
          description: URI of the target PDP.
        tls:
          type: boolean
          description: Indicates the connection will force the use of TLS.
        apikey:
          type: boolean
          description: Indicates an API-key is configured.
        compression:
          type: integer
          description: Type of compression to use for the bundle (default = gzip).
        headers:
          type: array
          description: List of optional HTTP headers to send.
          items:
            type: string
      required:
        - uri

    Deployments:
      type: array
      description: List of bundle deployments.
      items:
        $ref: "#/components/schemas/Deployment"

    Deployment:
      type: object
      description: The details of a bundle deployment.
      properties:
        version:
          type: integer
          description: Version number of the last deployment.
        title:
          type: string
          maxLength: 80
          description: Title of the deployment.
        description:
          type: string
          description: Optional description of the deployment.
        status:
          type: integer
          description: Status of the deployment.
        message:
          type: string
          description: Message for a failed deployment.
        audit:
          $ref: "#/components/schemas/ObjectAudit"
      required:
        - version
        - title
        - status
        - audit

    BundleActivated:
      type: object
      description: The details of a deployment bundle activation.
      properties:
        previousVersion:
          type: integer
          description: Version number of the replaced deployment.
      required:
        - previousVersion

    ErrorMessage:
      $ref: '../errors/openapi.yaml#/components/schemas/ErrorResponse'
