// Package attributes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2 DO NOT EDIT.
package attributes

// Attribute The content of an attribute (key/value pair).
type Attribute struct {
	// Audit The audit details for an object.
	Audit ObjectAudit `json:"audit"`

	// AuditLog Audit log for the attribute.
	AuditLog []AuditEntry `json:"auditLog,omitempty"`

	// Key The unique key of the attribute.
	Key string `json:"key"`

	// Metadata The metadata associated with an object.
	Metadata Metadata `json:"metadata"`

	// Status The current status of the attribute ('concept', 'accepted', 'deployed').
	Status string `json:"status"`

	// Type The optional type of a value. By default a value is stored as-is (e.g., JSON type).
	//
	// The following codes for type are supported:
	// "*string*", "*integer*", "*float*", "*boolean*", "*date*", "*time*", "*timestamp*".
	// Optionally, the type can be specified as one of the standard XSD types (e.g. "*xsd:byte*").
	//
	// An *integer* value (of any size) is stored as a 64-bit signed or unsigned integer.
	//
	// A *float* value is stored with double precision.
	//
	// A *boolean* value can be *true* (case-insensitive) or *1* to represent a true state,
	// or any other value to represent a false state.
	//
	// A *date*, *time* or *timestamp* value should adhere to the format as described in RFC3339.
	// If it cannot be decoded according to RFC3339, a 400 response status code will be returned.
	Type string `json:"type,omitempty"`

	// UsageData Usage data for the policy.
	UsageData []UsageData `json:"usageData,omitempty"`

	// Value The value of the attribute.
	Value interface{} `json:"value"`
}

// AttributeStatus The status of an attribute (key/value pair).
type AttributeStatus struct {
	// Key The unique key of the attribute.
	Key string `json:"key"`

	// Status The current status of the attribute ('concept', 'accepted', 'deployed').
	Status string `json:"status"`
}

// AttributeVersion The content of a specific version of an attribute (key/value pair).
type AttributeVersion struct {
	// Key The unique key of the attribute.
	Key string `json:"key"`

	// Metadata The metadata associated with an object.
	Metadata Metadata `json:"metadata"`

	// Type The optional type of a value. By default a value is stored as-is (e.g., JSON type).
	//
	// The following codes for type are supported:
	// "*string*", "*integer*", "*float*", "*boolean*", "*date*", "*time*", "*timestamp*".
	// Optionally, the type can be specified as one of the standard XSD types (e.g. "*xsd:byte*").
	//
	// An *integer* value (of any size) is stored as a 64-bit signed or unsigned integer.
	//
	// A *float* value is stored with double precision.
	//
	// A *boolean* value can be *true* (case-insensitive) or *1* to represent a true state,
	// or any other value to represent a false state.
	//
	// A *date*, *time* or *timestamp* value should adhere to the format as described in RFC3339.
	// If it cannot be decoded according to RFC3339, a 400 response status code will be returned.
	Type string `json:"type,omitempty"`

	// Value The value of the attribute.
	Value interface{} `json:"value"`

	// Version The version number of the attribute.
	Version int `json:"version"`
}

// AttributeVersions defines model for AttributeVersions.
type AttributeVersions = []AttributeVersion

// Attributes defines model for Attributes.
type Attributes = []Attribute

// AuditEntry Metadata about how, when and by whom an object has been manipulated.
type AuditEntry struct {
	// Created Timestamp of the log entry in RFC3339 format.
	Created string `json:"created,omitempty"`

	// Operation Operation performed on the object. Any of ["C", "U", "D"].
	Operation string `json:"operation"`

	// UserId Unique identifier of the user who operated on the object.
	UserId string `json:"userId,omitempty"`
}

// Entities defines model for Entities.
type Entities = []Entity

// Entity The content of an entity.
//
// The combination of *type* and *id* defines the unique key of an entity.
type Entity struct {
	// Attributes Optional attributes of the entity.
	Attributes []Attribute `json:"attributes,omitempty"`

	// Audit The audit details for an object.
	Audit ObjectAudit `json:"audit"`

	// AuditLog Audit log for the entity.
	AuditLog []AuditEntry `json:"auditLog,omitempty"`

	// Id The identification of the entity.
	Id string `json:"id"`

	// Metadata The metadata associated with an object.
	Metadata Metadata `json:"metadata"`

	// Status The current status of the entity ('concept', 'accepted', 'deployed').
	Status string `json:"status"`

	// Type The type of entity.
	Type string `json:"type"`

	// UsageData Usage data for the policy.
	UsageData []UsageData `json:"usageData,omitempty"`
}

// EntityStatus The status of an entity.
type EntityStatus struct {
	// Id The identification of the entity.
	Id string `json:"id"`

	// Status The current status of the entity ('concept', 'accepted', 'deployed').
	Status string `json:"status"`

	// Type The type of entity.
	Type string `json:"type"`
}

// EntityVersion The content of a specific version of an entity.
type EntityVersion struct {
	// Attributes Optional attributes of the entity.
	Attributes []Attribute `json:"attributes,omitempty"`

	// Id The identification of the entity.
	Id string `json:"id"`

	// Metadata The metadata associated with an object.
	Metadata Metadata `json:"metadata"`

	// Type The type of entity.
	Type string `json:"type"`

	// Version The version number of the entity.
	Version int `json:"version"`
}

// EntityVersions defines model for EntityVersions.
type EntityVersions = []EntityVersion

// Error The response for an error (as defined by RFC9457).
type Error struct {
	// Detail Detailed description of the problem.
	Detail string `json:"detail,omitempty"`

	// Instance Identification of the problem instance.
	Instance string `json:"instance,omitempty"`

	// Status Status code of the problem.
	Status int `json:"status,omitempty"`

	// Title Summary of the problem.
	Title string `json:"title,omitempty"`

	// Type Identification of the problem.
	Type string `json:"type,omitempty"`
}

// Metadata The metadata associated with an object.
type Metadata struct {
	// Description Detailed description of the object.
	Description string `json:"description,omitempty"`

	// Tags List of tags the object is annotated with.
	//
	// This is used to determine which PDP (or set of PDPs) objects can be pushed to.
	//
	// Verify with the policies.tags endpoint.
	Tags []string `json:"tags,omitempty"`

	// Title The title of the object. E.g., a short description.
	Title string `json:"title"`
}

// ObjectAudit The audit details for an object.
type ObjectAudit struct {
	// Created Timestamp the object was created (RFC3339 format).
	Created string `json:"created"`

	// CreatedBy User that created the object.
	CreatedBy string `json:"createdBy"`

	// Updated Timestamp the object was last updated (RFC3339 format).
	Updated string `json:"updated,omitempty"`

	// UpdatedBy User that last updated the object.
	UpdatedBy string `json:"updatedBy,omitempty"`
}

// Relation The content of a relation.
//
// The combination of *subject type/id*, *relation* and *object type/id* must be unique for all relations.
type Relation struct {
	// Attributes Optional attributes of the relation.
	Attributes []Attribute `json:"attributes,omitempty"`

	// Audit The audit details for an object.
	Audit ObjectAudit `json:"audit"`

	// AuditLog Audit log for the relation.
	AuditLog []AuditEntry `json:"auditLog,omitempty"`

	// Id The unique identifier of the relation (UUID).
	Id string `json:"id"`

	// Metadata The metadata associated with an object.
	Metadata Metadata `json:"metadata"`

	// ObjectId The identifier of the object of the relation.
	ObjectId string `json:"objectId"`

	// ObjectType The type of object of the relation.
	ObjectType string `json:"objectType"`

	// Relation The type of relation.
	Relation string `json:"relation"`

	// Status The current status of the relation ('concept', 'accepted', 'deployed').
	Status string `json:"status"`

	// SubjectId The identifier of the subject of the relation.
	SubjectId string `json:"subjectId"`

	// SubjectType The type of subject of the relation.
	SubjectType string `json:"subjectType"`

	// UsageData Usage data for the policy.
	UsageData []UsageData `json:"usageData,omitempty"`
}

// RelationStatus The status of a relation.
type RelationStatus struct {
	// Id The unique identifier of the relation (UUID).
	Id string `json:"id"`

	// Status The current status of the relation ('concept', 'accepted', 'deployed').
	Status string `json:"status"`
}

// RelationVersion The content of a specific version of a relation.
type RelationVersion struct {
	// Attributes Optional attributes of the relation.
	Attributes []Attribute `json:"attributes,omitempty"`

	// Id The unique identifier of the relation (UUID).
	Id string `json:"id"`

	// Metadata The metadata associated with an object.
	Metadata Metadata `json:"metadata"`

	// ObjectId The identifier of the object of the relation.
	ObjectId string `json:"objectId"`

	// ObjectType The type of object of the relation.
	ObjectType string `json:"objectType"`

	// Relation The type of relation.
	Relation string `json:"relation"`

	// SubjectId The identifier of the subject of the relation.
	SubjectId string `json:"subjectId"`

	// SubjectType The type of subject of the relation.
	SubjectType string `json:"subjectType"`

	// Version The version number of the relation.
	Version int `json:"version"`
}

// RelationVersions defines model for RelationVersions.
type RelationVersions = []RelationVersion

// Relations defines model for Relations.
type Relations = []Relation

// UsageData Metadata about when and where the object is used.
type UsageData struct {
	// Bundle Code of the bundle the object was included in.
	Bundle string `json:"bundle,omitempty"`

	// Created Timestamp the deployment was created (RFC3339 format).
	Created string `json:"created,omitempty"`

	// CreatedBy User that created the deployment.
	CreatedBy string `json:"createdBy,omitempty"`

	// Status Status of the deployment.
	Status string `json:"status,omitempty"`

	// Version Version number of the deployment.
	Version int `json:"version,omitempty"`
}

// AttributeKey defines model for AttributeKey.
type AttributeKey = string

// EntityID defines model for EntityID.
type EntityID = string

// EntityType defines model for EntityType.
type EntityType = string

// ForceUpsert defines model for ForceUpsert.
type ForceUpsert = bool

// IgnoreMissing defines model for IgnoreMissing.
type IgnoreMissing = bool

// RelationID defines model for RelationID.
type RelationID = string

// Version defines model for Version.
type Version = int

// AccessDenied The response for an error (as defined by RFC9457).
type AccessDenied = Error

// AlreadyExists The response for an error (as defined by RFC9457).
type AlreadyExists = Error

// AttributeResponse The content of an attribute (key/value pair).
type AttributeResponse = Attribute

// AttributeVersionResponse The content of a specific version of an attribute (key/value pair).
type AttributeVersionResponse = AttributeVersion

// AttributeVersionsResponse defines model for AttributeVersionsResponse.
type AttributeVersionsResponse = AttributeVersions

// AttributesResponse defines model for AttributesResponse.
type AttributesResponse = Attributes

// BadRequest The response for an error (as defined by RFC9457).
type BadRequest = Error

// EntitiesResponse defines model for EntitiesResponse.
type EntitiesResponse = Entities

// EntityResponse The content of an entity.
//
// The combination of *type* and *id* defines the unique key of an entity.
type EntityResponse = Entity

// EntityVersionResponse The content of a specific version of an entity.
type EntityVersionResponse = EntityVersion

// EntityVersionsResponse defines model for EntityVersionsResponse.
type EntityVersionsResponse = EntityVersions

// NotAuthorized The response for an error (as defined by RFC9457).
type NotAuthorized = Error

// NotFound The response for an error (as defined by RFC9457).
type NotFound = Error

// RelationResponse The content of a relation.
//
// The combination of *subject type/id*, *relation* and *object type/id* must be unique for all relations.
type RelationResponse = Relation

// RelationVersionResponse The content of a specific version of a relation.
type RelationVersionResponse = RelationVersion

// RelationVersionsResponse defines model for RelationVersionsResponse.
type RelationVersionsResponse = RelationVersions

// RelationsResponse defines model for RelationsResponse.
type RelationsResponse = Relations

// UnexpectedError The response for an error (as defined by RFC9457).
type UnexpectedError = Error

// RemoveAttributeParams defines parameters for RemoveAttribute.
type RemoveAttributeParams struct {
	// Force Ignore missing data during a delete operation.
	Force IgnoreMissing `form:"force,omitempty" json:"force,omitempty"`
}

// AddAttributeParams defines parameters for AddAttribute.
type AddAttributeParams struct {
	// Force Force upsert during a put/post operation.
	Force ForceUpsert `form:"force,omitempty" json:"force,omitempty"`
}

// ReplaceAttributeParams defines parameters for ReplaceAttribute.
type ReplaceAttributeParams struct {
	// Force Force upsert during a put/post operation.
	Force ForceUpsert `form:"force,omitempty" json:"force,omitempty"`
}

// DeleteEntityParams defines parameters for DeleteEntity.
type DeleteEntityParams struct {
	// Force Ignore missing data during a delete operation.
	Force IgnoreMissing `form:"force,omitempty" json:"force,omitempty"`
}

// AddEntityParams defines parameters for AddEntity.
type AddEntityParams struct {
	// Force Force upsert during a put/post operation.
	Force ForceUpsert `form:"force,omitempty" json:"force,omitempty"`
}

// RemoveEntityParams defines parameters for RemoveEntity.
type RemoveEntityParams struct {
	// Force Force upsert during a put/post operation.
	Force ForceUpsert `form:"force,omitempty" json:"force,omitempty"`
}

// RemoveRelationParams defines parameters for RemoveRelation.
type RemoveRelationParams struct {
	// Force Ignore missing data during a delete operation.
	Force IgnoreMissing `form:"force,omitempty" json:"force,omitempty"`
}

// AddRelationParams defines parameters for AddRelation.
type AddRelationParams struct {
	// Force Force upsert during a put/post operation.
	Force ForceUpsert `form:"force,omitempty" json:"force,omitempty"`
}

// ReplaceRelationParams defines parameters for ReplaceRelation.
type ReplaceRelationParams struct {
	// Force Force upsert during a put/post operation.
	Force ForceUpsert `form:"force,omitempty" json:"force,omitempty"`
}

// AddAttributeJSONRequestBody defines body for AddAttribute for application/json ContentType.
type AddAttributeJSONRequestBody = Attribute

// ReplaceAttributeJSONRequestBody defines body for ReplaceAttribute for application/json ContentType.
type ReplaceAttributeJSONRequestBody = Attribute

// StatusAttributeJSONRequestBody defines body for StatusAttribute for application/json ContentType.
type StatusAttributeJSONRequestBody = AttributeStatus

// AddEntityJSONRequestBody defines body for AddEntity for application/json ContentType.
type AddEntityJSONRequestBody = Entity

// RemoveEntityJSONRequestBody defines body for RemoveEntity for application/json ContentType.
type RemoveEntityJSONRequestBody = Entity

// StatusEntityJSONRequestBody defines body for StatusEntity for application/json ContentType.
type StatusEntityJSONRequestBody = EntityStatus

// AddRelationJSONRequestBody defines body for AddRelation for application/json ContentType.
type AddRelationJSONRequestBody = Relation

// ReplaceRelationJSONRequestBody defines body for ReplaceRelation for application/json ContentType.
type ReplaceRelationJSONRequestBody = Relation

// StatusRelationJSONRequestBody defines body for StatusRelation for application/json ContentType.
type StatusRelationJSONRequestBody = RelationStatus
