// Package attributes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package attributes

// Attribute The content of an attribute (key/value pair).
type Attribute struct {
	// Audit The audit details for an object.
	Audit ObjectAudit `json:"audit"`

	// AuditLog Audit log for the attribute.
	AuditLog []AuditEntry `json:"auditLog,omitempty"`

	// Key The unique key of the attribute.
	Key string `json:"key"`

	// Metadata The metadata associated with an object.
	Metadata Metadata `json:"metadata"`

	// Type The optional type of a value. By default a value is stored as-is (e.g., JSON type).
	//
	// The following codes for type are supported:
	// "*string*", "*integer*", "*float*", "*boolean*", "*date*", "*time*", "*timestamp*".
	// Optionally, the type can be specified as one of the standard XSD types (e.g. "*xsd:byte*").
	//
	// An *integer* value (of any size) is stored as a 64-bit signed or unsigned integer.
	//
	// A *float* value is stored with double precision.
	//
	// A *boolean* value can be *true* (case-insensitive) or *1* to represent a true state,
	// or any other value to represent a false state.
	//
	// A *date*, *time* or *timestamp* value should adhere to the format as described in RFC3339.
	// If it cannot be decoded according to RFC3339, a 400 response status code will be returned.
	Type string `json:"type,omitempty"`

	// UsageData Usage data for the policy.
	UsageData []UsageData `json:"usageData,omitempty"`

	// Value The value of the attribute.
	Value interface{} `json:"value"`
}

// Attributes defines model for Attributes.
type Attributes = []Attribute

// AuditEntry Metadata about how, when and by whom an object has been manipulated.
type AuditEntry struct {
	// Created Timestamp of the log entry in RFC3339 format.
	Created string `json:"created,omitempty"`

	// Operation Operation performed on the object. Any of ["C", "U", "D"].
	Operation string `json:"operation"`

	// UserId Unique identifier of the user who operated on the object.
	UserId string `json:"userId,omitempty"`
}

// Entities defines model for Entities.
type Entities = []Entity

// Entity The content of an entity.
//
// The combination of *type* and *id* defines the unique key of an entity.
type Entity struct {
	// Attributes Optional attributes of the entity.
	Attributes []Attribute `json:"attributes,omitempty"`

	// Audit The audit details for an object.
	Audit ObjectAudit `json:"audit"`

	// AuditLog Audit log for the entity.
	AuditLog []AuditEntry `json:"auditLog,omitempty"`

	// Id The identification of the entity.
	Id string `json:"id"`

	// Metadata The metadata associated with an object.
	Metadata Metadata `json:"metadata"`

	// Type The type of entity.
	Type string `json:"type"`

	// UsageData Usage data for the policy.
	UsageData []UsageData `json:"usageData,omitempty"`
}

// Error The response for an error (as defined by RFC9457).
type Error struct {
	// Detail Detailed description of the problem.
	Detail string `json:"detail,omitempty"`

	// Instance Identification of the problem instance.
	Instance string `json:"instance,omitempty"`

	// Status Status code of the problem.
	Status int `json:"status,omitempty"`

	// Title Summary of the problem.
	Title string `json:"title,omitempty"`

	// Type Identification of the problem.
	Type string `json:"type,omitempty"`
}

// Metadata The metadata associated with an object.
type Metadata struct {
	// Description Detailed description of the object.
	Description string `json:"description,omitempty"`

	// Tags List of tags the object is annotated with.
	//
	// This is used to determine which PDP (or set of PDPs) objects can be pushed to.
	//
	// Verify with the policies.tags endpoint.
	Tags []string `json:"tags,omitempty"`

	// Title The title of the object. E.g., a short description.
	Title string `json:"title"`
}

// ObjectAudit The audit details for an object.
type ObjectAudit struct {
	// Created Timestamp the object was created (RFC3339 format).
	Created string `json:"created"`

	// CreatedBy User that created the object.
	CreatedBy string `json:"createdBy"`

	// Updated Timestamp the object was last updated (RFC3339 format).
	Updated string `json:"updated,omitempty"`

	// UpdatedBy User that last updated the object.
	UpdatedBy string `json:"updatedBy,omitempty"`
}

// Relation The content of a relation.
//
// The combination of *subject type/id*, *relation* and *object type/id* must be unique for all relations.
type Relation struct {
	// Attributes Optional attributes of the relation.
	Attributes []Attribute `json:"attributes,omitempty"`

	// Audit The audit details for an object.
	Audit ObjectAudit `json:"audit"`

	// AuditLog Audit log for the relation.
	AuditLog []AuditEntry `json:"auditLog,omitempty"`

	// Id The unique identifier of the relation (UUID).
	Id string `json:"id"`

	// Metadata The metadata associated with an object.
	Metadata Metadata `json:"metadata"`

	// ObjectId The identifier of the object of the relation.
	ObjectId string `json:"objectId"`

	// ObjectType The type of object of the relation.
	ObjectType string `json:"objectType"`

	// Relation The type of relation.
	Relation string `json:"relation"`

	// SubjectId The identifier of the subject of the relation.
	SubjectId string `json:"subjectId"`

	// SubjectType The type of subject of the relation.
	SubjectType string `json:"subjectType"`

	// UsageData Usage data for the policy.
	UsageData []UsageData `json:"usageData,omitempty"`
}

// Relations defines model for Relations.
type Relations = []Relation

// UsageData Metadata about when and where the object is used.
type UsageData struct {
	// Bundle Code of the bundle the object was included in.
	Bundle string `json:"bundle,omitempty"`

	// Created Timestamp the deployment was created (RFC3339 format).
	Created string `json:"created,omitempty"`

	// CreatedBy User that created the deployment.
	CreatedBy string `json:"createdBy,omitempty"`

	// Status Status of the deployment.
	Status string `json:"status,omitempty"`

	// Version Version number of the deployment.
	Version int `json:"version,omitempty"`
}

// AttributeKey defines model for AttributeKey.
type AttributeKey = string

// EntityID defines model for EntityID.
type EntityID = string

// EntityType defines model for EntityType.
type EntityType = string

// ForceUpsert defines model for ForceUpsert.
type ForceUpsert = bool

// IgnoreMissing defines model for IgnoreMissing.
type IgnoreMissing = bool

// ObjectID defines model for ObjectID.
type ObjectID = string

// ObjectType defines model for ObjectType.
type ObjectType = string

// RelationType defines model for RelationType.
type RelationType = string

// SubjectID defines model for SubjectID.
type SubjectID = string

// SubjectType defines model for SubjectType.
type SubjectType = string

// AccessDenied The response for an error (as defined by RFC9457).
type AccessDenied = Error

// AlreadyExists The response for an error (as defined by RFC9457).
type AlreadyExists = Error

// AttributeResponse The content of an attribute (key/value pair).
type AttributeResponse = Attribute

// AttributesResponse defines model for AttributesResponse.
type AttributesResponse = Attributes

// BadRequest The response for an error (as defined by RFC9457).
type BadRequest = Error

// EntitiesResponse defines model for EntitiesResponse.
type EntitiesResponse = Entities

// EntityResponse The content of an entity.
//
// The combination of *type* and *id* defines the unique key of an entity.
type EntityResponse = Entity

// NotAuthorized The response for an error (as defined by RFC9457).
type NotAuthorized = Error

// NotFound The response for an error (as defined by RFC9457).
type NotFound = Error

// RelationResponse The content of a relation.
//
// The combination of *subject type/id*, *relation* and *object type/id* must be unique for all relations.
type RelationResponse = Relation

// RelationsResponse defines model for RelationsResponse.
type RelationsResponse = Relations

// UnexpectedError The response for an error (as defined by RFC9457).
type UnexpectedError = Error

// RemoveAttributeParams defines parameters for RemoveAttribute.
type RemoveAttributeParams struct {
	// Force Ignore missing data during a delete operation.
	Force IgnoreMissing `form:"force,omitempty" json:"force,omitempty"`
}

// AddAttributeParams defines parameters for AddAttribute.
type AddAttributeParams struct {
	// Force Force upsert during a put/post operation.
	Force ForceUpsert `form:"force,omitempty" json:"force,omitempty"`
}

// ReplaceAttributeParams defines parameters for ReplaceAttribute.
type ReplaceAttributeParams struct {
	// Force Force upsert during a put/post operation.
	Force ForceUpsert `form:"force,omitempty" json:"force,omitempty"`
}

// DeleteEntityParams defines parameters for DeleteEntity.
type DeleteEntityParams struct {
	// Force Ignore missing data during a delete operation.
	Force IgnoreMissing `form:"force,omitempty" json:"force,omitempty"`
}

// AddEntityParams defines parameters for AddEntity.
type AddEntityParams struct {
	// Force Force upsert during a put/post operation.
	Force ForceUpsert `form:"force,omitempty" json:"force,omitempty"`
}

// RemoveEntityParams defines parameters for RemoveEntity.
type RemoveEntityParams struct {
	// Force Force upsert during a put/post operation.
	Force ForceUpsert `form:"force,omitempty" json:"force,omitempty"`
}

// RemoveRelationParams defines parameters for RemoveRelation.
type RemoveRelationParams struct {
	// Force Ignore missing data during a delete operation.
	Force IgnoreMissing `form:"force,omitempty" json:"force,omitempty"`
}

// AddRelationParams defines parameters for AddRelation.
type AddRelationParams struct {
	// Force Force upsert during a put/post operation.
	Force ForceUpsert `form:"force,omitempty" json:"force,omitempty"`
}

// ReplaceRelationParams defines parameters for ReplaceRelation.
type ReplaceRelationParams struct {
	// Force Force upsert during a put/post operation.
	Force ForceUpsert `form:"force,omitempty" json:"force,omitempty"`
}

// AddAttributeJSONRequestBody defines body for AddAttribute for application/json ContentType.
type AddAttributeJSONRequestBody = Attribute

// ReplaceAttributeJSONRequestBody defines body for ReplaceAttribute for application/json ContentType.
type ReplaceAttributeJSONRequestBody = Attribute

// AddEntityJSONRequestBody defines body for AddEntity for application/json ContentType.
type AddEntityJSONRequestBody = Entity

// RemoveEntityJSONRequestBody defines body for RemoveEntity for application/json ContentType.
type RemoveEntityJSONRequestBody = Entity

// AddRelationJSONRequestBody defines body for AddRelation for application/json ContentType.
type AddRelationJSONRequestBody = Relation

// ReplaceRelationJSONRequestBody defines body for ReplaceRelation for application/json ContentType.
type ReplaceRelationJSONRequestBody = Relation
