# yaml-language-server: $schema=https://raw.githubusercontent.com/deepmap/oapi-codegen/HEAD/configuration-schema.json
package: attributes
output: attributes.go
generate:
  models: true
output-options:
  skip-prune: true
