{{- if and (eq .Values.config.policySource "local") (not .Values.config.policiesExistingConfigMap) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "open-ftv-pdp.fullname" . }}-policies
  labels:
    {{- include "open-ftv-pdp.labels" . | nindent 4 }}
data:
{{- range $filename, $content := .Values.config.policies }}
  {{ $filename }}: |
    {{- $content | nindent 4 }}
{{- end }}
{{- end }}
