apiVersion: v1
kind: Service
metadata:
  name: {{ include "open-ftv-pdp.fullname" . }}
  labels:
    {{- include "open-ftv-pdp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "open-ftv-pdp.selectorLabels" . | nindent 4 }}
  ports:
    - name: {{ .Values.config.tls.enabled | ternary "https" "http" }}
      protocol: TCP
      port: {{ .Values.config.tls.enabled | ternary .Values.service.httpsPort .Values.service.httpPort }}
      targetPort: http
